### ISSUE TITLE
Higher samplerate audio renders incorrectly

### ISSUE THREAD

**Issue by MrGriva** [olive-editor/olive#753] opened 2019-04-02 22:22 UTC
### System Information

**Olive version:** a0f62990
**Operating system:** Windows 10 64-bit

### Detailed Description

Audio files with higher samplerates than 48000 are still reproduced at 48000 so inserting a higher samplerate file (p.e. 96000) would play the file at half speed. Even though it may play correctly while editing, exporting the project will reproduce the audio at half speed.
Not that a lot of people will use 96khz wav files for editing but just a random thing i've noticed.

**Comment by itsmattkc** [comment] 2019-04-18 23:40
Does 3251a420c066c093a54673304be89397287744e8 fix this?

**Comment by itsmattkc** [comment] 2019-05-02 03:22
I believe this is a duplicate of #735.

**Closed by itsmattkc** 2019-05-02 03:22 UTC
