### ISSUE TITLE
[PLAYBACK] Displayed audio level is always zero while playing

### ISSUE THREAD

**Issue by TechPersonYT** [olive-editor/olive#2238] opened 2023-06-20 16:09 UTC
**Commit Hash** 
1687a721

**Platform** 
Linux Mint 21.1 5.15.0-72-generic

**Summary**
Playing audio in the timeline rarely results in any audio level being shown in the bottom right. Scrubbing timeline audio yields intended behavior. Certain edge cases show changing audio levels during playback, but I have yet to reproduce them.

**Additional Information / Output**

https://github.com/olive-editor/olive/assets/39715756/a7add492-f78c-4472-b1f6-cc9084610e57

Steps to reproduce:

1. New project
2. Place any audio on the timeline
3. Play

**Comment by itsmattkc** [comment] 2023-06-20 16:56
Duplicate of #2199

**Closed by itsmattkc** 2023-06-20 16:56 UTC
Labels: Playback, Triage
