### ISSUE TITLE
Exact layout should be preserved across sessions

### ISSUE THREAD

**Issue by prokoudine** [olive-editor/olive#565] opened 2019-02-28 07:52 UTC
Currently, Olive forgets resized state of docked panels and e.g. draws the upper half of the main window with three groups of docks taking equal 1/3 of width each, although the docks were resized the last time Olive ran.

Olive should be able to preserve resized state of docks across sessions.

**Comment by itsmattkc** [comment] 2019-02-28 11:05
Duplicate of #424, but reminded me to look into it properly haha. Properly implemented in eb4c2fdad382a16bf39fce4f25b2828bd088f972

**Closed by itsmattkc** 2019-02-28 11:05 UTC
