### ISSUE TITLE
Razor Tool resets Effects Properties to default

### ISSUE THREAD

**Issue by Corruptinator** [olive-editor/olive#272] opened 2019-01-08 05:32 UTC
I happen to notice after using the Razor Tool to split one track, the former track (Left Side) retains the Effects property variable such as Color Correction, Volume, etc to remain intact while the latter (Right Side) has the property variables reset back to the default setup. Shouldn't the effects properties remain unchanged after using the Razor Tool?

**Comment by itsmattkc** [comment] 2019-01-08 06:01
Thanks for reporting this, it was a regression due to the rewrite I did to the effect keyframe code. Should be fixed now.

**Closed** 2019-01-08 06:00 UTC

**Comment by Corruptinator** [comment] 2019-01-08 07:43
No problem!
