### ISSUE TITLE
Ripple delete freeze the strip in latest node build[Bug]

### ISSUE THREAD

**Issue by cgvirus** [olive-editor/olive#931] opened 2019-05-08 18:13 UTC
**Describe the bug**
Ripple delete freeze/non selectable the strip in latest node build
Olive (May 2019 | Alpha | b4ea83de)

**To Reproduce**
1. cut some strip
2. use ripple delete by right click
3. Strip is frozen and non selectable
**Expected behavior**
Should ripple delete

No BT can be produced with GBD as Olive doesn't crash. QT Creator can't send any trace as well.

**Comment by itsmattkc** [comment] 2019-05-08 18:43
Duplicate of #882?

**Comment by cgvirus** [comment] 2019-05-08 18:46
Seems to be a consistent bug in Olive (May 2019 | Alpha | b4ea83d)
Mainly after merging nodes commits 5 days ago

**Closed** 2019-05-09 01:11 UTC

**Comment by cgvirus** [comment] 2019-05-09 18:53
@itsmattkc Thanks for the fix.
Seems like some bug has been eliminated although some are still around. If the `ripple delete empty space` is called before the header of the strip it deletes the first strip not only the space. Also makes it non selectable. 
Other than that things are all fine. Like `ripple delete empty space` in between two strips works as usual. Demo:
[demo4.zip](https://github.com/olive-editor/olive/files/3163551/demo4.zip)
