### ISSUE TITLE
[EXPORT] Extremely high memory usage and extremely long ETA

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#1612] opened 2021-05-06 22:18 UTC
**Commit Hash** 32e11bb (and previous as well)

**Platform** Manjaro Linux

**Summary**

Exporting 20 seconds of 6K30p 10-bit footage to a standard MP4 file results in 32 GB of RAM being filled, another 20 GB or SWAP being filled and an ETA of ~13 hours. I've terminated the render, as my system became completely unresponsive due to Olive's memory usage.

**Additional Information / Output**

Here's a video demonstrating the issue:

https://youtu.be/voJck6k8VV0

I have had the same problem in previous versions of Olive 0.2, and I've tried again after reading on Patreon that this issue was supposedly resolved. Maybe what I'm experiencing is a different problem...

**Comment by itsmattkc** [comment] 2021-05-06 22:57
Would you be able to try 2e96b57319b7bc641d5b4740470f6aa39a48119c, I want to see if this is a regression introduced after that commit.

Also is this exclusive to exporting 6K footage or does this occur in all exports?

**Comment by unfa** [comment] 2021-05-07 08:27
I can and will do all of the above, though it may take me a few days.
So far I've tested with 4K and 6K footage - results where pretty much the same.

**Comment by dentex** [comment] 2021-05-08 07:20
I can report the same issue, trying to export a sequence containing a short intro in 2.7k 30fps and a few clips in 2.7k 60fps.
I added a few details here: https://discord.com/channels/549629829730009089/550238656468746261/840321130543841280
Basically the used RAM starts to grow with the rendering. I'm exporting about 30 sec of video and around 75% the appimage crashes. If I export really a few seconds, it works.

I'm on Linux Mint 20.1: [hardinfo_report.txt](https://github.com/olive-editor/olive/files/6445423/hardinfo_report.txt)
terminal output: [terminal_output.txt](https://github.com/olive-editor/olive/files/6445424/terminal_output.txt)

**Comment by dentex** [comment] 2021-05-08 10:49
@itsmattkc I confirm that https://github.com/olive-editor/olive/commit/2e96b57319b7bc641d5b4740470f6aa39a48119c does export the sequence.

**Comment by itsmattkc** [comment] 2021-05-08 13:32
@dentex Thanks, good to know

@unfa and anyone else experiencing this, you can use a precompiled AppImage from here of 2e96b57319b7bc641d5b4740470f6aa39a48119c: https://github.com/olive-editor/olive/suites/2600404950/artifacts/56861217

**Comment by unfa** [comment] 2021-05-08 13:44
@itsmattkc I've just started a video export using this build and it goes without issues. ETA is sane, RAM usage is sane, and progress is made. Same 6K footage, this time MKV output, but otherwise nothing changed. I'll try with MP4 again to make sure it's not depandant on the format.

**Comment by unfa** [comment] 2021-05-08 14:00
I'm tested now with 029b826f.

![image](https://user-images.githubusercontent.com/491704/117541862-30d58200-b016-11eb-8b02-fa9fce7c3922.png)

RAM consumption is very high, but not as high as previously, and the ETA and progress made within reasonable bounds.
It has taken a few good minutes of 0% progress though. Olive was processing something taking about 250% CPU (my CPU is 8-core 16-thread). But after that it finally started actual export and it's going. Memory usage is sitting stable now:

![image](https://user-images.githubusercontent.com/491704/117541907-75611d80-b016-11eb-9e53-870851b5f6ae.png)

**Comment by unfa** [comment] 2021-05-08 14:02
Wow, memory usage suddenly went up during export again, reached my maximum:

![image](https://user-images.githubusercontent.com/491704/117541943-b2c5ab00-b016-11eb-8e88-ed08752c441a.png)

I had to SIGSTOP Olive.

**Comment by dentex** [comment] 2021-05-08 14:19
> Wow, memory usage suddenly went up during export again, reached my maximum:

In my case, being only a 30 seconds long sequence, maybe it was able to finish the export. In fact I did notice too an increment in RAM usage, but not as much as with the latest appimage.

> I had to SIGSTOP Olive.

Another difference is that on my distro the process is being stopped automatically (see terminal output above).

**Comment by itsmattkc** [comment] 2021-05-08 14:34
Okay thank you for testing, my belief is that this regression was introduced in 3903f70259a1df31e70e89b6a504f69091e06607. I'll work on a fix tomorrow.

**Comment by unfa** [comment] 2021-05-08 14:36
Right now after I added 25G of extra SWAP and resumed Olive my PC is.cpmpletely unresponsive, but refreshes the display once every 10 minutes or so. Not sure what's gonna happen next.

**Comment by dentex** [comment] 2021-05-08 15:48
Is it possible that Olive retains the rendered video into RAM instead of flushing it to the tmp file? I'm exporting right now the same 30 sec long video, but with a noticeable lower compression: the used RAM is growing through 10GB out of 16 (it's not gonna make it...) and the tmp file is still at 44 byte.

**Comment by unfa** [comment] 2021-05-09 01:15
@itsmattkc In my experience on Linux that is not true. When Olive is rendering a file I can clearly see the file size change both in file manager (Dolphin) and terminal (`ls -oh`) after every chunk of the video is written to disk. Sure, there may be some OS-level cache involved, but files visibly change their size in Linux even before they are closed by software writing to them. If a file stays at 44 bytes (header) for a long period of time - it's a sign the software didn't issue a write in my opinion, not that it just didn't close the file.

It's normal for my exports to be 44 bytes for a short while - I think it's the time after writing the header but before the first GOP is complete.

**Comment by itsmattkc** [comment] 2021-05-09 01:34
It's possible FFmpeg is buffering frames in memory before writing them, but even then, it's not related to the regression introduced after 2e96b57319b7bc641d5b4740470f6aa39a48119c.

**Comment by dentex** [comment] 2021-05-09 09:27
> No, I'm fairly certain that's just an artifact of the fact that it doesn't "close" the file until the end so the file size doesn't appear to update.
> 
> Is this still commit [2e96b57](https://github.com/olive-editor/olive/commit/2e96b57319b7bc641d5b4740470f6aa39a48119c)? What do you mean by "lower compression"? Larger frame size or higher CRF?

By "lower compression" I mean higher quality mp4, with smaller CRF: while commenting above I was exporting with a CRF of 16, while the default it's a higher number (24 IIRC).

**Comment by itsmattkc** [comment] 2021-05-09 14:45
I've spent some time on this, let me know if the latest commit shows any improvement on this issue.

**Comment by dentex** [comment] 2021-05-09 15:55
> I've spent some time on this, let me know if the latest commit shows any improvement on this issue.

Is it the commit `15556c64` ? I'm trying it now.

**Comment by dentex** [comment] 2021-05-09 16:22
Unfortunately, same behavior as before. I tried to export a 30 sec long sequence of 2.7k 60FPS clips as h.264 with CRF of 16;
RAM usage went up to 12GB out of 16GB and, at about a 40% of progress, Olive crashed.

**Comment by itsmattkc** [comment] 2021-05-10 01:57
@unfa Could you test the latest commit when you get a chance?

@dentex You're both referring to separate issues and I was mainly referring to the OP.

**Comment by unfa** [comment] 2021-05-11 10:11
I've just tested 72d5b4af on a different Manjaro machine and I managed to process 1080p30 footagewithout problems.
I should make sure 4K and 6K works as well on my home studio machine.

**Comment by itsmattkc** [comment] 2021-05-11 15:38
> I'm unsure why you say it's a different issue... Maybe I'm missing something.

The OP appears to be about an issue that appeared after 2e96b57 and occurs regardless of video quality. By your own confirmation, the issue you're referring to still exists in 2e96b57 and is contingent on video quality. They may have similar outcomes, but they are clearly different root causes. I haven't even begun to look at your issue yet.

**Comment by dentex** [comment] 2021-05-11 16:17
@itsmattkc thanks for the clarification.

**Comment by itsmattkc** [comment] 2021-05-13 11:35
I've managed to locate a memory leak introduced about a week ago in ee6b09f7726ea565c586657f91f970b8d5c3b6d4, I've fixed it in the latest commit (with 51b3d974c52b85a87d65c927fcbda2a1b485d695), let me know if this helps @dentex and @unfa

**Comment by unfa** [comment] 2021-05-14 00:44
I'll test soon. Yesterday when I tried loading up 1080p and 4K footage. Olive froze. But today I managed to edit some 1080p footage without issues (albeit on another machine) - it seems higher resolutions expose problems that are not visible at 1080p.
I'll get back when I do some new tests.

**Comment by dentex** [comment] 2021-05-14 08:19
I just tried with the latest nightly `a675e0cc` and the export of my *usual* test sequence was successful (h.264 @18 CRF).
Thanks @itsmattkc for the great job. :heart:

**Comment by itsmattkc** [comment] 2021-05-26 12:41
I believe this has been fixed so I will close it.

**Closed** 2021-05-26 12:40 UTC
Labels: Export, High Priority
