### ISSUE TITLE
[CRASH] Crash on exporting a project

### ISSUE THREAD

**Issue by prokoudine** [olive-editor/olive#1431] opened 2020-11-29 08:43 UTC
**Commit Hash** 

commit 2c83c5835664af8e9cd0cde4cf4f8dcde2de456c

**Platform** 

Ubuntu 20.10

**Summary**

Cut a quick project, export, BOOM

<details><summary><strong>Backtrace</strong></summary>

```
[New Thread 0x7fff5e1d6640 (LWP 591852)]
[libx264 @ 0x7fffa00855c0] profile High, level 5.0, 4:2:0, 8-bit
[libx264 @ 0x7fffa00855c0] 264 - core 160 r3011 cde9a93 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1,00:0,00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23,0 qcomp=0,60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1,40 aq=1:1,00
Output #0, mp4, to '/home/alex/projects/video/librearts/other/2020/font-manager-0-8-0/test-2.mp4':
    Stream #0:0: Video: h264, yuv420p, 2560x1440 [SAR 1:1 DAR 16:9], q=2-31
    Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s
[New Thread 0x7fff5d9d5640 (LWP 591854)]
[New Thread 0x7fff52ad0640 (LWP 591855)]
[New Thread 0x7fff522cf640 (LWP 591856)]
[New Thread 0x7fff51ace640 (LWP 591857)]
[New Thread 0x7fff512cd640 (LWP 591858)]
[New Thread 0x7fff50acc640 (LWP 591859)]
[DEBUG] No arenas, creating new... (olive::MemoryPool<T>::ElementPtr olive::MemoryPool<T>::Get() [with T = unsigned char; olive::MemoryPool<T>::ElementPtr = std::shared_ptr<olive::MemoryPool<unsigned char>::Element>]:336)
[swscaler @ 0x7fffa0299340] Warning: data is not aligned! This can lead to a speed loss
[Thread 0x7fff50acc640 (LWP 591859) exited]
[Thread 0x7fff512cd640 (LWP 591858) exited]
[Thread 0x7fff51ace640 (LWP 591857) exited]
[Thread 0x7fff522cf640 (LWP 591856) exited]
[Thread 0x7fff52ad0640 (LWP 591855) exited]
[Thread 0x7fff5d9d5640 (LWP 591854) exited]
[Thread 0x7fff5e1d6640 (LWP 591852) exited]
[Thread 0x7fff6b672640 (LWP 591851) exited]
[Thread 0x7fff6be73640 (LWP 591850) exited]
[Thread 0x7fff6c674640 (LWP 591849) exited]
[Thread 0x7fff6ce75640 (LWP 591848) exited]
[Thread 0x7fff6d676640 (LWP 591847) exited]
[Thread 0x7fffbb05b640 (LWP 591846) exited]
[Thread 0x7fff7e1ec640 (LWP 591838) exited]
[Thread 0x7fff7e9ed640 (LWP 591837) exited]
[Thread 0x7fff7f1ee640 (LWP 591836) exited]
[Thread 0x7fffb887c640 (LWP 591835) exited]
[Thread 0x7fffba059640 (LWP 591833) exited]
[Thread 0x7fffba85a640 (LWP 591832) exited]
[Thread 0x7fffc5a07640 (LWP 591829) exited]
[Thread 0x7fffc6208640 (LWP 591828) exited]
[Thread 0x7fffc6a09640 (LWP 591827) exited]
[Thread 0x7fffdc943640 (LWP 591826) exited]
[Thread 0x7fffdd6e5640 (LWP 591825) exited]
[Thread 0x7fffddee6640 (LWP 591824) exited]
[Thread 0x7fffde6e7640 (LWP 591823) exited]
[Thread 0x7fffdeee8640 (LWP 591822) exited]
[Thread 0x7fffdf6f5640 (LWP 591820) exited]
[Thread 0x7fffe0110640 (LWP 591819) exited]
[Thread 0x7fffe0d86f80 (LWP 591815) exited]
--Type <RET> for more, q to quit, c to continue without paging--

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
```

**Additional Information**

**Comment by itsmattkc** [comment] 2020-11-29 11:42
I think your report is missing the backtrace (`bt` in gdb), is this bug consistently recreatable?

**Comment by prokoudine** [comment] 2020-11-29 11:48
That's the thing. When I type 'bt', it says 'The program no longer exists.'.

It's 100% reproducible.

**Comment by itsmattkc** [comment] 2020-11-30 20:59
Is this your own build or the AppImage? If your own build, try with the AppImage.

Also if you could attach a project that demonstrates this issue, that might be good too.

**Comment by prokoudine** [comment] 2020-11-30 21:30
It was my own build. Here's the latest AppImage crashing:

```
alex@carbon ~/s/v/olive> ./Olive-7dd9115e-Linux-x86_64.AppImage
[DEBUG] Extracting default OCIO config to "/home/alex/.cache/olivevideoeditor.org/Olive/ocioconf" ((null):0)
[INFO] Using Qt version: 5.12.8 ((null):0)
[DEBUG] Using graphics driver: Intel ((null):0)
[INFO] Setting output audio device to "alsa_output.pci-0000_00_1f.3.analog-stereo" ((null):0)
[INFO] Setting output audio device to "alsa_output.pci-0000_00_1f.3.analog-stereo" ((null):0)
[DEBUG] Set default pix fmt "yuv420p" ((null):0)
[libx264 @ 0x7f70d0852540] using SAR=1/1
[libx264 @ 0x7f70d0852540] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7f70d0852540] profile High, level 5.0, 4:2:0, 8-bit
[libx264 @ 0x7f70d0852540] 264 - core 161 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1,00:0,00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23,0 qcomp=0,60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1,40 aq=1:1,00
Output #0, mp4, to '/home/alex/projects/video/librearts/other/2020/font-manager-0-8-0/test.mp4':
    Stream #0:0: Video: h264, yuv420p, 2560x1440 [SAR 1:1 DAR 16:9], q=2-31
    Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s
[DEBUG] No arenas, creating new... ((null):0)
[swscaler @ 0x7f70c257f280] Warning: data is not aligned! This can lead to a speed loss
[DEBUG] Using graphics driver: Intel ((null):0)
[libx264 @ 0x7f70fc16be40] using SAR=1/1
[libx264 @ 0x7f70fc16be40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7f70fc16be40] profile High, level 5.0, 4:2:0, 8-bit
[libx264 @ 0x7f70fc16be40] 264 - core 161 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1,00:0,00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23,0 qcomp=0,60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1,40 aq=1:1,00
Output #0, mp4, to '/home/alex/projects/video/librearts/other/2020/font-manager-0-8-0/test.tmp0.mp4':
    Stream #0:0: Video: h264, yuv420p, 2560x1440 [SAR 1:1 DAR 16:9], q=2-31
    Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s

(process:637389): GLib-CRITICAL **: 00:23:22.713: g_hash_table_contains: assertion 'hash_table != NULL' failed

(process:637389): GLib-CRITICAL **: 00:23:22.713: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
[637274:637274:20201201,002322.861872:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.861996:ERROR process_reader_linux.cc:520] no module mappings 0x7f714c705000
[637274:637274:20201201,002322.862057:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.862066:ERROR process_reader_linux.cc:520] no module mappings 0x7f714c5ed000
[637274:637274:20201201,002322.864669:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.864700:ERROR process_reader_linux.cc:520] no module mappings 0x7f714c52f000
[637274:637274:20201201,002322.864846:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.864856:ERROR process_reader_linux.cc:520] no module mappings 0x7f714c468000
[637274:637274:20201201,002322.864900:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.864908:ERROR process_reader_linux.cc:520] no module mappings 0x7f714c354000
[637274:637274:20201201,002322.865970:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.865995:ERROR process_reader_linux.cc:520] no module mappings 0x7f714ac33000
[637274:637274:20201201,002322.866046:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.866054:ERROR process_reader_linux.cc:520] no module mappings 0x7f714a90b000
[637274:637274:20201201,002322.866098:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.866106:ERROR process_reader_linux.cc:520] no module mappings 0x7f714a87f000
[637274:637274:20201201,002322.866147:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.866156:ERROR process_reader_linux.cc:520] no module mappings 0x7f714a7ca000
[637274:637274:20201201,002322.878699:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.878727:ERROR process_reader_linux.cc:520] no module mappings 0x7f71490f2000
[637274:637274:20201201,002322.878770:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.878779:ERROR process_reader_linux.cc:520] no module mappings 0x7f7148ed2000
[637274:637274:20201201,002322.878822:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.878834:ERROR process_reader_linux.cc:520] no module mappings 0x7f7148816000
[637274:637274:20201201,002322.879936:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.879957:ERROR process_reader_linux.cc:520] no module mappings 0x7f71470e3000
[637274:637274:20201201,002322.880084:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.880094:ERROR process_reader_linux.cc:520] no module mappings 0x7f7146ba5000
[637274:637274:20201201,002322.880130:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.880137:ERROR process_reader_linux.cc:520] no module mappings 0x7f7146b11000
[637274:637274:20201201,002322.880177:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.880185:ERROR process_reader_linux.cc:520] no module mappings 0x7f7146a97000
[637274:637274:20201201,002322.880315:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.880323:ERROR process_reader_linux.cc:520] no module mappings 0x7f71469fa000
[637274:637274:20201201,002322.880515:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.880525:ERROR process_reader_linux.cc:520] no module mappings 0x7f71468f3000
[637274:637274:20201201,002322.880567:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.880575:ERROR process_reader_linux.cc:520] no module mappings 0x7f7146882000
[637274:637274:20201201,002322.880616:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.880623:ERROR process_reader_linux.cc:520] no module mappings 0x7f7146550000
[637274:637274:20201201,002322.880655:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.880660:ERROR process_reader_linux.cc:520] no module mappings 0x7f7145fdb000
[637274:637274:20201201,002322.880741:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.880746:ERROR process_reader_linux.cc:520] no module mappings 0x7f7145cb8000
[637274:637274:20201201,002322.894162:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.894191:ERROR process_reader_linux.cc:520] no module mappings 0x7f7144d89000
[637274:637274:20201201,002322.894235:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.894243:ERROR process_reader_linux.cc:520] no module mappings 0x7f7144d5a000
[637274:637274:20201201,002322.894282:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.894288:ERROR process_reader_linux.cc:520] no module mappings 0x7f7144d49000
[637274:637274:20201201,002322.894324:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.894331:ERROR process_reader_linux.cc:520] no module mappings 0x7f7144cfe000
[637274:637274:20201201,002322.894366:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.894373:ERROR process_reader_linux.cc:520] no module mappings 0x7f7144cda000
[637274:637274:20201201,002322.894411:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.894419:ERROR process_reader_linux.cc:520] no module mappings 0x7f7144cc5000
[637274:637274:20201201,002322.907505:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.907533:ERROR process_reader_linux.cc:520] no module mappings 0x7f7142381000
[637274:637274:20201201,002322.931071:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.931098:ERROR process_reader_linux.cc:520] no module mappings 0x7f714c525000
[637274:637274:20201201,002322.931131:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.931138:ERROR process_reader_linux.cc:520] no module mappings 0x7f713ea9e000
[637274:637274:20201201,002322.931261:ERROR elf_image_reader.cc:95] out of order load segments
[637274:637274:20201201,002322.931274:ERROR process_reader_linux.cc:520] no module mappings 0x7f713e89f000
[637274:637274:20201201,002322.933309:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.933338:ERROR process_reader_linux.cc:520] no module mappings 0x7f713e91e000
[637274:637274:20201201,002322.933384:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.933392:ERROR process_reader_linux.cc:520] no module mappings 0x7f713c75d000
[637274:637274:20201201,002322.936447:ERROR elf_image_reader.cc:622] no dynamic segment
[637274:637274:20201201,002322.936474:ERROR process_reader_linux.cc:520] no module mappings 0x7f713402c000
[637274:637274:20201201,002322.937764:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.937790:ERROR process_reader_linux.cc:520] no module mappings 0x7f7119823000
[637274:637274:20201201,002322.937926:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.937939:ERROR process_reader_linux.cc:520] no module mappings 0x7f7119815000
[637274:637274:20201201,002322.938753:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.938779:ERROR process_reader_linux.cc:520] no module mappings 0x7f7119809000
[637274:637274:20201201,002322.938922:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.938936:ERROR process_reader_linux.cc:520] no module mappings 0x7f7134008000
[637274:637274:20201201,002322.941168:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.941196:ERROR process_reader_linux.cc:520] no module mappings 0x7f7119582000
[637274:637274:20201201,002322.942686:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.942712:ERROR process_reader_linux.cc:520] no module mappings 0x7f7134022000
[637274:637274:20201201,002322.942981:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.942999:ERROR process_reader_linux.cc:520] no module mappings 0x7f7119578000
[637274:637274:20201201,002322.943187:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.943202:ERROR process_reader_linux.cc:520] no module mappings 0x7f711956c000
[637274:637274:20201201,002322.944910:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.944952:ERROR process_reader_linux.cc:520] no module mappings 0x7f7119563000
[637274:637274:20201201,002322.946040:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.946065:ERROR process_reader_linux.cc:520] no module mappings 0x7f71184da000
[637274:637274:20201201,002322.947908:ERROR elf_image_reader.cc:116] no preferred header address
[637274:637274:20201201,002322.947938:ERROR process_reader_linux.cc:520] no module mappings 0x7f70f84ed000
fish: './Olive-7dd9115e-Linux-x86_64.A…' terminated by signal SIGSEGV (Address boundary error)

```

**Comment by itsmattkc** [comment] 2020-12-01 00:00
I guess I'll have to test on Linux because I can't recreate this

**Comment by itsmattkc** [comment] 2021-03-22 12:48
Does this error still occur on the latest commit?

**Comment by itsmattkc** [comment] 2021-04-08 09:39
Assuming was a duplicate of #1418, closing now

**Closed** 2021-04-08 09:40 UTC
Labels: Crash, Triage

**Comment by jakdutra** [comment] 2022-11-03 07:22
I cannot export as well. No idea what do to :( Can anyone help me please? Thx
