### ISSUE TITLE
[CACHE] Some frames do not get cached

### ISSUE THREAD

**Issue by mcDandy** [olive-editor/olive#1706] opened 2021-08-08 19:10 UTC
**Commit Hash**  bdbeb111

**Platform**  Windows 11

**Summary**
Some frames do not get cached which means about a second of lag trying to cache a frame. Tried deleting cache and caching the entire sequence. Missing frames 32 124 481 483 485 496 500 511 960 1236 or near.

**Additional Information / Output**
[NodeTest.ove.txt](https://github.com/olive-editor/olive/files/6951327/NodeTest.ove.txt)

**Comment by itsmattkc** [comment] 2021-08-08 19:19
You'll need to be much more specific. In what situations does this happen? What are the steps to reproduce?

**Comment by mcDandy** [comment] 2021-08-08 20:10
I was just playing with nodes. It happened first time. I created empty seqence at 60 fps and 1 minute clip. Added shape. It probably started happenning when I combined shape with itself which was 30 frames behind using time remap node and started keyframing position of shape. I noticed it lag at one point. I clicked chace entire seqence which did not help. I continued to keyframe shapes position and decided to add two more copies using another Time remep node (60 frames behind) which after rechacing made everything more laggy (more missing frames). I continued keyframing position of Shape. It is then when I noticed two red slivers on timeline. Each one was few uncached frames divided by at least one chaced frame. 
In report is project where it happened. It does not need any footage becouse I was trying what I can create using only nodes. 

I guess steps to reproduce are (my parameters)
1. Create seqence (1920x1080 @60 fps)
2. add empty clip to it (60 s or 3600 frames)
3. add shape to nodes (white elipse 10x10)
4. add time remap node 
5. connect shape to time remap node
6. keyframe time remap node to be set frame count behind current frame (30 frames)
7. add output from time remap node and shape node together using Math node
8. create another time remap node connected to math node created earlier
9. keyframe time remap node to be set frame count behind current frame (60 frames)
10. add output from time remap node and math node together using Math node
11. connect last math node to clip
12. keyframe shape node to move 


Will do more testing tomorrow (if I do not forget).

**Comment by mcDandy** [comment] 2021-08-08 21:38
Ok so I deleted entire olive chace folder after closing project. Then I reopened it and chaced it. It fixed itself.

**Comment by mcDandy** [comment] 2021-08-09 12:57
It appears to be tied to changing keyframe type or invalidating part of seqence and then caching it using play head (also happened with Cache entire seqence option after delete cache option which resulted on few missing frames). After switching back there is only visual glitch (unchaced half frame - when cache was not deleted) remaining. It appears it has something to do with time remap node and/or 60 fps sequence.

**Comment by mcDandy** [comment] 2021-08-09 13:54
Final steps to reproduce:

1. create 60fps sequence
2. add empty clip with some lenght (few seconds)
3. add shape using node editor and keyframe position
4. add time remap node connected from shape
5. keyframe time remap node so it is not on one frame (i keyframed it so time remap node frame is <number of frames>-<current frame>)
6. add math between shape and clip
7. connect time remap node to math node

![obrazek](https://user-images.githubusercontent.com/18588943/128717480-254169ae-83cc-4e2d-ab28-5ecaaff235c8.png)

**Comment by itsmattkc** [comment] 2021-09-22 02:34
Let me know if this is fixed in 677277c16d51bcd9aa6073fc71fa8fe4bdbc720e

**Comment by mcDandy** [comment] 2021-09-30 19:33
For some frames it is reqired to move player head over the frame to cache the frame (does not work all the time). I cannot test it much, becouse clicking play does nothing, but ONLY on this project. Gouing to recreate setup (this project is source of some crashes)

**Comment by itsmattkc** [comment] 2022-01-10 09:49
I'm going to close this for now since I'm under the impression this doesn't really happen anymore. There may be the occasional issue where you have to move the playhead over to a region to cache them (especially if scrubbing a lot mid auto-cache, which I guess could be considered a "UI papercut"), but as long as the frames don't stay stuck uncached, I don't consider it a major bug.

**Closed by itsmattkc** 2022-01-10 09:49 UTC
Labels: Inadequate Information, Disk Cache, Triage
