### ISSUE TITLE
[Website] Download for Windows v0.2 Version "broken".

### ISSUE THREAD

**Issue by Avispa** [olive-editor/olive#1300] opened 2020-11-02 01:11 UTC
Download "link" on https://www.olivevideoeditor.org/download.php for the *"Olive 0.2 Nightly Builds"* for Windows is buggy/broken.

### Actually Behaviour
* The Windows 7+ box in the *Nightly Builds* section disappears [sic!]
*  Download links appear next to the Windows 7 button in the "Olive 0.1 unsupported" section next to the Windows 7+ appears.
* These links also just point (*kinda* correctly) to the old v0.1 from April 2019.

### Expected Behaviour
* Window 7+ box does not disappear.
* Correct links to the v0.2 version pop up next to the Windows box similiar to the behaviour for the box for the v0.1.

### Work Arround
Click on *"See More Nightly Builds"* and pick the desired version. However, pretty confusing, especially when your brain is on autopilot.

**Comment by elsandosgrande** [comment] 2020-11-02 03:01
I can confirm this on both Firefox Nightly and Microsoft Edge Dev.

**Comment by Simran-B** [comment] 2020-11-02 10:44
The buttons use the same IDs, which is invalid HTML:
![image](https://user-images.githubusercontent.com/7819991/97856662-e2f55f80-1cfc-11eb-8e85-de069e7b36a7.png)

The actual problem is caused by this jQuery code:

```js
$(".dlb-big").click(function(){
	$(".dlb-big").show();
	$(".dlb-sub").hide();

	$("#" + this.id + "sub").show(); // uses ambiguous id, in which case browsers seems to choose the first element

	$(this).hide();
});
```

This should be corrected to:

```html
<div class="dlb-container dlb-big">
	<div class="dl-button vpadding">
		<img src="img/win.png">
		<br>
		<br>
		<b>Windows</b>
		<br>
		Windows 7+
	</div>
</div>
<div class="dlb-container dlb-sub" style="display: none;">
	<div class="dl-button dlb-link" data-type="w64i" data-hash="latest">
		Installer (64-bit)
	</div>
	<br>
	<div class="dl-button dlb-link" data-type="w64p" data-hash="latest">
		Portable (64-bit)
	</div>
</div>
...
(also change id and hash attribute to data-* for Linux and macOS)
```

```js
<script type="text/javascript">
	$(document).ready(function(){
		$(".dlb-big").click(function(){
			$(".dlb-big").show();
			$(".dlb-sub").hide();
			$(this).next(".dlb-sub").show();
			$(this).hide();
		});

		$(".dlb-link").click(function(){
			window.location.href = 'go.php?hash=' + $(this).attr("data-hash") + '&type=' + $(this).attr("data-type");
		});
	});
</script>
```

**Comment by itsmattkc** [comment] 2020-11-03 08:53
Thanks for reporting this, fixed now using @Simran-B's suggestions

**Closed by itsmattkc** 2020-11-03 08:53 UTC
Labels: User Interface
