### ISSUE TITLE
Sequence Viewer black on newest Git 

### ISSUE THREAD

**Issue by alcomposer** [olive-editor/olive#555] opened 2019-02-26 08:09 UTC
Olive version: 3233c0d Feb 2019  
Source: GIT  
Operating system: Arch Linux  
CPU: i7-8550U
GPU: GeForce MX150 NVIDIA 418.43 (Nvidia Prime with Intel UHD 620)
Driver: nvidia v: 418.43 

Sequence viewer is blank (black) but media viewer shows media ok.

**Comment by Symbian9** [comment] 2019-02-26 13:13
Try launch *Olive* with option

```
$ olive --disable-blend-modes
```

**Comment by oc1024** [comment] 2019-02-26 13:46
Or `LIBGL_ALWAYS_SOFTWARE=1 ./olive-editor`

**Comment by Symbian9** [comment] 2019-02-26 14:10
> Or `LIBGL_ALWAYS_SOFTWARE=1 ./olive-editor`

This variable not show is black screen in sequence viewer broken by added GLSL effect or not.

@alcomposer, could you add screenshots and details about project file: is there any effects?

**Comment by alcomposer** [comment] 2019-02-26 19:59
The media viewer plays back, but flickers, however the sequence viewer is completely blank (a black windows) where the media normally is.

I have narrowed it down to Nvidia (I am testing on Linux so maybe only Linux?).  When I tested with Intel iGPU there was no problem playing back footage.

Neither the argument or the environment variable worked with the Nvidia GPU.

**Comment by bradleypariah** [comment] 2019-02-26 21:36
I'm experiencing this as well.  I have tried with both MOV files and MP4 files.  The Media Viewer works to preview files, but when playing in the timeline, nothing shows in the Sequence Window.  It's just black.  The issues started with the most recent update from the repo.

https://drive.google.com/open?id=1g4Q-IcZu-TU1-nbdbw0RpLB3AHzMGlCT

**Comment by alcomposer** [comment] 2019-02-27 07:49
@bradleypariah is you Nvidia card an Optimus or pci-e GPU?

**Comment by itsmattkc** [comment] 2019-02-27 19:46
Any improvement with d3487086c79a5640b6b8a539bcf1427b0c5e5b69?

**Comment by bradleypariah** [comment] 2019-02-27 21:58
> @bradleypariah is you Nvidia card an Optimus or pci-e GPU?

It's a 4GB gtx960.  It's a PCI desktop GPU, I believe.  Looks like a normal traditional PCIe x16 card.

neofetch
            .-/+oossssoo+/-.               bradley@UbuntuStudio 
        `:+ssssssssssssssssss+:`           -------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 18.04.2 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Kernel: 4.15.0-45-lowlatency 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Uptime: 5 hours, 52 mins 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Packages: 3119 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Shell: bash 4.4.19 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Resolution: 1920x1080 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   DE: Xfce 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Xfwm4 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM Theme: BubbleTux 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Adwaita-dark [GTK2] 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: Humanity-Dark [GTK2] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: xfce4-terminal 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal Font: Ubuntu Mono 11 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i5-6600K (4) @ 3.900GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA GeForce GTX 960 
      -+sssssssssssssssssyyyssss+-         Memory: 3451MiB / 32102MiB 
        `:+ssssssssssssssssss+:` 
            .-/+oossssoo+/-.

**Comment by alcomposer** [comment] 2019-02-28 03:41
> Any improvement with [d348708](https://github.com/olive-editor/olive/commit/d3487086c79a5640b6b8a539bcf1427b0c5e5b69)?

No, and now both viewers are blank:
![blank screen](https://user-images.githubusercontent.com/12004932/53539690-7bb7fd00-3b62-11e9-9375-992496bb991d.png)


Debug output from terminal: 2019-02-28T14:07:30 [WARNING] Invalid values passed to get_buffer_offset_from_frame 124 < 125

Looks like this issue is across all Nvidia GPU's on Linux (I have only tested Linux).

**Comment by psemiletov** [comment] 2019-02-28 14:44
My Radeon don't show video at the Sequence viewer. Some days ago all was fine, but after one commit things goes weird :)

**Comment by alcomposer** [comment] 2019-02-28 16:25
@psemiletov what is your OS, and GPU?

This is the first report if this issue occuring on an AMD card.

**Comment by elsandosgrande** [comment] 2019-02-28 23:05
__Olive version:__ 6c166a1 (Olive repository, AppImage), 26b4abe (personal Olive fork, manually/locally built)
__Operating system:__ *(Antergos with KDE, latest updates, testing repositories)*  
__CPU:__ *AMD Dual-Core A9-9410*  
__GPU:__ *AMD Radeon R7 M440 (dedicated), AMD Stoney (integrated)*
[Full laptop specifications sheet](https://github.com/olive-editor/olive/files/2917267/c05342156.pdf)

I, personally, am seeing issues with neither the timeline nor the media previews.
It is most likely not worth mentioning, but I am running it on Wayland.

**Comment by AGI-THB** [comment] 2019-02-28 23:14
I had the problem only when i used Olive in **virtualbox** (Linux MInt 19).
CPU: intel i5-4200u
GPU: iGPU

Godot-engine also refuses to start because of **OpenGL** problems.

Its fine outside the virtualbox.

**Comment by DaniSeeh** [comment] 2019-03-01 08:32
Wanted to throw in my two cents that I am having this problem on 48497dd on this machine:

AMD Ryzen 1700x
GTX 1070
32 GB of Ram
Manjaro Cinnamon

Except for me, both media and sequence viewer display constant black. Everything was working on 83ad41d (with some other minor display issues but at least working).

**Comment by psemiletov** [comment] 2019-03-01 12:55
> @psemiletov what is your OS, and GPU?
> This is the first report if this issue occuring on an AMD card.

Mageia 6, XOrg radeon driver, Radeon HD 6870. MATE desktop.

**Comment by Symbian9** [comment] 2019-03-01 13:22
FTR, I has NO such issue on my PC, but I launch *Olive* as:

```
$ olive --disable-blend-modes
```

Olive version: `48497dd` (AppImage)

OS: Debian 9.x (x86_64)

GPU: ATI Radeon Xpress 1250

Driver: Gallium 0.4 on ATI RS600 - X.Org R300 Project

OpenGL version: 2.1 Mesa 13.0.6 (GLSL 1.20)

**Comment by elsandosgrande** [comment] 2019-03-01 13:22
@psemiletov Could you try running AMDGPU? I am using AMDGPU and see no issues.

After discussing this issue for a little bit with @alcomposer on Discord, I think it would be beneficial to mention that I have [Early KMS](https://wiki.archlinux.org/index.php/Kernel_mode_setting#Early_KMS_start) set up (I had 6-bit color instead of 8-bit after an update and setting this actually fixed it, though I was setting it up without my color issue in mind, so it was pure chance that it fixed the issue) and that this issue does not come up in Xorg either (at least when using XRender as the backend in KWin, as OpenGL gives me glitches galore in Xorg).

**Comment by psemiletov** [comment] 2019-03-01 17:34
> @psemiletov Could you try running AMDGPU? I am using AMDGPU and see no issues.

AMDGPU does not support my videocard.
What was changed at video output code? Week ago I had video output in both panels.

**Comment by psemiletov** [comment] 2019-03-01 17:44
My Sequence viewer, with the new project and one empty sequence, shows the random pieces of video memory (for example, from the "screenshot" of the file open dialog that was called before).

**Comment by elsandosgrande** [comment] 2019-03-01 18:08
I get those framebuffer glitches too (not in Olive though and less and less with each and every KDE update). You're running `xf86-video-ati` with mesa installed as well if I am not mistaken. 

Hmm, I wonder if it's just Nvidia's proprietary driver and the ATI driver having issues/if it's just nouveau and AMDGPU that are fine?

**Comment by NathanSalapat** [comment] 2019-03-02 14:25
I'm having the same problem.

OS Linux Mint 19.1
Nvidia driver 390.77, GTX 1060

launched with --disable-blend-mode

I get some errors in the terminal, maybe this can shed some light on the issue.
````
2019-03-02T08:22:24 [WARNING] libpng warning: iCCP: known incorrect sRGB profile
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f2ee4005240] unsupported color_parameter_type aclc
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/nathan/Downloads/GOPR8751.MP4':
  Metadata:
    major_brand     : avc1
    minor_version   : 0
    compatible_brands: avc1isom
    creation_time   : 2014-01-01T01:47:26.000000Z
    firmware        : HD3.20.01.07
  Duration: 00:00:17.03, start: 0.000000, bitrate: 15445 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuvj420p(pc), 1280x720 [SAR 1:1 DAR 16:9], 15042 kb/s, 59.94 fps, 59.94 tbr, 60k tbn, 119.88 tbc (default)
    Metadata:
      creation_time   : 2014-01-01T01:47:26.000000Z
      handler_name    :  Ambarella AVC
      encoder         : Ambarella AVC encoder
      timecode        : 01:47:19:33
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2014-01-01T01:47:26.000000Z
      handler_name    :  Ambarella AAC
      timecode        : 01:47:19:33
    Stream #0:2(eng): Data: none (tmcd / 0x64636D74), 0 kb/s (default)
    Metadata:
      creation_time   : 2014-01-01T01:47:26.000000Z
      timecode        : 01:47:19:33
2019-03-02T08:22:36 [ERROR] Unsupported codec in stream 2 of file "GOPR8751.MP4"
2019-03-02T08:22:36 [WARNING] QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)

[swscaler @ 0x7f2e780709a0] deprecated pixel format used, make sure you did set range correctly
2019-03-02T08:22:46 [INFO] Clip opened on track -1 (took 11 ms)
Input #0, image2, from '/home/nathan/Downloads/Minetest-channel-art.jpg':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 250476 kb/s
    Stream #0:0: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 2560x1440 [SAR 28:28 DAR 16:9], 25 tbr, 25 tbn, 25 tbc

```

**Comment by naj59** [comment] 2019-03-02 16:09
Looks like a GoPro mp4. Error relies in codec. Probably hevc?

**Comment by NathanSalapat** [comment] 2019-03-02 16:23
@naj59 It makes no difference what video I use. The second example is a .jpg and that doesn't work either.
I have some projects that used to work just fine, and now display no output.

**Comment by naj59** [comment] 2019-03-02 16:26
@NathanSalapat I understandbut at this time, the error message is
``[ERROR] Unsupported codec in stream 2 of file "GOPR8751.MP4"``. But when you say that they worked before something must have been changed that this is broken. I am on Windows so I cannot really talk about.

**Comment by NathanSalapat** [comment] 2019-03-02 16:27
Here's the error ouput from a clip that worked before.
```2019-03-02T10:25:51 [WARNING] libpng warning: iCCP: known incorrect sRGB profile
Input #0, matroska,webm, from '/home/nathan/Videos/CitySim.mkv':
  Metadata:
    ENCODER         : Lavf56.40.101
  Duration: 00:18:08.77, start: 0.000000, bitrate: 7783 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 1k tbn, 60 tbc (default)
    Metadata:
      DURATION        : 00:18:08.766000000
    Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      title           : Microphone
      DURATION        : 00:18:08.644000000
    Stream #0:2: Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      title           : Desktop
      DURATION        : 00:18:08.644000000
2019-03-02T10:26:04 [WARNING] QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
[swscaler @ 0x7fe8b9022a80] Warning: data is not aligned! This can lead to a speed loss
Input #0, matroska,webm, from '/home/nathan/Videos/CitySim.mkv':
  Metadata:
    ENCODER         : Lavf56.40.101
  Duration: 00:18:08.77, start: 0.000000, bitrate: 7783 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 1k tbn, 60 tbc (default)
    Metadata:
      DURATION        : 00:18:08.766000000
    Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      title           : Microphone
      DURATION        : 00:18:08.644000000
    Stream #0:2: Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      title           : Desktop
      DURATION        : 00:18:08.644000000
Input #0, matroska,webm, from '/home/nathan/Videos/CitySim.mkv':
  Metadata:
    ENCODER         : Lavf56.40.101
  Duration: 00:18:08.77, start: 0.000000, bitrate: 7783 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 1k tbn, 60 tbc (default)
    Metadata:
      DURATION        : 00:18:08.766000000
    Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      title           : Microphone
      DURATION        : 00:18:08.644000000
    Stream #0:2: Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      title           : Desktop
      DURATION        : 00:18:08.644000000
2019-03-02T10:26:11 [INFO] Clip opened on track 1 (took 17 ms)
2019-03-02T10:26:11 [INFO] Clip opened on track 0 (took 18 ms)
Input #0, matroska,webm, from '/home/nathan/Videos/CitySim.mkv':
  Metadata:
    ENCODER         : Lavf56.40.101
  Duration: 00:18:08.77, start: 0.000000, bitrate: 7783 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 1k tbn, 60 tbc (default)
    Metadata:
      DURATION        : 00:18:08.766000000
    Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      title           : Microphone
      DURATION        : 00:18:08.644000000
    Stream #0:2: Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      title           : Desktop
      DURATION        : 00:18:08.644000000
2019-03-02T10:26:11 [INFO] Clip opened on track -1 (took 13 ms)
[matroska,webm @ 0x7fe8ac004380] Invalid EBML number size tag 0x01 at pos 924 (0x39c)
[matroska,webm @ 0x7fe8a40051e0] Invalid EBML number size tag 0x01 at pos 924 (0x39c)
```

**Comment by naj59** [comment] 2019-03-02 16:30
Strange. Also a „format“ error. Tried this file in other software?

**Comment by NathanSalapat** [comment] 2019-03-02 17:30
Yes, the file worked fine. I did an edit with it before in Olive. Plays fine with VLC.

**Comment by itsmattkc** [comment] 2019-03-02 19:46
2b406d71f28f51e56eb69396c6c790e08ca7b384 fixes this for me

**Comment by DaniSeeh** [comment] 2019-03-02 21:05
Good for me now!

**Comment by AGI-THB** [comment] 2019-03-02 22:04
It works now. @itsmattkc

**Comment by NathanSalapat** [comment] 2019-03-02 22:36
Works now, Thanks.

**Comment by itsmattkc** [comment] 2019-03-03 02:19
Confirmed with @alcomposer, the issue is gone. I'll close this now, thanks everyone for chiming in

**Closed by itsmattkc** 2019-03-03 02:19 UTC

**Comment by capabomba** [comment] 2019-06-02 17:37
Sorry guys if I bring this up again, but I'm trying Olive for the first time and on my laptop with Windows 7 32 bit I still have this issue. No matter what file I add in the media library, it won't show in the viewer. It only plays sound. I also tried it on a desktop with same OS and nothing has changed.

I'm running it on a old Compaq Presario CQ61-207SL
CPU Pentium Dual-core T4200 2GHz
GPU Mobile Intel 4 series express chipset
RAM 3 GB DDR2

**Comment by iopenet** [comment] 2025-02-04 15:46
Same issue with Olive-8ac191ce-Windows-x86_64
when importing mp4.

1. Reset custom cache/settings
2. Close Olive
3. Launch Olive
4. Import mp4  

All good !
