### ISSUE TITLE
[BUILD] Cannot build on Arch

### ISSUE THREAD

**Issue by gnolooo** [olive-editor/olive#2341] opened 2024-07-24 15:53 UTC
**Commit Hash** 
f7e1bff

**Platform** 
Arch Linux
Gnome w/ Wayland

**Summary**
Build stops with the following informations.

<details>
<summary><b>Build output</b></summary>

```
gnolooo@lenovo ~ >>> git clone --recursive https://github.com/olive-editor/olive
Clone in 'olive' in corso...
remote: Enumerating objects: 82846, done.
remote: Counting objects: 100% (7609/7609), done.
remote: Compressing objects: 100% (329/329), done.
remote: Total 82846 (delta 7359), reused 7287 (delta 7279), pack-reused 75237
Ricezione degli oggetti: 100% (82846/82846), 29.93 MiB | 26.91 MiB/s, fatto.
Risoluzione dei delta: 100% (64513/64513), fatto.
Sottomodulo 'ext/KDDockWidgets' (https://github.com/olive-editor/KDDockWidgets.git) registrato per il percorso 'ext/KDDockWidgets'
Sottomodulo 'ext/core' (https://github.com/olive-editor/core) registrato per il percorso 'ext/core'
Clone in '/home/gnolooo/olive/ext/KDDockWidgets' in corso...
remote: Enumerating objects: 42840, done.        
remote: Total 42840 (delta 0), reused 0 (delta 0), pack-reused 42840        
Ricezione degli oggetti: 100% (42840/42840), 22.56 MiB | 27.37 MiB/s, fatto.
Risoluzione dei delta: 100% (34986/34986), fatto.
Clone in '/home/gnolooo/olive/ext/core' in corso...
remote: Enumerating objects: 174, done.        
remote: Counting objects: 100% (174/174), done.        
remote: Compressing objects: 100% (96/96), done.        
remote: Total 174 (delta 79), reused 153 (delta 59), pack-reused 0        
Ricezione degli oggetti: 100% (174/174), 102.07 KiB | 2.55 MiB/s, fatto.
Risoluzione dei delta: 100% (79/79), fatto.
Submodule path 'ext/KDDockWidgets': checked out '8d2d0a5764f8393cc148a2296d511276a8ffe559'
Submodule path 'ext/core': checked out '277792824801495e868580ca86f6e7a1b53e4779'
gnolooo@lenovo ~ >>> cd olive
gnolooo@lenovo ~/olive >>> mkdir build
gnolooo@lenovo ~/olive >>> cd build
gnolooo@lenovo ~/olive/build >>> cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo
-- The CXX compiler identification is GNU 14.1.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/ccache/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: /usr/lib/libOpenGL.so
-- Found OpenColorIO: /usr/lib/libOpenColorIO.so (found suitable version "2.3.2", minimum required is "2.1.1")
-- Found OpenImageIO: /usr/lib/libOpenImageIO.so;/usr/lib/libOpenImageIO_Util.so (found suitable version "2.5.13", minimum required is "2.1.12")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found ZLIB: /usr/lib/libz.so (found version "1.3.1")
-- Found CONFIG for OpenEXR 3 (OPENEXR_VERSION=3.2.0)
-- Found FFMPEG: /usr/include (found suitable version "7.0.1", minimum required is "3.0") found components: avutil avcodec avformat avfilter swscale swresample
-- Found PortAudio: /usr/lib/libportaudio.so
-- Looking for C++ include pa_jack.h
-- Looking for C++ include pa_jack.h - found
-- Found OpenTimelineIO: /usr/local/lib/libopentimelineio.so;/usr/local/lib/libopentime.so
-- Could NOT find GoogleCrashpad (missing: CRASHPAD_CLIENT_LIB CRASHPAD_COMMON_LIB CRASHPAD_UTIL_LIB CRASHPAD_BASE_LIB BREAKPAD_BIN_DIR CRASHPAD_BUILD_INCLUDE_DIR CRASHPAD_CLIENT_INCLUDE_DIR CRASHPAD_BASE_INCLUDE_DIR CRASHPAD_COMPAT_LIB) 
   Automatic crash reporting will be disabled.
-- Found Git: /usr/bin/git (found version "2.45.2")
-- Found FFMPEG: /usr/include (found suitable version "7.0.1", minimum required is "3.0") found components: avutil
-- Found OpenTimelineIO: /usr/local/lib/libopentimelineio.so;/usr/local/lib/libopentime.so;/usr/local/lib/libopentimelineio.so;/usr/local/lib/libopentime.so
-- The following OPTIONAL packages have been found:

 * Git
 * OpenTimelineIO
 * Qt5X11Extras

-- The following REQUIRED packages have been found:

 * OpenColorIO (required version >= 2.1.1)
 * OpenImageIO (required version >= 2.1.12)
 * Threads
 * OpenEXR
 * QT
 * Qt5Core
 * Qt5Gui
 * Qt5OpenGL
 * Qt5LinguistTools
 * Qt5Concurrent
 * Qt5DBus
 * Qt5Network
 * PortAudio
 * FFMPEG (required version >= 3.0)
 * Imath
 * OpenGL
 * Qt5Widgets
 * Qt5Test
 * Qt5 (required version >= 5.15)

-- The following OPTIONAL packages have not been found:

 * GoogleCrashpad

-- Configuring done (0.8s)
-- Generating done (0.3s)
-- Build files have been written to: /home/gnolooo/olive/build
gnolooo@lenovo ~/olive/build >>> cmake --build .
[  0%] Built target olive-version-obj_autogen_timestamp_deps
[  1%] Automatic MOC and UIC for target olive-version-obj
[  1%] Built target olive-version-obj_autogen
[  1%] Building CXX object app/CMakeFiles/olive-version-obj.dir/olive-version-obj_autogen/mocs_compilation.cpp.o
[  1%] Building CXX object app/CMakeFiles/olive-version-obj.dir/version.cpp.o
[  1%] Built target olive-version-obj
[  1%] Built target kddockwidgets_autogen_timestamp_deps
[  1%] Automatic MOC and UIC for target kddockwidgets
[  1%] Built target kddockwidgets_autogen
[  1%] Automatic RCC for kddockwidgets_resources.qrc
[  1%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/kddockwidgets_autogen/mocs_compilation.cpp.o
[  1%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/Config.cpp.o
[  2%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/FocusScope.cpp.o
[  2%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/FrameworkWidgetFactory.cpp.o
[  2%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/DockWidgetBase.cpp.o
[  2%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/MainWindowBase.cpp.o
[  2%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/MainWindowMDI.cpp.o
[  3%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/MDIArea.cpp.o
[  3%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/LayoutSaver.cpp.o
[  3%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/LayoutWidget.cpp.o
[  3%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/MDILayoutWidget.cpp.o
[  3%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/MultiSplitter.cpp.o
[  4%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/Position.cpp.o
[  4%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/DropIndicatorOverlayInterface.cpp.o
[  4%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/DropArea.cpp.o
[  4%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/FloatingWindow.cpp.o
[  5%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/Logging.cpp.o
[  5%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/TabWidget.cpp.o
[  5%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/TitleBar.cpp.o
[  5%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/SideBar.cpp.o
[  5%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/DockRegistry.cpp.o
[  6%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/Draggable.cpp.o
[  6%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/WindowBeingDragged.cpp.o
[  6%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/DragController.cpp.o
[  6%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/Frame.cpp.o
[  6%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/DropAreaWithCentralFrame.cpp.o
[  7%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/WidgetResizeHandler.cpp.o
[  7%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/indicators/NullIndicators.cpp.o
[  7%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/indicators/ClassicIndicators.cpp.o
[  7%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/indicators/ClassicIndicatorsWindow.cpp.o
[  7%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/multisplitter/Item.cpp.o
[  8%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/multisplitter/ItemFreeContainer.cpp.o
[  8%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/multisplitter/Logging.cpp.o
[  8%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/multisplitter/MultiSplitterConfig.cpp.o
[  8%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/multisplitter/Separator.cpp.o
[  9%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/multisplitter/Widget.cpp.o
[  9%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/DebugWindow.cpp.o
[  9%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/ObjectViewer.cpp.o
[  9%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/MainWindow.cpp.o
[  9%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/multisplitter/Widget_qwidget.cpp.o
[ 10%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/multisplitter/Separator_qwidget.cpp.o
[ 10%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/widgets/TabBarWidget.cpp.o
[ 10%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/widgets/FloatingWindowWidget.cpp.o
[ 10%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/widgets/FrameWidget.cpp.o
[ 10%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/widgets/SideBarWidget.cpp.o
[ 11%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/widgets/TabWidgetWidget.cpp.o
[ 11%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/widgets/TitleBarWidget.cpp.o
[ 11%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/widgets/DockWidget.cpp.o
[ 11%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/widgets/QWidgetAdapter_widgets.cpp.o
[ 11%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/private/indicators/SegmentedIndicators.cpp.o
[ 12%] Building CXX object ext/KDDockWidgets/src/CMakeFiles/kddockwidgets.dir/kddockwidgets_autogen/EWIEGA46WW/qrc_kddockwidgets_resources.cpp.o
[ 12%] Linking CXX static library libkddockwidgets.a
[ 12%] Built target kddockwidgets
[ 12%] Built target olivecore_autogen_timestamp_deps
[ 13%] Automatic MOC and UIC for target olivecore
[ 13%] Built target olivecore_autogen
[ 13%] Building CXX object ext/core/CMakeFiles/olivecore.dir/olivecore_autogen/mocs_compilation.cpp.o
[ 13%] Building CXX object ext/core/CMakeFiles/olivecore.dir/src/render/audioparams.cpp.o
/home/gnolooo/olive/ext/core/src/render/audioparams.cpp: In member function ‘void olive::core::AudioParams::calculate_channel_count()’:
/home/gnolooo/olive/ext/core/src/render/audioparams.cpp:162:20: error: ‘av_get_channel_layout_nb_channels’ was not declared in this scope
  162 |   channel_count_ = av_get_channel_layout_nb_channels(channel_layout());
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [ext/core/CMakeFiles/olivecore.dir/build.make:97: ext/core/CMakeFiles/olivecore.dir/src/render/audioparams.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3623: ext/core/CMakeFiles/olivecore.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
</details>

**Comment by Simran-B** [comment] 2024-07-25 05:20
Duplicate of #2325. You need to use FFmpeg 6 or older.

**Closed by Simran-B** 2024-07-25 05:20 UTC
Labels: Building/Packaging, Triage
