### ISSUE TITLE
[CACHE] Not dirtying cache when deleting a solid

### ISSUE THREAD

**Issue by eliemichel** [olive-editor/olive#1290] opened 2020-10-29 08:25 UTC
**Commit Hash**
379a799a

**Platform**
Windows 10

**Summary**
When deleting a solid clip, it remains in the playback and the cache does not switch to red even temporarily.

**Additional Information / Output**
Steps to reproduce:

1. Create a sequence with a background video clip.
2. On another video channel, add a solid clip on top of the video.
3. Put the playback cursor over this solid so that it get cached, the caching hint should turn green entierly.
4. Remove the clip.
5. The caching hint remains green at any time and the playback still shows the solid even though it's been deleted.

PS: I did not find a way to crop a clip with alpha 0.2. Is this part of the unwanted feature requests or does it falls in the basic usability concerns and should hence be in the targeted MVP?

**Comment by Simran-B** [comment] 2020-10-29 09:40
Cropping a clip is kind of possible, but not really usable in 0.2 as of yet. You can feed a video input and a polygon node into a math node set to multiply. But the polygon starts out with 5 points and you can only add more (crop would require 4, although you could line up the 5th so that it's a rectangle anyway). And there's a problem on reload with the not fully implemented polygon node: #1285

**Comment by itsmattkc** [comment] 2020-10-29 10:51
This cache issue sounds like it might be a duplicate of #1228?

**Comment by eliemichel** [comment] 2020-10-29 11:20
@itsmattkc Might be, technically, but I did not experience the issue when moving video sequences.

@Simran-B Ah indeed I had tried something like that but did not realize the math multiplication was also affecting the alpha channel, thx.

**Comment by itsmattkc** [comment] 2020-11-17 14:02
Does the latest commit fix this?

**Comment by eliemichel** [comment] 2020-11-17 18:28
Nope: (my background video clip isn't solid red, screenshot took right after a solid at the cursor location had been deleted using the Delete key)
![image](https://user-images.githubusercontent.com/5802849/99431289-ce26e780-290a-11eb-9f69-d6faecdd630e.png)

I note that the cache no longer fill instantly when adding a solid, it seems to get rendered for each frame individually even though they are all the same (but early optimization is bad optimization, let's make this issue solved first I'd say :) ).

**Closed** 2020-11-18 01:56 UTC
Labels: Disk Cache, Triage
