### ISSUE TITLE
[CRASH] Probably because disk C: (cache) ran full

### ISSUE THREAD

**Issue by Avispa** [olive-editor/olive#1648] opened 2021-05-29 02:57 UTC
**Build:** ab31df36
**Platform**:  Windows 7 (64 Bit)

#### Summary
First assumed it is related to the scaling function but since I got no crash report I've realised drive C: had no space left and AppData/olivevideoeditor.org consumed 6 GB++.

#### Steps to Reproduce

1. Let drive C: run full.
2. Start _Olive_.
3. Load file.
4. Do some action -- for exampel transform video via scaling.

#### Expectation
1. Check for full disk so _Olive_ doesn't crash.
2. Clear cache from unused files -- in case it doesn't do already.

**Comment by itsmattkc** [comment] 2021-05-29 03:57
Presumably a duplicate of #1614

**Closed by itsmattkc** 2021-05-29 03:57 UTC
Labels: Crash, Triage
