### ISSUE TITLE
[FEATURE] [AUDIO] Optional audio limiter to prevent clipping

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#2064] opened 2022-10-14 11:59 UTC
I really miss a master limiter effect that'd allow to export videos without clipping in case something gets too loud.

I often open audio from exported videos in Audacity, control the levels, apply limiting and mux the result with my original exported video stream using ffmpeg. This is obviously not trivial and most people don't do it

Here's a video where I explain the process: https://youtu.be/s-odn1RszZg?t=537

Having an (optional) limiter in Olive would provide a fool-proof way to ensure the exported audio is free from clipping, and also give users peace of mind when turning things up.

I would recommend reusing an excellent GPL-licensed limiter called x42-DPL: https://x42-plugins.com/x42/x42-limiter

I've tested it thoroughly and it's the cleanest in existence. I'd make the true-peak mode default as it's even more precise. Otherwise even just default settings and having it as "on/off" option to make sure things don't get above -1 dBFS (that's a common recommendation for lossy audio encoding) would be amazing.

You can watch my video about this plug-in and read more details from the author here:
https://discord.com/channels/549629829730009089/552011038137122826/1030447926356488263

It manages to cleanly limit audio levels without distorting even in the most extreme conditions, where all other tested FOSS limiters would start distorting in one way or another. It's the perfect "transparent" limiter that I use all the time.

A bonus master gain control in Olive would be awesome, as users could tweak the master level at export (should play in the export preview) to make sure their video is not too squashed but not too quiet.

Note that this is not a form of loudness normalisation - it's just a safeguard against audio clipping.

Probably the best way to implement this would be to extend the audio meter into a simple "mixer strip":

1. Add a "gain" knob for master volume control (+/- 24 dB should be plenty)
2. Add a limiter toggle and optionally a release time knob
This way users can control the levels of their audio while editing and make sure it sounds good and not have to leave it for the export phase.

Here's a mockup:

![image](https://user-images.githubusercontent.com/491704/195844576-baaaf27c-02fc-43b6-9e78-4668acbf69fd.png)

**Comment by itsmattkc** [comment] 2022-10-16 06:40
While this is not necessarily a duplicate of #1342, I think it falls into the same category of discussion

**Closed by itsmattkc** 2022-10-16 06:40 UTC
Labels: Export, Triage
