### ISSUE TITLE
[CRASH] Deleting footage in a video track with no merge node linked causes assertion error

### ISSUE THREAD

**Issue by ZoomTen** [olive-editor/olive#1397] opened 2020-11-22 10:13 UTC
**Commit Hash** 

992802704

**Platform** 

Manjaro Linux 20.1.2, manual build

**Summary**

When a merge node is unlinked from a track node (e.g. by deletion of the Merge node), and then a footage is deleted from the affected track, it causes an assertion error.

**Steps to Reproduce**

1. Populate the timeline with several tracks each containing one footage.
2. Show all nodes by right clicking on the node editor -> Filter -> Show All
3. Unlink a track from its merge node by deleting the connection.
4. Remove the footage in the corresponding track in the timeline.
5. Crash, obtain backtrace.

<details><summary><strong>Backtrace</strong></summary><pre><code>
[FATAL] ASSERT: "!graph_update_queue_.isEmpty()" in file /home/zumid/desktop/Apps/Olive Git/app/render/previewautocacher.cpp, line 78 ((null):78)

Thread 1 "olive-editor" received signal SIGABRT, Aborted.
0x00007ffff2e04615 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff2e04615 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff2ded862 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff335f9ac in  () at /usr/lib/libQt5Core.so.5
#3  0x00007ffff335ed59 in qt_assert_x(char const*, char const*, char const*, int) () at /usr/lib/libQt5Core.so.5
#4  0x0000555555991833 in olive::PreviewAutoCacher::NodeGraphChanged(olive::NodeInput*) (this=0x55555996c600, source=0x555559caeb60)
    at /home/zumid/desktop/Apps/Olive Git/app/render/previewautocacher.cpp:78
#5  0x000055555599e405 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<olive::NodeInput*>, void, void (olive::PreviewAutoCacher::*)(olive::NodeInput*)>::call(void (olive::PreviewAutoCacher::*)(olive::NodeInput*), olive::PreviewAutoCacher*, void**) (f=
    (void (olive::PreviewAutoCacher::*)(olive::PreviewAutoCacher * const, olive::NodeInput *)) 0x5555559917a6 <olive::PreviewAutoCacher::NodeGraphChanged(olive::NodeInput*)>, o=0x55555996c600, arg=0x7fffffffcb20) at /usr/include/qt/QtCore/qobjectdefs_impl.h:152
#6  0x000055555599d9b2 in QtPrivate::FunctionPointer<void (olive::PreviewAutoCacher::*)(olive::NodeInput*)>::call<QtPrivate::List<olive::NodeInput*>, void>(void (olive::PreviewAutoCacher::*)(olive::NodeInput*), olive::PreviewAutoCacher*, void**) (f=
    (void (olive::PreviewAutoCacher::*)(olive::PreviewAutoCacher * const, olive::NodeInput *)) 0x5555559917a6 <olive::PreviewAutoCacher::NodeGraphChanged(olive::NodeInput*)>, o=0x55555996c600, arg=0x7fffffffcb20) at /usr/include/qt/QtCore/qobjectdefs_impl.h:185
#7  0x000055555599ca28 in QtPrivate::QSlotObject<void (olive::PreviewAutoCacher::*)(olive::NodeInput*), QtPrivate::List<olive::NodeInput*>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x555559cd5e70, r=0x55555996c600, a=0x7fffffffcb20, ret=0x0) at /usr/include/qt/QtCore/qobjectdefs_impl.h:418
#8  0x00007ffff35ba036 in  () at /usr/lib/libQt5Core.so.5
#9  0x0000555555831bca in olive::ViewerOutput::GraphChangedFrom(olive::NodeInput*) (this=0x555559c50d30, _t1=0x555559caeb60)
    at /home/zumid/desktop/Apps/Olive Git/build/app/olive-editor_autogen/TZS4I5HN7D/moc_viewer.cpp:416
#10 0x0000555555928ec6 in olive::ViewerOutput::InvalidateCache(olive::TimeRange const&, olive::NodeInput*, olive::NodeInput*)
    (this=0x555559c50d30, range=..., from=0x555559e03d20, source=0x555559caeb60) at /home/zumid/desktop/Apps/Olive Git/app/node/output/viewer/viewer.cpp:117
#11 0x0000555555944f4b in olive::Node::SendInvalidateCache(olive::TimeRange const&, olive::NodeInput*) (this=0x7fffe400c850, range=..., source=0x555559caeb60)
    at /home/zumid/desktop/Apps/Olive Git/app/node/node.cpp:315
#12 0x0000555555944565 in olive::Node::InvalidateCache(olive::TimeRange const&, olive::NodeInput*, olive::NodeInput*)
    (this=0x7fffe400c850, range=..., from=0x555559caeb60, source=0x555559caeb60) at /home/zumid/desktop/Apps/Olive Git/app/node/node.cpp:207
#13 0x0000555555922f0d in olive::TrackOutput::SetLengthInternal(olive::rational const&, bool) (this=0x7fffe400c850, r=..., invalidate=true)
    at /home/zumid/desktop/Apps/Olive Git/app/node/output/track/track.cpp:493
#14 0x0000555555923474 in olive::TrackOutput::BlockDisconnected(std::shared_ptr<olive::NodeEdge>) (this=0x7fffe400c850, edge=
    std::shared_ptr<olive::NodeEdge> (use count 4, weak count 0) = {...}) at /home/zumid/desktop/Apps/Olive Git/app/node/output/track/track.cpp:572
#15 0x0000555555924bac in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<std::shared_ptr<olive::NodeEdge> >, void, void (olive::TrackOutput::*)(std::shared_ptr<olive::NodeEdge>)>::call(void (olive::TrackOutput::*)(std::shared_ptr<olive::NodeEdge>), olive::TrackOutput*, void**) (f=
    (void (olive::TrackOutput::*)(olive::TrackOutput * const, std::shared_ptr<olive::NodeEdge>)) 0x555555923308 <olive::TrackOutput::BlockDisconnected(std::shared_ptr<olive::NodeEdge>)>, o=0x7fffe400c850, arg=0x7fffffffcfd0) at /usr/include/qt/QtCore/qobjectdefs_impl.h:152
#16 0x00005555559248c2 in QtPrivate::FunctionPointer<void (olive::TrackOutput::*)(std::shared_ptr<olive::NodeEdge>)>::call<QtPrivate::List<std::shared_ptr<olive::NodeEdge> >, void>(void (olive::TrackOutput::*)(std::shared_ptr<olive::NodeEdge>), olive::TrackOutput*, void**) (f=
    (void (olive::TrackOutput::*)(olive::TrackOutput * const, std::shared_ptr<olive::NodeEdge>)) 0x555555923308 <olive::TrackOutput::BlockDisconnected(std::shared_ptr<olive::NodeEdge>)>, o=0x7fffe400c850, arg=0x7fffffffcfd0) at /usr/include/qt/QtCore/qobjectdefs_impl.h:185
#17 0x000055555592449e in QtPrivate::QSlotObject<void (olive::TrackOutput::*)(std::shared_ptr<olive::NodeEdge>), QtPrivate::List<std::shared_ptr<olive::NodeEdge> >, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x555559e9e780, r=0x7fffe400c850, a=0x7fffffffcfd0, ret=0x0) at /usr/include/qt/QtCore/qobjectdefs_impl.h:418
#18 0x00007ffff35ba036 in  () at /usr/lib/libQt5Core.so.5
#19 0x000055555582e85a in olive::NodeInputArray::SubParamEdgeRemoved(std::shared_ptr<olive::NodeEdge>)
    (this=0x555559caeb60, _t1=std::shared_ptr<olive::NodeEdge> (use count 4, weak count 0) = {...})
    at /home/zumid/desktop/Apps/Olive Git/build/app/olive-editor_autogen/MFLS3X56JO/moc_inputarray.cpp:172
#20 0x0000555555940a36 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<std::shared_ptr<olive::NodeEdge> >, void, void (olive::NodeInputArray::*)(std::shared_ptr<olive::NodeEdge>)>::call(void (olive::NodeInputArray::*)(std::shared_ptr<olive::NodeEdge>), olive::NodeInputArray*, void**) (f=
    (void (olive::NodeInputArray::*)(olive::NodeInputArray * const, std::shared_ptr<olive::NodeEdge>)) 0x55555582e7fc <olive::NodeInputArray::SubParamEdgeRemoved(std::shared_ptr<olive::NodeEdge>)>, o=0x555559caeb60, arg=0x7fffffffd1e0) at /usr/include/qt/QtCore/qobjectdefs_impl.h:152
#21 0x00005555559408de in QtPrivate::FunctionPointer<void (olive::NodeInputArray::*)(std::shared_ptr<olive::NodeEdge>)>::call<QtPrivate::List<std::shared_ptr<olive::NodeEdge> >, void>(void (olive::NodeInputArray::*)(std::shared_ptr<olive::NodeEdge>), olive::NodeInputArray*, void**) (f=
    (void (olive::NodeInputArray::*)(olive::NodeInputArray * const, std::shared_ptr<olive::NodeEdge>)) 0x55555582e7fc <olive::NodeInputArray::SubParamEdgeRemoved(std::shared_ptr<olive::NodeEdge>)>, o=0x555559caeb60, arg=0x7fffffffd1e0) at /usr/include/qt/QtCore/qobjectdefs_impl.h:185
#22 0x0000555555940804 in QtPrivate::QSlotObject<void (olive::NodeInputArray::*)(std::shared_ptr<olive::NodeEdge>), QtPrivate::List<std::shared_ptr<olive::NodeEdge> >, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x555559eb3cb0, r=0x555559caeb60, a=0x7fffffffd1e0, ret=0x0) at /usr/include/qt/QtCore/qobjectdefs_impl.h:418
#23 0x00007ffff35ba036 in  () at /usr/lib/libQt5Core.so.5
--Type <RET> for more, q to quit, c to continue without paging--c
#24 0x0000555555832536 in olive::NodeParam::EdgeRemoved(std::shared_ptr<olive::NodeEdge>) (this=0x555559ed3510, _t1=std::shared_ptr<olive::NodeEdge> (use count 4, weak count 0) = {...}) at /home/zumid/desktop/Apps/Olive Git/build/app/olive-editor_autogen/MFLS3X56JO/moc_param.cpp:152
#25 0x000055555594cb3e in olive::NodeParam::DisconnectEdge(std::shared_ptr<olive::NodeEdge>) (edge=std::shared_ptr<olive::NodeEdge> (use count 4, weak count 0) = {...}) at /home/zumid/desktop/Apps/Olive Git/app/node/param.cpp:158
#26 0x000055555593fd97 in olive::NodeInputArray::RemoveAt(int) (this=0x555559caeb60, index=0) at /home/zumid/desktop/Apps/Olive Git/app/node/inputarray.cpp:185
#27 0x00005555559222d8 in olive::TrackOutput::RippleRemoveBlock(olive::Block*) (this=0x7fffe400c850, block=0x5555598241c0) at /home/zumid/desktop/Apps/Olive Git/app/node/output/track/track.cpp:340
#28 0x0000555555a6aca8 in olive::TrackReplaceBlockWithGapCommand::redo_internal() (this=0x555559e217c0) at /home/zumid/desktop/Apps/Olive Git/app/widget/timelinewidget/undo/undo.cpp:1091
#29 0x00005555559d218f in olive::UndoCommand::redo() (this=0x555559e217c0) at /home/zumid/desktop/Apps/Olive Git/app/undo/undocommand.cpp:34
#30 0x00007ffff43d91d2 in QUndoCommand::redo() () at /usr/lib/libQt5Widgets.so.5
#31 0x00007ffff43db6a7 in QUndoStack::push(QUndoCommand*) () at /usr/lib/libQt5Widgets.so.5
#32 0x00005555559d2300 in olive::UndoStack::pushIfHasChildren(QUndoCommand*) (this=0x7fffffffdf48, command=0x555557d89640) at /home/zumid/desktop/Apps/Olive Git/app/undo/undostack.cpp:28
#33 0x0000555555a7fcfb in olive::TimelineWidget::DeleteSelected(bool) (this=0x555557bf9260, ripple=false) at /home/zumid/desktop/Apps/Olive Git/app/widget/timelinewidget/timelinewidget.cpp:540
#34 0x000055555595c3f9 in olive::TimelinePanel::DeleteSelected() (this=0x5555596862c0) at /home/zumid/desktop/Apps/Olive Git/app/panel/timeline/timeline.cpp:92
#35 0x00005555559f82d7 in olive::MenuShared::DeleteSelectedTriggered() (this=0x5555581098a0) at /home/zumid/desktop/Apps/Olive Git/app/widget/menu/menushared.cpp:184
#36 0x00005555559f972c in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (olive::MenuShared::*)()>::call(void (olive::MenuShared::*)(), olive::MenuShared*, void**) (f=(void (olive::MenuShared::*)(olive::MenuShared * const)) 0x5555559f82ac <olive::MenuShared::DeleteSelectedTriggered()>, o=0x5555581098a0, arg=0x7fffffffd7f0) at /usr/include/qt/QtCore/qobjectdefs_impl.h:152
#37 0x00005555559f96af in QtPrivate::FunctionPointer<void (olive::MenuShared::*)()>::call<QtPrivate::List<>, void>(void (olive::MenuShared::*)(), olive::MenuShared*, void**) (f=(void (olive::MenuShared::*)(olive::MenuShared * const)) 0x5555559f82ac <olive::MenuShared::DeleteSelectedTriggered()>, o=0x5555581098a0, arg=0x7fffffffd7f0) at /usr/include/qt/QtCore/qobjectdefs_impl.h:185
#38 0x00005555559f961a in QtPrivate::QSlotObject<void (olive::MenuShared::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x5555583ea990, r=0x5555581098a0, a=0x7fffffffd7f0, ret=0x0) at /usr/include/qt/QtCore/qobjectdefs_impl.h:418
#39 0x00007ffff35ba036 in  () at /usr/lib/libQt5Core.so.5
#40 0x00007ffff4041f63 in QAction::triggered(bool) () at /usr/lib/libQt5Widgets.so.5
#41 0x00007ffff4044845 in QAction::activate(QAction::ActionEvent) () at /usr/lib/libQt5Widgets.so.5
#42 0x00007ffff4045488 in QAction::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#43 0x00007ffff4048752 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#44 0x00007ffff3582cda in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#45 0x00007ffff398bc2d in QShortcutMap::dispatchEvent(QKeyEvent*) () at /usr/lib/libQt5Gui.so.5
#46 0x00007ffff398c633 in QShortcutMap::tryShortcut(QKeyEvent*) () at /usr/lib/libQt5Gui.so.5
#47 0x00007ffff39342b4 in QWindowSystemInterface::handleShortcutEvent(QWindow*, unsigned long, int, QFlags<Qt::KeyboardModifier>, unsigned int, unsigned int, unsigned int, QString const&, bool, unsigned short) () at /usr/lib/libQt5Gui.so.5
#48 0x00007ffff39573bc in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) () at /usr/lib/libQt5Gui.so.5
#49 0x00007ffff3930bac in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#50 0x00007fffebdbef9c in  () at /usr/lib/libQt5XcbQpa.so.5
#51 0x00007fffee889bfc in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#52 0x00007fffee8db1f9 in  () at /usr/lib/libglib-2.0.so.0
#53 0x00007fffee888421 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#54 0x00007ffff35db941 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#55 0x00007ffff358165c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#56 0x00007ffff3589af4 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#57 0x000055555587ab97 in main(int, char**) (argc=1, argv=0x7fffffffe0d8) at /home/zumid/desktop/Apps/Olive Git/app/main.cpp:178
</code></pre></details>

**Additional Information**

Tested:
 - Deleting all the Merge nodes and removing a footage from any track
 - Deleting a single Merge node and removing a footage from any two tracks affected
 - Removing a track connection to a Merge node and removing a footage from the affected track

**Comment by ThomasWilshaw** [comment] 2020-12-14 23:49
So the problem here is that when the user deletes an edge on the merge node, (say edge[0]), all the other edges are shitfed down one and egde[1] becomes edge[0] etc. This means that when we then delete the block in the timeline it tries to disconnect the wrong edge (i.e. the edge that was previously edge[1]). This trickles all the way down to the cache render and things mess up.

What we might need to do is cause blocks to be deleted from the timeline when a relevant edge is deleted? This possibly ties into https://github.com/olive-editor/olive/issues/1255#issuecomment-706544231, adding new track or block nodes doesn't make anything happen in the timeline.

**Comment by itsmattkc** [comment] 2021-03-22 12:16
Is this reproducible in the latest commit?

**Comment by itsmattkc** [comment] 2021-04-12 05:32
This has most likely been fixed due to the recent sweeping node architecture changes so I will therefore close it. If it can be confirmed to still occur, it can be re-opened.

**Closed by itsmattkc** 2021-04-12 05:32 UTC
Labels: Crash, Nodes/Compositing
