### ISSUE TITLE
[UI] Layout don´t save when app is closed

### ISSUE THREAD

**Issue by SiyrShiny** [olive-editor/olive#1600] opened 2021-04-30 06:33 UTC
**Commit Hash** 

**Platform** Windows 10

**Summary**

**Additional Information / Output**

**Comment by AGI-THB** [comment] 2021-04-30 06:39
Fill out the issue template.

**Comment by itsmattkc** [comment] 2021-04-30 07:20
Duplicate of #1231

**Closed by itsmattkc** 2021-04-30 07:20 UTC
Labels: Triage, User Interface
