### ISSUE TITLE
[Feature Request] Rendering on GPU

### ISSUE THREAD

**Issue by mcDandy** [olive-editor/olive#1064] opened 2019-08-19 11:37 UTC
**Is your feature request related to a problem? Please describe.**
I would like to see GPU acceleration on rendering. It is possible to speed up rendering copule of times.

**Describe the solution you'd like**
Ability to choose  GPU as rendering device. Pricier GPUs have hardvare acceleration of encoding capability, which is faster than CPU. 

**Describe alternatives you've considered**
Rendering on CPU, which is slower

**Do you know any libraries or sources that can help the Olive Team include the feature?**
I do not know any .I could find something if I have known how rendering on GPU works.

**Additional context**
Sorry for my english.

**Comment by AGI-THB** [comment] 2019-08-19 15:48
repost: #26

**Comment by sobotka** [comment] 2019-08-19 18:45
Duplicate of #26. Closing.

**Closed by sobotka** 2019-08-19 18:45 UTC

**Comment by mcDandy** [comment] 2019-08-20 16:45
Od did not find anything with "title search. Do not know how to search issues on github. Sory for duplicate."
