### ISSUE TITLE
Video desyncs with audio after importing

### ISSUE THREAD

**Issue by jasonTong68** [olive-editor/olive#798] opened 2019-04-14 08:52 UTC
### System Information

**Olive version:** `6264123b`
**Source:** Website
**Operating system:** Windows 10 64bit
**CPU:** Intel Core i3 6100
**RAM:** 8GB
**GPU:** NVIDIA GeForce GTX 1050 Ti (Driver version 419.67)

### Detailed Description

After importing a video recorded by a camera, the video is delayed by around 1 second than the audio. The video does not desync when played with other players like VLC.

### Steps to reproduce

This video is an example. https://www.dropbox.com/s/7os91mtr09fpqqf/00093.MTS?dl=0

Drag and drop the video onto the timeline. The video will be delayed.

**Comment by itsmattkc** [comment] 2019-04-14 12:00
Duplicate of #769, known issue with MTS files.

**Closed by itsmattkc** 2019-04-14 12:00 UTC
