### ISSUE TITLE
[UI] Drag and Drop not working

### ISSUE THREAD

**Issue by Funtime60** [olive-editor/olive#1525] opened 2021-03-23 04:13 UTC
**Commit Hash** 
c444213a

**Platform** 
Win10 Home -10.0.19042

**Summary**
I can no longer drag file from file explorer into the project section. The mouse icon is simply a grey/black [https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/ProhibitionSign2.svg/1200px-ProhibitionSign2.svg.png](url) (Sorry, I don't know the name of the icon). After the only thing I did was open and import my keyboard settings since those don't save automatically. I did not check if it worked before that.

**Additional Information / Output**

**Comment by itsmattkc** [comment] 2021-03-23 08:13
Do you have any specific steps to recreate this?

**Comment by Simran-B** [comment] 2021-03-23 10:32
Can't reproduce it on Windows 10 in 7e00ffa8:

![image](https://user-images.githubusercontent.com/7819991/112131999-6f2ff280-8bca-11eb-9cca-0d608565dd31.png)

If a file is dragged to an area that doesn't support dropping it, then a red icon indicates that it is blocked:

![image](https://user-images.githubusercontent.com/7819991/112132305-bddd8c80-8bca-11eb-918b-a72ea8a23e48.png)

However, if I run Olive as administrator, then drag'n'drop is disabled entirely and this is indicated with a black icon:

![image](https://user-images.githubusercontent.com/7819991/112131763-2b3ced80-8bca-11eb-8807-9327bb7e2855.png)

@Funtime60 Did you use the installer? It launches Olive with elevated permissions after the setup, disabling drag'n'drop. It would be a duplicate of #1245 in that case.

**Comment by Funtime60** [comment] 2021-03-23 12:27
Yes I did use the installer, however I didn't realize this was expected
behavior as I used the installer just a few days ago and was able to drag
and drop just fine.

AH! I just tested it and realized exactly what you meant and yes that is
exactly what happened. My apologies.

Sincerely: Daniel Peaslee

linkedin.com/in/daniel-peaslee-23b889178

**Closed** 2021-03-23 12:26 UTC
Labels: Inadequate Information, User Interface

**Comment by Simran-B** [comment] 2021-03-23 13:55
It is currently expected, but not intended. The workaround is simply to start Olive normally yourself.

**Comment by itsmattkc** [comment] 2021-03-23 14:33
#1245 is fixed now so this shouldn't be an issue anymore

**Comment by Simran-B** [comment] 2021-03-23 14:54
Nice, works on my end with the latest installer.
