### ISSUE TITLE
[NODES] OCIO Color Grading effects everything in the sequence

### ISSUE THREAD

**Issue by Avispa** [olive-editor/olive#2134] opened 2022-12-26 03:04 UTC
### System
**Commit Hash**: de8d50e
**Platform**: Windows 10

### Summary
Maybe I get this feature wrong but adding the effect/node effects the whole image of the sequence although according to the node-graph it should only effect the specific clip/graph.

#### Steps to Reproduce
1. Add two text clips.
2. Add _"OCIO Color Grading"_ to one of them.
3. Change colour value _"Offset"_ on **_all_** clips on the sequence.

#### Expected behaviour
As like as the node graph implies: only change the output/clip of the graph/clip where the effect is attached to.

**Comment by itsmattkc** [comment] 2022-12-26 22:09
Can you send a video/screen recording of this happening?

**Comment by Avispa** [comment] 2022-12-31 03:10
Here is the video:

https://user-images.githubusercontent.com/25295052/210123027-89f9dae0-bbd6-4a96-bc89-9938f9597c91.mp4

After recording this example I felt I should also test with 3 tracks to test the quick claim that the problem effects all sequences (didn't record). I think now that the problem is a bit more specific and is just related to transparent areas (but not to "totally empty" clips).

**Comment by ThomasWilshaw** [comment] 2023-01-20 17:44
Are you able to re uplaod the video? For somereason it's not displaying.

**Comment by itsmattkc** [comment] 2023-02-22 03:32
Your video doesn't play.

As far as "all other clips in the sequence" being affected, I can't recreate that - other clips all appear to be normal. If you mean only the clips underneath/being merged with the text clip, that would be somewhat to be expected because "Offset" by definition will offset the RGB values upwards, which will result in a light grey. These values can be seen with the pixel sampler.

I'm guessing that's what you were running into, and since that's expected/intended behavior, I will close this.

**Closed by itsmattkc** 2023-02-22 03:33 UTC
Labels: Nodes/Compositing, Triage
