### ISSUE TITLE
[UI] AppImage on Linux does not load the Olive logo

### ISSUE THREAD

**Issue by AntonioBerna** [olive-editor/olive#2280] opened 2023-08-31 20:08 UTC
**Commit Hash** 
1687a721

**Platform** 
Linux Manjaro

**Summary**
Both the .ove files and the Olive program when running on Linux Manjaro do not have the Olive logo.

**Additional Information / Output**

**Comment by Simran-B** [comment] 2023-08-31 20:30
Duplicate of https://github.com/olive-editor/olive/issues/1317?

**Comment by AntonioBerna** [comment] 2023-08-31 21:01
> Duplicate of #1317?

Ok but how come it hasn't been fixed yet?

**Comment by Simran-B** [comment] 2023-08-31 21:04
I don't have a Linux system to test the suggested change to the .desktop file but if that all or takes, then that would be a simple fix. I'm afraid however that it works on a few distros at best, and the chance of a fix in the upstream AppImage project seems unlikely.

**Comment by AntonioBerna** [comment] 2023-08-31 21:12
I understand... unfortunately I'm having a lot of problems with this video editor, in fact I opened another issue (#2277) but I haven't received news yet... it's a real shame because I like the GUI a lot but I think I'll have to find a more valid alternative

**Closed** 2023-08-31 21:48 UTC
Labels: User Interface, Triage
