### ISSUE TITLE
[NODES] Granular control for sampling and rendering of typefaces

### ISSUE THREAD

**Issue by goldenbait** [olive-editor/olive#969] opened 2019-05-21 14:37 UTC
Making smooth rolling end credits is not as easy as it should be in todays NLEs and popular compositors. After Effects need a small script, Fusion needs messing around with non obvious keyframing of non obvious nodes. I'm pretty sure Premiere Pro can't do it at all.

The problem is that text doesn't move on whole pixels, which in turn makes the movement of text appear jittery as the aliasing tries to render text between pixels.

The solution is to move the text on intervals of whole pixels. 3 pixels per frame for example. This limits how precisely you can time your rolling credits, but makes them appear buttery smooth.

Since we're getting a node workflow (yay) I suggest having a "Scroll on whole pixels" node, where you choose a direction (up, down, left, right) and a speed (1-25 pixels per frame seems reasonable, credits need 1-10, but maybe way higher for flexibility) that you plug your source into.

To understand this issue better I recommend reading this article [http://endcrawl.com/blog/why-are-my-end-titles-jittering/](http://endcrawl.com/blog/why-are-my-end-titles-jittering/)

**Comment by sobotka** [comment] 2019-05-21 14:42
It comes down to sampling, which isn’t much of an issue to sort out if the sampling function is exposed. The Endcrawl peeps are great.

**Comment by goldenbait** [comment] 2019-05-21 14:59
There are many ways to make text move, and few need to move on whole pixels. The transform values for example should be able to be to hit decimals. Since it is rare it needs a dedicated way of doing it.

The easiest and most flexible way I can think of is a node like this, as you could plug images (logos) into it as well for more designed end credits.

**Comment by sobotka** [comment] 2019-05-21 15:39
>There are many ways to make text move, and few need to move on whole pixels. The transform values for example should be able to be to hit decimals. Since it is rare it needs a dedicated way of doing it.

It's sampling and how you sample. It's not really about "many ways".

In graphics, where you don't want a tear or a hole, usually you reverse project from the screen back into a given buffer. For example, if we start in the upper left corner of the destination buffer, and transform via an offset, we'd peek into the source buffer after the transformed values, and grab the nearest pixel. This is a rounding essentially, and grabbing the RGB in the source buffer that is at the transformed coordinate. If we used linear sampling, we'd calculate a percentage of the transform, and estimate the result _between_ the source pixels, linearly sampled.

This is why it comes down to sampling I believe, _not_ a separate node, but rather simply a matter of formulating the sampling based on a variable that is determined by the stroke of the glyph in question.

All of that is to suggest that it has less to do with typeface stroke rendering and more about providing sane sampling options for the transform vertex such that the one can achieve Endcrawl per-stroke-width incrementing without adding more and more nodes / vertices.

**Comment by goldenbait** [comment] 2019-05-21 15:57
I honestly have little knowledge about rendering graphics on the screen, you obviously know way more about this than me. I'm just a professional user.

Are you saying that your proposition would result in moving graphics on whole pixels, or that the rendering would result in smooth motion even on say 2.283 pixels per frame? If it is the latter I have my doubts, all professional NLEs and compositors handles rendering graphics between frames just fine (I guess this is what you mean by sampling. Linear, bilinear etc.)

However, as stated in the article I linked, it will appear various degrees of jittery no matter how you sample it unless you move on round integers, whole pixels. It's limited, it's inconvinient, but it is the only thing that looks great in a cinema or even a big TV.

**Comment by sobotka** [comment] 2019-05-21 16:10
>Are you saying that your proposition would result in moving graphics on whole pixels, or that the rendering would result in smooth motion even on say 2.283 pixels per frame?

Given that a glyph stroke in a typeface font file varies based on rasterization, the transform sampling would also need to vary accordingly. Direction, for example, would also play a role, where the vertical glyph stroke is a different increment to a horizontal.

>As stated in the article I linked, it will appear various degrees of jittery no matter how you sample it unless you move on round integers, whole pixels.

I don’t believe this encompasses the issue entirely, given that a degree of the motion depends on the glyph stroke dimension as it is rasterized, and as such, it is a little more nuanced than simply “whole pixels.”

>all professional NLEs and compositors handles rendering graphics between frames just fine

Citation needed; most don’t handle the pixel pipe properly at all. Some compositors and hybrid compositing / grading applications can, for certain, but NLEs typically don’t give much of a care to it as more serious projects are conforming elsewhere.

**Comment by goldenbait** [comment] 2019-05-21 16:22
On your second point, there might be more to the equation to make this work. The end result should in any case be a pixel perfect copy of the text shifted up. An estimation (sampling, right?) is just not enough, as is why I bring this up as an issue.

I'm gonna end my involvement on this issue for now as I've hit the limit on what I know about it.

Someone else who has some experience on creating rolling end credits specifically should perhaps chime in.

**Comment by sobotka** [comment] 2019-05-21 16:32
>An estimation (sampling, right?) is just not enough, as is why I bring this up as an issue.

Sampling is essentially the “logic” as to how to pull a value from a signal. If the sampling is handled correctly, with variables, it should be entirely fine and granular. Sampling as you are describing it is simply from a higher level interpretation that you’ve seen in GUIs. It extends beyond that.

In this case though, it is not _simply_ sampling, as part of text being rendered from splines involves how it is rasterized. For example, if the typeface is rasterized such that the glyph stroke is on a subpixel, how _that_ buffer is sampled is tricky.

Anyways, you are obsessing a bit here. Olive currently doesn’t have basic cutting yet, so delving into nuances of text rendering, especially in a Non Linear Editor, is probably going a tad off the cart-before-horse end.

It all does indeed come down to sampling.

**Comment by frink** [comment] 2019-05-22 02:03
I create a PNG from Inkscape for the full length of the scroll. Then do a transform moving it up at a certain rate. I've found that making the PNG about 20% wider than the video allows me to scale it down in a way that looks sharp with subpixel hinting. Haven't done this in Olive yet. But that's how I've done it in others. You could probable generate the PNG from DTP software as well. Most of them will generate PNGs now days...

**Comment by sobotka** [comment] 2019-05-22 02:05
This is a specific sampling issue, and has zilch to do with Inkscrape. Read the Endcrawl article.

**Comment by frink** [comment] 2019-05-22 04:28
@sobotka thanks. Read. Thanks. I commented too quick. Sorry...

So the issue is really about HOW to know what the ppf speed of scroll is... Seems all we need to do is provide a way to change scroll rate to integer ppf rates and we will be good. Just need a way to help with the math... Is that the issue?

**Comment by goldenbait** [comment] 2019-05-29 17:56
> Anyways, you are obsessing a bit here. Olive currently doesn’t have basic cutting yet, so delving into nuances of text rendering, especially in a Non Linear Editor, is probably going a tad off the cart-before-horse end.
>

I agree, this shouldn't be a priority in any sense. I wouldn't say I'm obsessing, as I need to do this for professional short films from time to time, and it's a pain in any NLE. Also we would bless the world with less shitty endcrawls. This issue should be kept around for when the time is right. It would be a killer QoL feature for those that require it.

**Comment by itsmattkc** [comment] 2021-03-25 22:49
I think this could be more or less achieved in the current system by connecting a "time" node to a text position and letting it automate the scrolling. We might need to implement a few more nodes to make it work as described in the OP, but they'll be coming anyway. I'll close this as it should be very much possible soon with the direction we're headed in.

**Closed by itsmattkc** 2021-03-25 22:49 UTC
Labels: Low Priority, Nodes/Compositing
