### ISSUE TITLE
[BUILD] writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]

### ISSUE THREAD

**Issue by gianmarcogg03** [olive-editor/olive#1785] opened 2021-11-02 22:46 UTC
**Commit Hash** 
cf1bd65

**Platform** 
Arch Linux

**Summary**
The compiler stops at `cc1plus: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]`.

**Additional Information / Output**
![2021-11-02_23-46](https://user-images.githubusercontent.com/28053717/139962100-793b4ffa-9c76-4315-9556-290f13c6d488.png)

**Comment by elsandosgrande** [comment] 2021-11-03 00:17
Duplicate of #1590

**Closed by elsandosgrande** 2021-11-03 00:17 UTC
Labels: Building/Packaging, Triage
