### ISSUE TITLE
[Bug] Audio is gone with .avi files

### ISSUE THREAD

**Issue by crihminaal** [olive-editor/olive#1081] opened 2019-09-04 21:55 UTC
**Your Setup:**
- Olive version (window title or Help > About): April @019
- Source: (e.g. AppImage, PPA, AUR, website etc.)
- Operating system: (e.g. Ubuntu 18.04 64-bit)
- CPU: (e.g. Intel i5-4300U)
- RAM: (e.g. 8GB)
- GPU: (e.g. NVIDIA Geforce GT 1030 2GB (Driver ver xxx.xx.xx))

**Describe the Bug**

**To Reproduce**

**Screenshots**

** Debug Log and/or Crash Report **

```
[Paste log/report]
```

**Additional Details**
Add any other information about the problem here.

**Comment by NathanSalapat** [comment] 2019-09-04 23:15
Your supposed to replace the text in the issue description with what you have and what the problem is, your issue tells us nothing.

**Comment by AGI-THB** [comment] 2019-09-05 12:14
I think this issue is useless and should be closed.
Another reason for closing it is that the engine is being rewritten anyway.

Audio Issues also have another ticket already #889 

@sobotka

**Closed** 2020-09-13 04:59 UTC
Labels: Legacy (Unsupported)
