### ISSUE TITLE
[CRASH] Cancelling a media export doesn't properly cancel the export

### ISSUE THREAD

**Issue by aeroc7** [olive-editor/olive#1900] opened 2022-04-20 22:27 UTC
**Commit Hash** 
3661599

**Platform** 
Linux -- can't seem to reproduce on macOS (not tested on Windows)

**Summary**
If exporting media and you decide to cancel it (either by x-ing the window or clicking 'cancel'), a seg fault will occur.

**Steps to Reproduce**

1. Export media
2. Click cancel or 'x'
3. 

<details><summary><strong>Crash Report</strong></summary><pre><code>

* thread #24, name = 'Thread (pooled)', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
* frame #0: 0x00007ffff3bc0ebf libQt5Core.so.5`void doActivate<false>(QObject*, int, void**) + 47
* frame #1: 0x00000000004a3ee4 olive-editor`olive::Task::ProgressChanged(this=0x00007fff88564ec0, _t1=0.00079009744535159341) at moc_task.cpp:178:5
* frame #2: 0x00000000006dc140 olive-editor`olive::ExportTask::FrameDownloaded(this=0x00007fff88564ec0, f=std::__shared_ptr<olive::Frame, __gnu_cxx::_S_atomic>::element_type @ 0x00007fff899caec0, hash=0x00007fff758afa40, times=0x00007fff758afa08) at export.cpp:189:10
* frame #3: 0x00000000006e4868 olive-editor`olive::RenderTask::Render(this=0x00007fff88564ec0, manager=0x00000000053c08e0, video_range=0x00007fff758b00d0, audio_range=0x00007fff758b00c8, subtitle_range=0x00007fff758b0098, mode=kOnline, cache=0x0000000000000000, force_size=0x00007fff758b0190, force_matrix=0x00007fff758b0148, force_format=kFormatUnsigned16, force_color_output=std::__shared_ptr<olive::ColorProcessor, __gnu_cxx::_S_atomic>::element_type @ 0x00007fff6c30fcc0) at render.cpp:222:14
* frame #4: 0x00000000006dba4c olive-editor`olive::ExportTask::Run(this=0x00007fff88564ec0) at export.cpp:128:3
* frame #5: 0x00000000004be46a olive-editor`olive::Task::Start(this=0x00007fff88564ec0) at task.h:97:16
* frame #6: 0x000000000059dd77 olive-editor`QtConcurrent::StoredMemberFunctionPointerCall0<bool, olive::Task>::runFunctor(this=0x0000000003112c70) at qtconcurrentstoredfunctioncall.h:189:24
* frame #7: 0x000000000059dc05 olive-editor`QtConcurrent::RunFunctionTask<bool>::run(this=0x0000000003112c70) at qtconcurrentrunbase.h:108:19
* frame #8: 0x00007ffff39d35d0 libQt5Core.so.5`QThreadPoolThread::run() + 128
* frame #9: 0x00007ffff39d04c6 libQt5Core.so.5`QThreadPrivate::start(void*) + 342
* frame #10: 0x00007ffff352eb1a libc.so.6`start_thread + 730
* frame #11: 0x00007ffff35b3660 libc.so.6`__clone3 + 48

</code></pre></details>

**Additional Information**

**Comment by itsmattkc** [comment] 2022-04-25 20:34
I feel like this is essentially a duplicate of #1899. Either way, render jobs are not finishing when they should be. Therefore I'm going to merge this issue into that one.

**Closed by itsmattkc** 2022-04-25 20:34 UTC
Labels: Crash, Triage
