### ISSUE TITLE
[Feature Request] Motion Tracking

### ISSUE THREAD

**Issue by MisterTeeXD** [olive-editor/olive#679] opened 2019-03-23 14:35 UTC
It would be great if there was a effect that allows us to have a title motion tracked to, lets say, a moving hand.

**Comment by hamzamihoub** [comment] 2019-03-23 18:00
yes, i agree 
and some sort of video stabilization would even greater.

**Comment by MisterTeeXD** [comment] 2019-03-23 18:01
Yep

**Comment by AGI-THB** [comment] 2019-03-23 18:35
#452

**Comment by itsmattkc** [comment] 2019-03-23 23:04
Indeed, duplicate of #452

**Closed by itsmattkc** 2019-03-23 23:04 UTC
