### ISSUE TITLE
Change Timecode font

### ISSUE THREAD

**Issue by tree786** [olive-editor/olive#824] opened 2019-04-17 15:24 UTC
### Detailed Description
Feature request

Currently, it seems that there is no option to set the font of the `Timecode` object (please correct me if I'm mistaken). It would be nice to expose an option which allows changing the font (e.g. like the `Edit Text` button used in the `Text` object).

**Comment by oc1024** [comment] 2019-04-17 15:31
If Olive fully bets on nodes, another possibility is having a "Render Text" node fed by a "Timecode Generator" node. This would bring about new possibilities to make Olive more versatile (though it might cost intuitiveness for more casual users).

**Comment by itsmattkc** [comment] 2019-04-17 15:59
Duplicate of #723, but also what @oc1024 says is something I've been considering.

**Closed by itsmattkc** 2019-04-17 15:59 UTC
