### ISSUE TITLE
[UI] Mask editing UX

### ISSUE THREAD

**Issue by prokoudine** [olive-editor/olive#2068] opened 2022-10-15 22:47 UTC
**Commit Hash**

7791dde9

**Platform**

Ubuntu Linux 22.04, 64-bit

**Summary**

Masks are becoming really helpful but need more UI/UX love. The things I've been struggling with in particular are:

- Pretty much impossible to move a node without moving two of its CPs first.
- Once I accidentally move CPs, I need to drag them back on top of their node. Elsewhere (Inkscape), Ctrl+click resets CPs' position.
- Both nodes and their CPs are tiny in HiDPI and very hard to grab, especially on top of a light/white backdrop
- Lining up nodes is difficult, some sort of horizontal/vertical constraint or guides+snapping would help a ton

**Additional Information / Output**

In terms of UX, darktable has a semi-decent approach to handling masks on the screen, with on-canvas controlled feathering.

![image](https://user-images.githubusercontent.com/57467/196010305-d8faa57c-6221-4339-a913-d394f1f810e1.png)

**Comment by itsmattkc** [comment] 2022-10-16 06:38
Duplicate of #1907

**Closed by itsmattkc** 2022-10-16 06:38 UTC
Labels: User Interface, Triage
