### ISSUE TITLE
"Normal" blending works like "Add"

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#790] opened 2019-04-12 16:24 UTC
I've built Olive from 233a409b Master.

I'd expect this sequence to result in just the Bars being visible, instea they are added to the background:

![image](https://user-images.githubusercontent.com/491704/56051684-c88d1700-5d4f-11e9-9ff9-ca9fa7c9eb90.png)

If I disable the Transform effect, it works as expected again (no blending is used).

Can anyone confirm this?

**Comment by unfa** [comment] 2019-04-12 16:34
Somehow doing `sudo make uninstall` fixed the problem:

```
[unfa@unfa-desktop Olive]$ sudo make uninstall
[sudo] password for unfa: 
rm -f /usr/local/bin/olive-editor
rmdir /usr/local/bin/ 
rmdir: failed to remove '/usr/local/bin/': Directory not empty
make: [Makefile:7649: uninstall_target] Error 1 (ignored)
rm -f -r /usr/local/share/olive-editor/effects/wave.xml
rm -f -r /usr/local/share/olive-editor/effects/wave.frag
rm -f -r /usr/local/share/olive-editor/effects/volumetriclight.xml
rm -f -r /usr/local/share/olive-editor/effects/volumetriclight.frag
rm -f -r /usr/local/share/olive-editor/effects/vignette.xml
rm -f -r /usr/local/share/olive-editor/effects/vignette.frag
rm -f -r /usr/local/share/olive-editor/effects/toonify.xml
rm -f -r /usr/local/share/olive-editor/effects/toonify.frag
rm -f -r /usr/local/share/olive-editor/effects/tile.xml
rm -f -r /usr/local/share/olive-editor/effects/tile.frag
rm -f -r /usr/local/share/olive-editor/effects/swirl.xml
rm -f -r /usr/local/share/olive-editor/effects/swirl.frag
rm -f -r /usr/local/share/olive-editor/effects/sphere.xml
rm -f -r /usr/local/share/olive-editor/effects/sphere.frag
rm -f -r /usr/local/share/olive-editor/effects/ripple.xml
rm -f -r /usr/local/share/olive-editor/effects/ripple.frag
rm -f -r /usr/local/share/olive-editor/effects/radialblur.xml
rm -f -r /usr/local/share/olive-editor/effects/radialblur.frag
rm -f -r /usr/local/share/olive-editor/effects/posterize.xml
rm -f -r /usr/local/share/olive-editor/effects/posterize.frag
rm -f -r /usr/local/share/olive-editor/effects/pixelate.xml
rm -f -r /usr/local/share/olive-editor/effects/pixelate.frag
rm -f -r /usr/local/share/olive-editor/effects/noise.xml
rm -f -r /usr/local/share/olive-editor/effects/noise.frag
rm -f -r /usr/local/share/olive-editor/effects/lumakey.xml
rm -f -r /usr/local/share/olive-editor/effects/lumakey.frag
rm -f -r /usr/local/share/olive-editor/effects/invert.xml
rm -f -r /usr/local/share/olive-editor/effects/invert.frag
rm -f -r /usr/local/share/olive-editor/effects/huesatbri.xml
rm -f -r /usr/local/share/olive-editor/effects/huesatbri.frag
rm -f -r /usr/local/share/olive-editor/effects/gaussianblur.xml
rm -f -r /usr/local/share/olive-editor/effects/gaussianblur.frag
rm -f -r /usr/local/share/olive-editor/effects/flip.xml
rm -f -r /usr/local/share/olive-editor/effects/flip.frag
rm -f -r /usr/local/share/olive-editor/effects/fisheye.xml
rm -f -r /usr/local/share/olive-editor/effects/fisheye.frag
rm -f -r /usr/local/share/olive-editor/effects/findedges.xml.disabled
rm -f -r /usr/local/share/olive-editor/effects/findedges.frag
rm -f -r /usr/local/share/olive-editor/effects/emboss.xml
rm -f -r /usr/local/share/olive-editor/effects/emboss.frag
rm -f -r /usr/local/share/olive-editor/effects/dropshadow.xml.disabled
rm -f -r /usr/local/share/olive-editor/effects/directionalblur.xml
rm -f -r /usr/local/share/olive-editor/effects/directionalblur.frag
rm -f -r /usr/local/share/olive-editor/effects/crossstitch.xml
rm -f -r /usr/local/share/olive-editor/effects/crossstitch.frag
rm -f -r /usr/local/share/olive-editor/effects/crop.xml
rm -f -r /usr/local/share/olive-editor/effects/crop.frag
rm -f -r /usr/local/share/olive-editor/effects/common.vert
rm -f -r /usr/local/share/olive-editor/effects/common.frag
rm -f -r /usr/local/share/olive-editor/effects/colorsel.xml
rm -f -r /usr/local/share/olive-editor/effects/colorsel.frag
rm -f -r /usr/local/share/olive-editor/effects/colorcorrection.xml
rm -f -r /usr/local/share/olive-editor/effects/colorcorrection.frag
rm -f -r /usr/local/share/olive-editor/effects/chromaticaberration.xml
rm -f -r /usr/local/share/olive-editor/effects/chromaticaberration.frag
rm -f -r /usr/local/share/olive-editor/effects/chromakey.xml
rm -f -r /usr/local/share/olive-editor/effects/chromakey.frag
rm -f -r /usr/local/share/olive-editor/effects/bulge.xml
rm -f -r /usr/local/share/olive-editor/effects/bulge.frag
rm -f -r /usr/local/share/olive-editor/effects/boxblur.xml
rm -f -r /usr/local/share/olive-editor/effects/boxblur.frag
rmdir /usr/local/share/olive-editor/effects/ 
rm -f -r /usr/local/share/metainfo/org.olivevideoeditor.Olive.appdata.xml
rmdir /usr/local/share/metainfo/ 
rm -f -r /usr/local/share/applications/org.olivevideoeditor.Olive.desktop
rmdir /usr/local/share/applications/ 
rmdir: failed to remove '/usr/local/share/applications/': Directory not empty
make: [Makefile:7796: uninstall_desktop] Error 1 (ignored)
rm -f -r /usr/local/share/mime/packages/org.olivevideoeditor.Olive.xml
rmdir /usr/local/share/mime/packages/ 
rm -f -r /usr/local/share/icons/hicolor/16x16/apps/org.olivevideoeditor.Olive.png
rmdir /usr/local/share/icons/hicolor/16x16/apps/ 
rm -f -r /usr/local/share/icons/hicolor/32x32/apps/org.olivevideoeditor.Olive.png
rmdir /usr/local/share/icons/hicolor/32x32/apps/ 
rm -f -r /usr/local/share/icons/hicolor/48x48/apps/org.olivevideoeditor.Olive.png
rmdir /usr/local/share/icons/hicolor/48x48/apps/ 
rm -f -r /usr/local/share/icons/hicolor/64x64/apps/org.olivevideoeditor.Olive.png
rmdir /usr/local/share/icons/hicolor/64x64/apps/ 
rm -f -r /usr/local/share/icons/hicolor/128x128/apps/org.olivevideoeditor.Olive.png
rmdir /usr/local/share/icons/hicolor/128x128/apps/ 
rm -f -r /usr/local/share/icons/hicolor/256x256/apps/org.olivevideoeditor.Olive.png
rmdir /usr/local/share/icons/hicolor/256x256/apps/ 
rm -f -r /usr/local/share/icons/hicolor/512x512/apps/org.olivevideoeditor.Olive.png
rmdir /usr/local/share/icons/hicolor/512x512/apps/
```

**Comment by itsmattkc** [comment] 2019-04-12 17:18
There's a "known issue" where transferring a project between the `furtherocio` and `master` branches will break the blending mode for the other branch due to differences in their pipelines. My assumption this was caused by something of that nature.

**Comment by unfa** [comment] 2019-04-12 17:24
Interesting. I haven't checked out `furtherocio` at any point, but I messed in the code a bit to re-enable blending modes.

**Comment by itsmattkc** [comment] 2019-04-17 16:57
I have a feeling this was something strange in your setup, judging by the issues you were having with `make install`. I'll close this and you can let me know if it returns.

**Closed by itsmattkc** 2019-04-17 16:57 UTC
