### ISSUE TITLE
 [EDIT] Applying all the Effects and animating it and reversing the same video and audio causes the audio to not be reversed and several frames to not be rendered

### ISSUE THREAD

**Issue by 111ukasz111** [olive-editor/olive#1716] opened 2021-08-11 11:24 UTC
**Commit Hash** 
132e637f

**Platform** 
Windows 10 Intelcore i7, Nvidia Geforce 920M, 4gb ram

**Summary**
Steps to reproduce:
1. Applay all Effects nodes to this video and animate it using keyframes. 
2. Change the scale to 50% of this video . 
3. Turn on  reverse on video and audio. on this media.
Expected Result:
Video and audio should be revesed.
Actual result:
Video is reversed and audio is not revesed and a few frames are not rendered.

**Additional Information / Output**

https://user-images.githubusercontent.com/20667528/129020708-21b8a331-71ad-4982-82e6-6fb23a83d855.mp4

**Comment by itsmattkc** [comment] 2021-09-06 23:16
I believe this is a duplicate of #1706

**Closed by itsmattkc** 2021-09-06 23:16 UTC
Labels: Timeline/Editing, Triage
