### ISSUE TITLE
[EXPORT] Feature request: Export audio only

### ISSUE THREAD

**Issue by libalis** [olive-editor/olive#1467] opened 2021-01-17 20:10 UTC
Would be amazing if you could export only the audio of a sequence as MP3, AAC, WAV or FLAC.

Don't think this is way too complicated to implement, but I have to agree that it is not priority number 1.

Thank you very much for the amazing development of the olive video editor since the first version.

0.2 looks amazing, I'm already using it, I'm sending bug reports and can't wait for the final launche.

**Comment by itsmattkc** [comment] 2021-01-21 22:50
This is already an option:
![image](https://user-images.githubusercontent.com/34096995/105422068-38576200-5c97-11eb-857c-84b6829afbb3.png)

I'm not sure if it's implemented correctly yet, but that would fall under #1345

**Comment by libalis** [comment] 2021-04-21 18:40
I know that the function to export audio only already exists, but that was not the idea behind my issue.

It lacks the functionality when only audio is exported to export into an audio format (MP3, AAC, WAV or FLAC).

Please excuse the misunderstanding.

And thank you very much for everything that all the developers have made possible on this great project.

**Comment by Simran-B** [comment] 2021-04-22 08:40
I deem this a fair request. There should be a way to bounce out audio without sticking it into a video container. It could be implemented in either of the following two ways:
- Format: Audio only
  Codec selection in the Audio tab
- Format: MP3, AAC, WAV, FLAC, ...
  Audio codec selection gets disabled

Not entirely sure if there are cases with audio formats where you need to be able to specify both, the container and the codec. If so, then it would need to be more like:
- Format: MP3 etc. (referring to the container)
  Codec selection in the Audio tab

Independent of that, we should also:
- Disable (and untick?) the Export Video checkbox if an audio format is selected
- Tick the Export Audio option (and disable it, so that it cannot be toggled off?)

**Comment by itsmattkc** [comment] 2021-04-22 08:54
I agree this is a valid issue, but I maintain it's a duplicate of #1345

**Closed by itsmattkc** 2021-04-22 08:54 UTC
Labels: Audio, Export
