### ISSUE TITLE
Audio waveform isn't correct

### ISSUE THREAD

**Issue by NathanSalapat** [olive-editor/olive#477] opened 2019-02-11 04:01 UTC
![olive-waveform](https://user-images.githubusercontent.com/8930456/52545696-0e912300-2d7f-11e9-8fd0-afa4ebd622d2.png)
Both of these clips are the exact same audio, one in .wav and one in .ogg format. the waveform of the .wav  clip is synced with the audio playback. This seems to be an issue with any .ogg file. When editing video the imported audio from the video looks fine. I usually import the audio into Audacity and run a few filters on it and then export and use that audio in the video.

**Comment by itsmattkc** [comment] 2019-02-11 04:22
You'll probably need to send me both of these files so I can diagnose this issue.

**Comment by alcomposer** [comment] 2019-02-11 04:43
I made a 3 frame audio tone in Olive, rendered it as Wav & Ogg, when I bring them both back into Olive, here is the difference I get in timing:
![audio_issue](https://user-images.githubusercontent.com/12004932/52546446-3d56da00-2e0f-11e9-8118-8b06bc299af4.png)
I looks like the waveform of the Ogg is 1 frame too long, and the Wav is a bit short. However it does seem like the audio playback is correct, only the display is out.

**Comment by itsmattkc** [comment] 2019-02-11 11:28
This should be fixed in the latest commit. You may have to clear your current waveform cache (Tools > Preferences > General > Delete Previews), but they should be correct now. This was caused by slightly inaccurate waveform generation exacerbated by Ogg's usage of variable frame sizes.

**Closed by itsmattkc** 2019-02-11 11:28 UTC
