### ISSUE TITLE
New SVG icons not shown on buttons

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#569] opened 2019-02-28 15:39 UTC
Olive version: `edea300` (AppImage)

OS/Platform: *Debian 9.x* (x86_64)

![pic.1](https://i.imgur.com/jKO1B8g.png)

**Comment by itsmattkc** [comment] 2019-02-28 19:43
Duplicate of #567, fixed in 5b9c389efc286186684e259a4732ac4fb57d6cc7

**Closed by itsmattkc** 2019-02-28 19:43 UTC
Labels: packaging
