### ISSUE TITLE
[FEATURE] [AUDIO] Add audio plug-in support

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#2066] opened 2022-10-14 12:53 UTC
The best way to provide flexible audio processing in Olive would be to add support for audio plug-ins.

VST2 plug-in support was present in 0.1x albeit quite flaky.

Doing this properly would require a lot of work, but because Olive is FOSS, there's a better way:

Carla is a plug-in host that could be used internaly as a bridge between Olive and various audio plug-in formats, leaving the hard stuff to it, while having a uniform interface on Olive's side.

Carla can load VST2/3, LV2, CLAP and other plug-in formats, so Olive just needs to care about Carla, and all the rest is handled by it.

I believe this is exactly how it's done in Zrythm, an upcoming FOSS DAW.

I imagine we'd need an **Audio Plug-in** node that would allow loading audio plug-ins through Carla, and exposing controllable parameters as node inputs. Some plug-ins may also have a sidechain audio input, though that's not top priority.

Being able to load plug-ins and animate their parameters would already be a massive leap forward allowing proper audio processing in Olive with minimal effort.

Reimplementing various effects is wholly unnecessary, when there's so many open-source plug-in that could be jut shipped as stock instead.

Ardour has a nice suite of stock plug-ins providing simple Filters, EQ, Compression, Reverb and Delay effects that would be perfect as a basic toolset.

**Comment by AGI-THB** [comment] 2022-10-14 13:37
#1342

**Comment by unfa** [comment] 2022-10-14 14:00
Oh, thanks for bringing this up. I searched for these but "VST" wasn't on my mind.
Plus audio-plug-ins means much more than "VST" :)

**Comment by psemiletov** [comment] 2022-10-14 19:22
Maybe making LV2 or VST support is simplier than some sort of Carla interconnection? Carla itself exports any loaded plugin as LV2, so Olive need LV2 support first.

**Comment by itsmattkc** [comment] 2022-10-16 06:38
Duplicate of #1342

**Closed by itsmattkc** 2022-10-16 06:38 UTC
Labels: User Interface, Triage
