### ISSUE TITLE
[EXPORT] Color Shifting after Export

### ISSUE THREAD

**Issue by ZERICO2005** [olive-editor/olive#1966] opened 2022-07-11 18:04 UTC
**Commit Hash** 
a8d46c4c

**Platform** 
Windows 10 21H2 (r7 3800x, 3070)

**Summary**
Whenever I export a video in Olive 0.2, the colors get shifted by a lot. For example the color 229,24,24 would be shown as 228,24,24 in the preview window, but then the exported video would randomly shift to 247,43,21 changing from a Red color to a Orange color. (Exporting with default settings with no effects (sRGB OETF) and I tried with linear color to no avail).

**Additional Information / Output**
This issue has happened on every version of Olive 0.2 I have used along with Olive 0.1. It appears to happen on different hardware as my old R5 2500x, 1050ti PC (Running Olive 0.1) had the same color shifting. Other than the color shift the video plays fine in VLC and YouTube without corruption.

Left: 228,24,24
Right: 247,43,21
![Compare](https://user-images.githubusercontent.com/71151164/178328475-6d5a7a3e-57a4-4a0a-b334-d24327ac12ed.png)

//I forgot to put the Title, it would have been "Color Shifting after Export"

**Comment by itsmattkc** [comment] 2022-07-20 19:44
I think what's happening here is a YUV color range issue. We might not be encoding the correct YUV mode into the file. Worth investigating further.

**Comment by sobotka** [comment] 2022-07-21 02:45
This can easily be a player problem, as most of them are often crap at honouring atoms such as NCLC etc.

**Comment by ZERICO2005** [comment] 2022-07-21 06:15
> This can easily be a player problem, as most of them are often crap at honouring atoms such as NCLC etc.

Playing the video in VLC, uploading the video to YouTube, and viewing the video in the Olive video editor show the same shifted color.

**Comment by itsmattkc** [comment] 2022-07-21 07:55
I've spent some time on this and there seem to be a few things at play here. Firstly, I've ensured YUV ranges are handled correctly in export in 187568324aa782987cc6fd43dcf0584ab3ecb782. Decoding was already correct (minus a manual override: #1354), but indeed we had a metadata issue when encoding, which has now been resolved. You can even configure the YUV range you want to export to in the UI, and the pixels/metadata will be correct in the resulting file.

However there's a second issue, which is that most players seem to assume video is in Rec. 709, at least without metadata specifying otherwise, while Olive by default exports to sRGB. While these colorspaces are very similar, their gammas/transfer functions are slightly different, leading to color shift. This is a complicated issue, because @sobotka is 100% right that players are very inconsistent with things like this. While we could write metadata specifying sRGB into the file, Olive supports a wide variety of colorspaces outside of sRGB through OCIO, for which most players are unlikely to be compatible with. Additionally, in my testing, a lot of players simply ignored the metadata and continued to assume Rec. 709. Some players (notably VLC and Adobe software) didn't even respond to the YUV color range metadata. The only players I found that could consistently handle these correctly were QuickTime, FFplay, and Olive.

In theory this isn't a flaw as much as it is a difference in assumptions, but for compatibility it may make sense to add a Rec. 709 output and default to it, since most of the existing infrastructure appears to be based around that assumption.

**Comment by sobotka** [comment] 2022-07-21 14:48
BT.709 with appropriate `nclc` etc. tags is 100% the most appropriate default. [This](https://vimeo.com/349868875) video is a very solid brief dive into some of the atoms.

**Comment by itsmattkc** [comment] 2022-07-21 16:28
Do we have a BT.709 colorspace in the config? Glancing through the YAML, BT.1886 EOTF seems like the most appropriate thing but I couldn't say with confidence.

![image](https://user-images.githubusercontent.com/34096995/180264250-9a1c14e1-2e4d-4125-b904-b2cf4adfff4f.png)

**Comment by sobotka** [comment] 2022-07-21 18:39
Shorter answer is “No there is not”. It is not included because the encoding discrepancy seems to be somewhat anachronistic, except in this specific case covered in this thread. Rather easy to add. I suspect @ThomasWilshaw could provide the basic transform, with care and caution applied to considering the broadcast range scaling for delivery.

I suspect it opens a can of worms if included in the configuration however. Perhaps including it in the configuration and not exposing it to the authors could work.

A bit of historical vantage…

The BT.709 OETF is arguably a legacy construct; it was designed to be paired with the latter designed BT.1886 specification. This pairing has an implicit discrepancy, where the encoding is decoded with a unique distortion. The magic between the two essentially performed an appearance-like adjustment for dark viewing of the BT.709 OETF encoding.

Within the sRGB specification annex, there is a discussion where the sRGB reference EOTF (pure 2.2 exponent applied to the encoded values) can be used for direct viewing of BT.709 OETF encoded values for a dim viewing context. Here, the unique discrepancy forms an appearance adjustment again, more appropriate to the dim conditions.

We could make a case that in a DCC authoring environment, the application should be responsible for handling this appearance difference encoding based on set viewing condition assumptions. Hence leaning on the discrepancy (historical phrase “system gamma”) seems extremely problematic in the context of our current era.

**Comment by ThomasWilshaw** [comment] 2022-07-21 20:19
@sobotka Am I right in thinking we'd have to run our linear data through the Rec.709 OETF and then the BT.1886 EOTF?

And would we then scale the output of that based on full/legal range?

Or have I got completely the wrong end of the stick?

**Comment by sobotka** [comment] 2022-07-21 20:22
This is where I’d consider that appearance models can help get us over the hump to more appropriate outputs.

The encoding for most YCbCr streams is often about scaling to broadcast range, tracking the primaries etc, and setting appropriate atoms in the endless stream of wrappers, and praying they are honoured properly in the decoding.

**Comment by itsmattkc** [comment] 2022-08-08 06:20
Mostly fixed in b39e5028dd518045025c60992ec6525fa11cdf39.

**Closed by itsmattkc** 2022-08-08 06:20 UTC
Labels: High Priority, Export
