### ISSUE TITLE
[EDIT] Audio Displaying 0dB

### ISSUE THREAD

**Issue by SamuraiDestroy** [olive-editor/olive#2150] opened 2023-01-16 10:57 UTC
**Commit Hash** af76fbf0

**Platform** Windows 10

**Summary** When looking at the volume in audio nodes, it will always display as 0dB

**Additional Information / Output** The audio still plays though, it's just a visual bug.

**Comment by itsmattkc** [comment] 2023-01-16 16:40
Duplicate of #2059

**Closed by itsmattkc** 2023-01-16 16:40 UTC
Labels: Timeline/Editing, Triage
