### ISSUE TITLE
[EXPORT]  H.264 Codec -  "Failed to open file: Failed to find codec for 1"

### ISSUE THREAD

**Issue by blueyes80m** [olive-editor/olive#1793] opened 2021-11-16 11:22 UTC
**Commit Hash** 
8befda8d 

**Platform** 
Windows 10

**Summary**
I cannot export a file in Video MPEG-4 with H.264 codec (error "Failed to open file: Failed to find codec for 1").
It worked if I select H.265.

https://user-images.githubusercontent.com/65186257/141976171-ab809989-ffad-46b7-a4cc-538a97239af1.mp4

**Additional Information / Output**
I'm using the portable version.

**Comment by ThomasWilshaw** [comment] 2021-11-16 14:40
I can confirm this on my end as well. @itsmattkc  I wonder if the nightly builds aren't installing the `libx264` libraries needed for `ffmpeg`?

**Comment by ThomasWilshaw** [comment] 2021-11-16 14:44
For Windows at least you'd need `vcpkg install ffmpeg[x264]`

**Comment by itsmattkc** [comment] 2021-11-17 20:05
So this was genuinely confounding for me because this had been addressed and confirmed working literally only three weeks ago (#1778). How could it have broken again?

It appears vcpkg has introduced a bug that has broken FFmpeg's ability to compile with x264. I've made a bug report with them (microsoft/vcpkg#21499) and will patch our dependency system to fix it in the mean time.

**Comment by ThomasWilshaw** [comment] 2021-11-17 21:29
Sorry, I hadn't seen that previous issue, that's really weird.

**Comment by itsmattkc** [comment] 2021-11-18 17:37
Fixed by patching our dependency system, hopefully vcpkg will fix this soon too.

**Closed by itsmattkc** 2021-11-18 17:37 UTC
Labels: Export
