### ISSUE TITLE
[Feature request] Mute/hide tracks

### ISSUE THREAD

**Issue by qubodup** [olive-editor/olive#775] opened 2019-04-08 16:03 UTC
It'd be nice to be able to mute (edit: and solo*) and/or hide tracks at a time (affecting both preview and export).

Most important use case would be when clips on v2 track lead to massive slowdown (for example cool overlays on weak machines) and v1 track is sufficient to check the project.

Another use case: checking a1 voice commentary for mistakes/unpleasant sounds after having added multiple music clips to a2 track for bgm.

*soloing a track after finishing cutting and adding music happens to be something I do once per project to export voice audio as an audiofile, so I can edit it externally.

**Comment by AGI-THB** [comment] 2019-04-08 16:12
#420

**Comment by itsmattkc** [comment] 2019-04-08 22:49
Duplicate of #420

**Closed by itsmattkc** 2019-04-08 22:49 UTC
