### ISSUE TITLE
Feature Request: Multicam Automatic Sync by Sound

### ISSUE THREAD

**Issue by frink** [olive-editor/olive#589] opened 2019-03-03 19:04 UTC
In the case of multi-angle shots - which are becoming a common process for everything from wedding videos to TV serials to music videos - the time consuming process of synchronizing video content to begin switching angles is increasingly annoying. Most pro and prosumer video editors (Lightworks, Avid, Davinci Resolve, Hitfilms, Adobe Premier, Kdenlive) have a way to automatically sync and in some cases rough cut a multi-cam scene. With cameras continuing to drop in price we can expect this trend for more angles shot simultaneously to increase. We need to make sure this is on our roadmap as well or many use cases for pro video will be missed...

**Comment by itsmattkc** [comment] 2019-03-03 19:29
This sounds like a duplicate of #365

**Comment by frink** [comment] 2019-03-04 07:03
Yes. It is...

**Comment by frink** [comment] 2019-03-04 07:03
Duplicate of #365

**Closed** 2019-03-04 07:34 UTC
