### ISSUE TITLE
[PLAYBACK] No video preview

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1886] opened 2022-03-23 21:40 UTC
**Commit Hash** 
a4056d84

**Platform** 
macOS 12.2.1

**Summary**
In last build the video output is gone, I guess it has something to do with openGL:
<img width="851" alt="Captura de pantalla 2022-03-23 a las 22 38 06" src="https://user-images.githubusercontent.com/5942369/159800226-4268b559-4be0-4e97-bc5d-de5bb62ea8e1.png">

Previous build, cdf9efa7, works fine.

**Additional Information / Output**
this is the log I get:
```
[DEBUG] Extracting default OCIO config to "/Users/pablo/Library/Caches/olivevideoeditor.org/Olive/ocioconf" ((null):0)
[WARNING] Failed to compile OpenGL shader ((null):0)
ERROR: 0:13: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:14: Use of undeclared identifier 'color'

#version 150

precision highp float;

// Input texture
uniform sampler2D ove_maintex;

// Input texture coordinate
in vec2 ove_texcoord;
out vec4 frag_color;

void main() {
    vec4 color = texture2D(ove_maintex, ove_texcoord);
    frag_color = color;
}

[INFO] Using Qt version: 5.15.2 ((null):0)
[INFO] Setting output audio device to Built-in Output ((null):0)
[INFO] Setting input audio device to Built-in Microphone ((null):0)
[WARNING] Failed to compile OpenGL shader ((null):0)
ERROR: 0:25: Invalid call of undeclared identifier 'texture2D'

#version 150

precision highp float;

uniform sampler2D ove_maintex;

uniform vec2 viewport;
uniform vec3 luma_coeffs;

uniform float waveform_scale;

in vec2 ove_texcoord;
out vec4 frag_color;

void main(void) {
    float waveform_height = ceil(waveform_scale * viewport.y);
    float quantisation = 1.0 / (waveform_height - 1.0);
    float intensity = 0.10;
    vec4 col = vec4(0.0);
    vec4 cur_col = vec4(0.0);
    float ratio = 0.0;

    for (int i = 0; float(i) < waveform_height; i++) {
        ratio = float(i) / float(waveform_height - 1.0);
        cur_col.rgb = texture2D(
            ove_maintex,
            vec2(ove_texcoord.x, ratio)
        ).rgb;

        cur_col.w = dot(cur_col.rgb, luma_coeffs);

        col += (
            step(vec4(ove_texcoord.y - quantisation), cur_col) *
            step(cur_col, vec4(ove_texcoord.y + quantisation)) *
            intensity) +
            (step(1.0 - quantisation, ove_texcoord.y) *
            step(vec4(1.0 - quantisation), cur_col) * intensity);
    }

    col.rgb += vec3(col.w);
    frag_color = vec4(col.rgb, 1.0);
}

[WARNING] Tried to allocate sample buffer with zero sample count ((null):0)
[WARNING] Tried to fill an unallocated sample buffer ((null):0)
[WARNING] Failed to compile OpenGL shader ((null):0)
ERROR: 0:93: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:97: Use of undeclared identifier 'col'
ERROR: 0:97: Use of undeclared identifier 'col'
ERROR: 0:101: Use of undeclared identifier 'col'
ERROR: 0:101: Use of undeclared identifier 'col'
ERROR: 0:105: Use of undeclared identifier 'col'
ERROR: 0:105: Use of undeclared identifier 'col'
ERROR: 0:107: Use of undeclared identifier 'col'
ERROR: 0:107: Use of undeclared identifier 'col'
ERROR: 0:110: Use of undeclared identifier 'col'

#version 150

precision highp float;

// Main texture input
uniform sampler2D ove_maintex;
uniform int ove_maintex_alpha;
uniform mat4 ove_cropmatrix;

// Macros defining `ove_maintex_alpha` state
// Matches `AlphaAssociated` C++ enum
#define ALPHA_NONE     0
#define ALPHA_UNASSOC  1
#define ALPHA_ASSOC    2

// Main texture coordinate
in vec2 ove_texcoord;
out vec4 frag_color;

// Program will replace this with OCIO's auto-generated shader code

// Declaration of all variables

uniform sampler2D ocio_lut1d_0Sampler;

// Declaration of all helper methods

vec2 ocio_lut1d_0_computePos(float f)
{
  float dep;
  float abs_f = abs(f);
  if (abs_f > 6.10351562e-05)
  {
    vec3 fComp = vec3(15., 15., 15.);
    float absarr = min( abs_f, 65504.);
    fComp.x = floor( log2( absarr ) );
    float lower = pow( 2.0, fComp.x );
    fComp.y = ( absarr - lower ) / lower;
    vec3 scale = vec3(1024., 1024., 1024.);
    dep = dot( fComp, scale );
  }
  else
  {
    dep = abs_f * 1023.0 / 6.09755516e-05;
  }
  dep += step(f, 0.0) * 32768.0;
  vec2 retVal;
  retVal.y = floor(dep / 4095.);
  retVal.x = dep - retVal.y * 4095.;
  retVal.x = (retVal.x + 0.5) / 4096.;
  retVal.y = (retVal.y + 0.5) / 17.;
  return retVal;
}

// Declaration of the OCIO shader function

vec4 OCIODisplay(vec4 inPixel)
{
  vec4 outColor = inPixel;
  
  // Add LUT 1D processing for ocio_lut1d_0
  
  {
    outColor.r = texture(ocio_lut1d_0Sampler, ocio_lut1d_0_computePos(outColor.r)).r;
    outColor.g = texture(ocio_lut1d_0Sampler, ocio_lut1d_0_computePos(outColor.g)).r;
    outColor.b = texture(ocio_lut1d_0Sampler, ocio_lut1d_0_computePos(outColor.b)).r;
  }

  return outColor;
}


// Alpha association functions
vec4 assoc(vec4 c) {
  return vec4(c.rgb * c.a, c.a);
}

vec4 reassoc(vec4 c) {
  return (c.a == 0.0) ? c : assoc(c);
}

vec4 deassoc(vec4 c) {
  return (c.a == 0.0) ? c : vec4(c.rgb / c.a, c.a);
}

void main() {
  vec2 cropped_coord = (vec4(ove_texcoord-vec2(0.5, 0.5), 0.0, 1.0)*ove_cropmatrix).xy + vec2(0.5, 0.5);
  if (cropped_coord.x < 0.0 || cropped_coord.x >= 1.0 || cropped_coord.y < 0.0 || cropped_coord.y >= 1.0) {
    frag_color = vec4(0.0);
    return;
  }

  vec4 col = texture2D(ove_maintex, cropped_coord);

  // If alpha is associated, de-associate now
  if (ove_maintex_alpha == ALPHA_ASSOC) {
    col = deassoc(col);
  }

  // Perform color conversion
  col = OCIODisplay(col);

  // Associate or re-associate here
  if (ove_maintex_alpha == ALPHA_ASSOC) {
    col = reassoc(col);
  } else if (ove_maintex_alpha == ALPHA_UNASSOC) {
    col = assoc(col);
  }

  frag_color = col;
}

[DEBUG] Blit entered with 1281 ((null):0)
[DEBUG] Blit exited with 1282 ((null):0)
[DEBUG] AttachTextureAsDestination entered with 1281 ((null):0)
[DEBUG] Blit exited with 1282 ((null):0)
[DEBUG] Blit entered with 1281 ((null):0)
[DEBUG] Blit exited with 1282 ((null):0)
[DEBUG] AttachTextureAsDestination entered with 1281 ((null):0)
[DEBUG] Blit exited with 1282 ((null):0)
```

**Comment by ThomasWilshaw** [comment] 2022-03-23 21:54
Looks like we missed some of the shaders in the update.

**Comment by itsmattkc** [comment] 2022-03-24 03:38
macOS once again being the most stringent with OpenGL. I could have sworn I tested this, but I must have forgotten.

**Comment by GUY-BBS** [comment] 2022-03-24 16:05
I have the same problem on Windows 10.  I have tested it on two different computers with the same result.

**Comment by ThomasWilshaw** [comment] 2022-03-24 17:27
Should be fixed in the latest master

**Comment by itsmattkc** [comment] 2022-03-24 17:35
> I have the same problem on Windows 10. I have tested it on two different computers with the same result.

I assume you're using Intel GPUs? They can also be pretty picky, but I've confirmed the latest commit fixes this on those.

Haven't tested macOS yet, but I think it should be fixed there too.

**Comment by itsmattkc** [comment] 2022-03-24 21:21
Can confirm this is fixed on macOS too. Closing.

**Closed by itsmattkc** 2022-03-24 21:21 UTC
Labels: Playback, Triage
