### ISSUE TITLE
[EDIT] UI hangs for several seconds after a ripple delete

### ISSUE THREAD

**Issue by morrolinux** [olive-editor/olive#1508] opened 2021-03-06 19:35 UTC
**Commit Hash** 
a57bf35e

**Platform** 
Manjaro

**Summary**
After splitting a track in half and ripple-deleting the left side, the right one will immediately jump in its place as it's supposed to, but the UI will be unresponsive for about 10 seconds.
The UI also hangs the same way each time I drag a track onto the timeline.

![Peek 06-03-2021 20-28](https://user-images.githubusercontent.com/20294254/110218550-9abc9880-7eba-11eb-9b71-b575d2f8d688.gif)

Nothing's being logged on the shell except for 
`[DEBUG] Stub ((null):0)`
repeated several times

**Additional Information / Output**

System specs:

CPU: AMD Ryzen 9 3900X (24 threads) @ 3.800GHz
GPU: AMD ATI Radeon RX 570
OS: Manjaro Linux x86_64
Host: X570 AORUS MASTER -CF
Kernel: 5.10.7-3-MANJARO

**Comment by itsmattkc** [comment] 2021-03-10 04:30
Duplicate of #1430

**Closed by itsmattkc** 2021-03-10 04:30 UTC
Labels: Timeline/Editing, Triage
