### ISSUE TITLE
[BUILD] Adding olive to apt

### ISSUE THREAD

**Issue by Berksen** [olive-editor/olive#1502] opened 2021-02-28 14:35 UTC
**Linux Pop-os 20_10** 

**Adding PPA to apt**

Output: **ERROR: ppa 'olive-editor/olive-editor' not found (use --login if private)**

Followed first step of the linux [install page](https://www.olivevideoeditor.org/linux.php)

**Comment by elsandosgrande** [comment] 2021-02-28 14:44
Duplicate of #1292.

@Simran-B @itsmattkc I overlooked this the first time around (:sweat_smile:), but the instructions for 0.1 seem to be quite old, not to mention that the PPA appears to be official if we go off of the web site alone, since it is above the “Unofficial” section.

**Comment by elsandosgrande** [comment] 2021-02-28 14:46
Duplicate of #1292

**Closed** 2021-02-28 15:12 UTC
Labels: Building/Packaging

**Comment by Simran-B** [comment] 2021-02-28 15:36
That page should certainly be removed. How did you find it?

The only official form of distribution is via AppImages. There's no point in additional options as long as it's experimental software.

**Comment by elsandosgrande** [comment] 2021-02-28 15:42
> […] How did you find it?

@Simran-B
![image](https://user-images.githubusercontent.com/40576902/109424442-e74c3380-79e3-11eb-890e-ef8758a8890d.png)

**Comment by jlrigdon** [comment] 2021-06-07 19:09
adafg
