### ISSUE TITLE
[NODES] Cannot reconnect clip to track

### ISSUE THREAD

**Issue by mcDandy** [olive-editor/olive#1659] opened 2021-07-01 15:00 UTC
**Commit Hash**  08e2fa4d

**Platform**  Windows 11 pro (exact version: 22000.51)

**Summary** When I connect clip to track after disconnecting it, it will not be connected as list entry, but as source of the list and not show on track.

**Additional Information / Output**
Before:
![2021-07-01 (3)](https://user-images.githubusercontent.com/18588943/124145369-05f33180-da8d-11eb-9779-678f7550d96d.png)

After:
![2021-07-01 (4)](https://user-images.githubusercontent.com/18588943/124145423-12778a00-da8d-11eb-91c1-180129a8fec3.png)

**Comment by itsmattkc** [comment] 2021-07-02 04:27
Duplicate of #1353

**Closed by itsmattkc** 2021-07-02 04:27 UTC
Labels: Nodes/Compositing, Triage
