### ISSUE TITLE
[EDIT] Play always same audio

### ISSUE THREAD

**Issue by klwemu** [olive-editor/olive#1211] opened 2020-09-21 19:56 UTC
**Commit Hash (8 character string of letters/numbers in title bar)**
871bc08

**Platform**
W10

**Summary**
Start new Project, insert a clip - play it. Audio is from a different clip which is not part of the project.
If I remove the audio track from the clip, false audio is still available and played. (Disc cache is cleared in prefs)

**Additional Information / Output**

**Comment by itsmattkc** [comment] 2020-09-24 14:01
Can you elaborate on this? Where is the audio that you're hearing from?

**Comment by klwemu** [comment] 2020-09-24 18:06
No, I am sorry. I reinstalled the app and then it was okay.
*(the audio was from a different clip - not part of the current project and
it was played even when I deleted all audio in the current project. Very
strange.)*

>

**Comment by klwemu** [comment] 2020-09-24 21:53
Hello, It happens again (now with Version: 21412c5e).

The audio file I hear is one I had opened some time before, and the audio I
hear is not always the same. Nothing changes when I load different clips or
restart the app.

Check out my screenshot (I hope you can see it):
[image: image.png]
There is no video and no audio at the current location in the timeline, but
audio is played - from a different clip which is not part of the project.
For me it looks like a cache problem.

Debug from console:
[image: image.png]

**Comment by Simran-B** [comment] 2020-09-24 22:53
@klwemu GitHub doesn't support image attachments in reply emails. Please upload them on the website. A screen recording would also be helpful.

**Comment by klwemu** [comment] 2020-09-25 07:43
![False Audio](https://user-images.githubusercontent.com/3965097/94240058-ff8ac480-ff12-11ea-9bfe-f9d50ee5465e.png)

ScreenRecording is nothing special in this case.  I click on play and I can hear (non existing) audio.

![False Audio Debug](https://user-images.githubusercontent.com/3965097/94240364-7b850c80-ff13-11ea-9c10-3e5ccde75c39.png)

**Comment by bobbyonbisq** [comment] 2020-10-03 19:49
I just started to work with Olive for the first time, and I have the same problem.
No matter what audiofiles I import... they always play as the first imported... restarting program, with new projectfile... everything does not help.
![debugbildchen](https://user-images.githubusercontent.com/63121369/95000565-5868f580-05c2-11eb-9c8c-789eb87b4d9b.JPG)

**Comment by ThomasWilshaw** [comment] 2020-10-03 19:59
There should be some PCM files in either the same folder as Olive, or it's cache directory. Try deleting them and see if that helps.

**Comment by bobbyonbisq** [comment] 2020-10-04 09:31
Hi, I have the same problem. Olive will playback one first audio clip only and not update when others are added but playing only this one, even if not existing in the project anymore. I am searching for a workaround still this gets fixed.

**Comment by bobbyonbisq** [comment] 2020-10-04 10:29
Thank you very much that helped (deleting PCM files in the application-folder.
Olive writes PCM files in the project-directory now (had not been there before). They revealed to be necessary, so I leave them there.  I changed location for Cache now (away from System disk C:  )... nonetheless there are still big files not deleted in the old cache location... I didnt dare to delete them... 2 folders : "cache" and "mediacache"... still needed by olive?

**Comment by itsmattkc** [comment] 2020-10-04 10:35
As long as Olive is closed, there's no danger to deleting the `mediacache` folders.

I think this issue should be merged into #1248 since that seems to be the root cause.

**Closed by itsmattkc** 2020-10-04 10:35 UTC
Labels: Timeline/Editing, Triage
