### ISSUE TITLE
[CRASH] Olive stops responding frequently.

### ISSUE THREAD

**Issue by SamuraiDestroy** [olive-editor/olive#2210] opened 2023-04-02 10:35 UTC
**Commit Hash** 5626e6ae

**Platform** Windows 10

**Summary**
Randomly Olive will stop responding and crash.

**Steps to Reproduce**

It seems to happen when I use playback for too long.

<details><summary><strong>Crash Report</strong></summary><pre><code>

I do not recieve a crash report. 

</code></pre></details>

**Additional Information**
When it stops responding, it will ask me if I want to close it or if I want to wait for it to respond.

**Comment by itsmattkc** [comment] 2023-04-03 21:25
Duplicate of #2184

**Closed by itsmattkc** 2023-04-03 21:25 UTC
Labels: Crash, Triage
