### ISSUE TITLE
[BUILD] Cannot build latest 0.2 release

### ISSUE THREAD

**Issue by SnazzHazLazz** [olive-editor/olive#1801] opened 2021-12-03 21:55 UTC
**Commit Hash** 

**Platform**  
Manjaro Linux w/ 5.14.18-1-MANJARO kernel

**Summary**
I'm trying to compile the latest 0.2 release on my desktop following the instructions [here](https://www.olivevideoeditor.org/compile.php#arch). I've installed the dependencies listed and looked for similar issues to no avail. I'm really not that great at reading make/cmake errors, so I have no idea what's going on here.

**Additional Information / Output**
[  1%] Automatic MOC and UIC for target olive-editor
[  1%] Built target olive-editor_autogen
[  1%] Automatic MOC and UIC for target libolive-editor
[  1%] Built target libolive-editor_autogen
[  1%] Generating zh_TW.qm
Updating '/home/user/.programs/olive/build/app/zh_TW.qm'...
    Generated 247 translation(s) (0 finished and 247 unfinished)
    Ignored 611 untranslated source text(s)
[  2%] Generating ar_AR.qm
Updating '/home/user/.programs/olive/build/app/ar_AR.qm'...
    Generated 255 translation(s) (0 finished and 255 unfinished)
    Ignored 603 untranslated source text(s)
[  2%] Generating bs_BA.qm
Updating '/home/user/.programs/olive/build/app/bs_BA.qm'...
    Generated 66 translation(s) (14 finished and 52 unfinished)
    Ignored 793 untranslated source text(s)
[  2%] Generating cs_CZ.qm
Updating '/home/user/.programs/olive/build/app/cs_CZ.qm'...
    Generated 923 translation(s) (923 finished and 0 unfinished)
[  3%] Generating de_DE.qm
Updating '/home/user/.programs/olive/build/app/de_DE.qm'...
    Generated 989 translation(s) (989 finished and 0 unfinished)
[  3%] Generating en_US.qm
Updating '/home/user/.programs/olive/build/app/en_US.qm'...
    Generated 5 translation(s) (5 finished and 0 unfinished)
[  3%] Generating es_ES.qm
Updating '/home/user/.programs/olive/build/app/es_ES.qm'...
    Generated 880 translation(s) (880 finished and 0 unfinished)
[  3%] Generating fr_FR.qm
Updating '/home/user/.programs/olive/build/app/fr_FR.qm'...
    Generated 447 translation(s) (389 finished and 58 unfinished)
    Ignored 433 untranslated source text(s)
[  4%] Generating id_ID.qm
Updating '/home/user/.programs/olive/build/app/id_ID.qm'...
    Generated 232 translation(s) (0 finished and 232 unfinished)
    Ignored 626 untranslated source text(s)
[  4%] Generating it_IT.qm
Updating '/home/user/.programs/olive/build/app/it_IT.qm'...
    Generated 602 translation(s) (595 finished and 7 unfinished)
    Ignored 387 untranslated source text(s)
[  4%] Generating ja_JP.qm
Updating '/home/user/.programs/olive/build/app/ja_JP.qm'...
    Generated 985 translation(s) (985 finished and 0 unfinished)
[  4%] Automatic RCC for ui/cursors/cursors.qrc
[  5%] Generating ru_RU.qm
Updating '/home/user/.programs/olive/build/app/ru_RU.qm'...
    Generated 867 translation(s) (857 finished and 10 unfinished)
    Ignored 143 untranslated source text(s)
[  6%] Generating zh_CN.qm
Updating '/home/user/.programs/olive/build/app/zh_CN.qm'...
    Generated 856 translation(s) (856 finished and 0 unfinished)
    Ignored 2 untranslated source text(s)
[  6%] Generating uk_UK.qm
Updating '/home/user/.programs/olive/build/app/uk_UK.qm'...
    Generated 270 translation(s) (0 finished and 270 unfinished)
    Ignored 588 untranslated source text(s)
[  6%] Generating sr_RS.qm
Updating '/home/user/.programs/olive/build/app/sr_RS.qm'...
    Generated 65 translation(s) (14 finished and 51 unfinished)
    Ignored 794 untranslated source text(s)
[  6%] Generating pt_BR.qm
Updating '/home/user/.programs/olive/build/app/pt_BR.qm'...
    Generated 304 translation(s) (0 finished and 304 unfinished)
    Ignored 554 untranslated source text(s)
[  6%] Generating tr_TR.qm
Updating '/home/user/.programs/olive/build/app/tr_TR.qm'...
    Generated 240 translation(s) (0 finished and 240 unfinished)
    Ignored 618 untranslated source text(s)
[  6%] Automatic RCC for ts/translations.qrc
[  6%] Automatic RCC for shaders/shaders.qrc
[  6%] Automatic RCC for ui/style/olive-dark/olive-dark.qrc
[  6%] Automatic RCC for render/ocioconf/ocioconf.qrc
[  6%] Automatic RCC for ui/style/olive-light/olive-light.qrc
[  7%] Automatic RCC for ui/graphics/graphics.qrc
[  7%] Building CXX object app/CMakeFiles/libolive-editor.dir/libolive-editor_autogen/mocs_compilation.cpp.o
[  8%] Building CXX object app/CMakeFiles/libolive-editor.dir/core.cpp.o
[  8%] Building CXX object app/CMakeFiles/libolive-editor.dir/audio/audiomanager.cpp.o
[  8%] Building CXX object app/CMakeFiles/libolive-editor.dir/audio/audiovisualwaveform.cpp.o
[  8%] Building CXX object app/CMakeFiles/libolive-editor.dir/audio/packedprocessor.cpp.o
[  9%] Building CXX object app/CMakeFiles/libolive-editor.dir/audio/tempoprocessor.cpp.o
[  9%] Building CXX object app/CMakeFiles/libolive-editor.dir/cli/cliprogress/cliprogressdialog.cpp.o
[  9%] Building CXX object app/CMakeFiles/libolive-editor.dir/cli/clitask/clitaskdialog.cpp.o
[  9%] Building CXX object app/CMakeFiles/libolive-editor.dir/codec/ffmpeg/ffmpegdecoder.cpp.o
In member function ‘void QVector<T>::append(const T&) [with T = olive::AudioParams]’:
cc1plus: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
In file included from /usr/include/qt/QtCore/qbytearray.h:46,
                 from /usr/include/qt/QtCore/qstring.h:50,
                 from /usr/include/qt/QtCore/qobject.h:47,
                 from /usr/include/qt/QtCore/qtimer.h:48,
                 from /usr/include/qt/QtCore/QTimer:1,
                 from /home/user/.programs/olive/app/codec/ffmpeg/ffmpegdecoder.h:35,
                 from /home/user/.programs/olive/app/codec/ffmpeg/ffmpegdecoder.cpp:21:
/usr/include/qt/QtCore/qarraydata.h:129:8: note: at offset 24 into destination object ‘QTypedArrayData<olive::AudioParams>::<anonymous>’ of size 24
  129 | struct QTypedArrayData
      |        ^~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [app/CMakeFiles/libolive-editor.dir/build.make:869: app/CMakeFiles/libolive-editor.dir/codec/ffmpeg/ffmpegdecoder.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3093: app/CMakeFiles/libolive-editor.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by Simran-B** [comment] 2021-12-03 21:57
Duplicate of https://github.com/olive-editor/olive/issues/1590

**Closed by Simran-B** 2021-12-03 21:57 UTC
Labels: Building/Packaging, Triage
