### ISSUE TITLE
[CODEC] Unable to Import MKV Files

### ISSUE THREAD

**Issue by snakethewolf** [olive-editor/olive#1299] opened 2020-10-31 23:49 UTC
**Commit Hash** 
34cb7c96

**Platform**
Windows 10

**Summary**
Title's self explanatory, I'd say.

**Additional Information / Output**
I use mostly MKV (Matroska Multimedia Video) format for editing. As soon as I try to import it, the "import" window is stuck at 00:00:00 elapsed, 00:00:00 remaining. This is what the command lines say:

> [matroska,webm @ 000001d5eac33880] Could not find codec parameters for stream 3 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
>Consider increasing the value for the 'analyzeduration' and 'probesize' options

If I'm doing something wrong, let me know. I'm not used to posts like this--not a coder, just a video editor. Thanks for all the hard work.

**Comment by Simran-B** [comment] 2020-11-01 00:12
Can you share a piece of footage that exhibits the problem? How was it created? Is it supposed to have subtitles?

**Comment by yasharya2901** [comment] 2020-11-10 12:08
Yes, I also shared a mkv in Telegram which one user tried and took more than 30 minutes to import. And it also had subtitles. Here's the link - https://t.me/c/1475173194/1649

**Comment by yasharya2901** [comment] 2020-11-10 12:10
> Yes, I also shared a mkv in Telegram which one user tried and took more than 30 minutes to import. And it also had subtitles. Here's the link - https://t.me/c/1475173194/1649

Also, just to mention, I imported this clip in Kdenlive as well and it imported in just a minute. So, it is sure that the problem is with Olive somewhere.

**Comment by yasharya2901** [comment] 2020-11-10 12:15
> Yes, I also shared a mkv in Telegram which one user tried and took more than 30 minutes to import. And it also had subtitles. Here's the link - https://t.me/c/1475173194/1649

And this telegram link is the part of official Olive telegram channel.

**Comment by yasharya2901** [comment] 2020-11-16 14:31
Dear @Simran-B, please visit this issue again as I have provided a piece of video.

**Comment by Simran-B** [comment] 2020-11-16 14:46
It's pirated content. Closing until suitable footage is provided directly.

**Closed by Simran-B** 2020-11-16 14:46 UTC
Labels: Codec, Triage

**Comment by itsmattkc** [comment] 2020-11-20 07:15
I know this issue is already closed, but this bug has been fixed in 42506e0da098e12b4efcf627a15e260046d5b129
