### ISSUE TITLE
[CRASH] Segfault when opening project file

### ISSUE THREAD

**Issue by RiversideRocks** [olive-editor/olive#1466] opened 2021-01-17 00:55 UTC
**Commit Hash** 
19eabf28

**Platform** 
Linux Mint 20

**Summary**
Was working on a project, added a clip (~3 minutes long) and it crashed. I had saved, but every time I open the file it crashes.

**Steps to Reproduce**
- Add a large clip

File that caused the issue (had to upload to my own CDN as discord doesn't allow .ove files)

https://cdn.riverside.rocks/a/gazelle-abacus-whippoorwill.ove

<details><summary><strong>Backtrace</strong></summary><pre><code>

[WARNING] Trying to use locale "en_US" but couldn't find a translation for it ((null):0)
[DEBUG] Extracting default OCIO config to "/home/riversiderocks/.cache/olivevideoeditor.org/Olive/ocioconf" ((null):0)
[INFO] Using Qt version: 5.12.8 ((null):0)
[DEBUG] Using graphics driver: Intel ((null):0)
[INFO] Setting output audio device to "alsa_output.pci-0000_00_1f.3.analog-stereo" ((null):0)
[49047:49047:20210116,194937.676403:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.676859:ERROR process_reader_linux.cc:520] no module mappings 0x7f92634b0000
[49047:49047:20210116,194937.677071:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.677094:ERROR process_reader_linux.cc:520] no module mappings 0x7f9263398000
[49047:49047:20210116,194937.677279:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.677299:ERROR process_reader_linux.cc:520] no module mappings 0x7f92632da000
[49047:49047:20210116,194937.677494:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.677502:ERROR process_reader_linux.cc:520] no module mappings 0x7f926321e000
[49047:49047:20210116,194937.677548:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.677554:ERROR process_reader_linux.cc:520] no module mappings 0x7f926310a000
[49047:49047:20210116,194937.677727:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.677787:ERROR process_reader_linux.cc:520] no module mappings 0x7f92619e9000
[49047:49047:20210116,194937.677843:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.677902:ERROR process_reader_linux.cc:520] no module mappings 0x7f92616c1000
[49047:49047:20210116,194937.677999:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.678053:ERROR process_reader_linux.cc:520] no module mappings 0x7f9261635000
[49047:49047:20210116,194937.678115:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.678169:ERROR process_reader_linux.cc:520] no module mappings 0x7f9261580000
[49047:49047:20210116,194937.679133:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.679173:ERROR process_reader_linux.cc:520] no module mappings 0x7f925fea8000
[49047:49047:20210116,194937.679235:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.679247:ERROR process_reader_linux.cc:520] no module mappings 0x7f925fc88000
[49047:49047:20210116,194937.679307:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.679318:ERROR process_reader_linux.cc:520] no module mappings 0x7f925f5cc000
[49047:49047:20210116,194937.680300:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.680333:ERROR process_reader_linux.cc:520] no module mappings 0x7f925de9a000
[49047:49047:20210116,194937.680492:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.680502:ERROR process_reader_linux.cc:520] no module mappings 0x7f925d95c000
[49047:49047:20210116,194937.680554:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.680589:ERROR process_reader_linux.cc:520] no module mappings 0x7f925d8c8000
[49047:49047:20210116,194937.680683:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.680698:ERROR process_reader_linux.cc:520] no module mappings 0x7f925d84e000
[49047:49047:20210116,194937.680803:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.680812:ERROR process_reader_linux.cc:520] no module mappings 0x7f925d7b1000
[49047:49047:20210116,194937.680999:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.681014:ERROR process_reader_linux.cc:520] no module mappings 0x7f925d6aa000
[49047:49047:20210116,194937.681055:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.681062:ERROR process_reader_linux.cc:520] no module mappings 0x7f925d639000
[49047:49047:20210116,194937.681089:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.681094:ERROR process_reader_linux.cc:520] no module mappings 0x7f925d307000
[49047:49047:20210116,194937.681127:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.681133:ERROR process_reader_linux.cc:520] no module mappings 0x7f925cd92000
[49047:49047:20210116,194937.681245:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.681252:ERROR process_reader_linux.cc:520] no module mappings 0x7f925ca6f000
[49047:49047:20210116,194937.681751:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.681760:ERROR process_reader_linux.cc:520] no module mappings 0x7f925bb44000
[49047:49047:20210116,194937.681815:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.681821:ERROR process_reader_linux.cc:520] no module mappings 0x7f925bb15000
[49047:49047:20210116,194937.681849:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.681856:ERROR process_reader_linux.cc:520] no module mappings 0x7f925bb04000
[49047:49047:20210116,194937.681881:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.681897:ERROR process_reader_linux.cc:520] no module mappings 0x7f925bab9000
[49047:49047:20210116,194937.681943:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.681950:ERROR process_reader_linux.cc:520] no module mappings 0x7f925ba95000
[49047:49047:20210116,194937.681971:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.681976:ERROR process_reader_linux.cc:520] no module mappings 0x7f925ba80000
[49047:49047:20210116,194937.682568:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.682574:ERROR process_reader_linux.cc:520] no module mappings 0x7f925911a000
[49047:49047:20210116,194937.684054:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.684062:ERROR process_reader_linux.cc:520] no module mappings 0x7f92632d0000
[49047:49047:20210116,194937.684079:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.684084:ERROR process_reader_linux.cc:520] no module mappings 0x7f925586e000
[49047:49047:20210116,194937.684147:ERROR elf_image_reader.cc:492] ehdr out of range
[49047:49047:20210116,194937.684152:ERROR process_reader_linux.cc:520] no module mappings 0x7f925567a000
[49047:49047:20210116,194937.684463:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.684469:ERROR process_reader_linux.cc:520] no module mappings 0x7f92556ef000
[49047:49047:20210116,194937.684487:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.684492:ERROR process_reader_linux.cc:520] no module mappings 0x7f925453a000
[49047:49047:20210116,194937.685537:ERROR elf_image_reader.cc:622] no dynamic segment
[49047:49047:20210116,194937.685545:ERROR process_reader_linux.cc:520] no module mappings 0x7f924c4a7000
[49047:49047:20210116,194937.685562:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.685568:ERROR process_reader_linux.cc:520] no module mappings 0x7f924c49c000
[49047:49047:20210116,194937.685582:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.685588:ERROR process_reader_linux.cc:520] no module mappings 0x7f924c48e000
[49047:49047:20210116,194937.685602:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.685607:ERROR process_reader_linux.cc:520] no module mappings 0x7f924c482000
[49047:49047:20210116,194937.685621:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.685626:ERROR process_reader_linux.cc:520] no module mappings 0x7f924c474000
[49047:49047:20210116,194937.685679:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.685684:ERROR process_reader_linux.cc:520] no module mappings 0x7f924c1f2000
[49047:49047:20210116,194937.685698:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.685703:ERROR process_reader_linux.cc:520] no module mappings 0x7f924c1e9000
[49047:49047:20210116,194937.685717:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.685723:ERROR process_reader_linux.cc:520] no module mappings 0x7f924c1e0000
[49047:49047:20210116,194937.685737:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.685742:ERROR process_reader_linux.cc:520] no module mappings 0x7f924c1d4000
[49047:49047:20210116,194937.685756:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.685761:ERROR process_reader_linux.cc:520] no module mappings 0x7f924c1cb000
[49047:49047:20210116,194937.685775:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.685780:ERROR process_reader_linux.cc:520] no module mappings 0x7f924c144000
[49047:49047:20210116,194937.685838:ERROR elf_image_reader.cc:116] no preferred header address
[49047:49047:20210116,194937.685843:ERROR process_reader_linux.cc:520] no module mappings 0x7f923c029000
/tmp/.mount_Olive-wZI7Wo/usr/bin/olive-crashhandler: symbol lookup error: /tmp/.mount_Olive-wZI7Wo/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5: undefined symbol: _ZdlPvm, version Qt_5
Segmentation fault (core dumped)

</code></pre></details>

**Additional Information**

**Comment by sobotka** [comment] 2021-01-17 05:37
[Pretty sure this is the OpenColorIO locale issue](https://github.com/AcademySoftwareFoundation/OpenColorIO/issues/297).

**Comment by Corvus69** [comment] 2021-01-18 23:39
I can't load any saved project files either, it just crashes to desktop. Another Linux user submitted it, but I think it has yet to be triaged.
Cheers,
Dave.

**Comment by satcom886** [comment] 2021-01-19 00:13
This also happens to me. `Olive 0.2.0-19eabf28`.
I created a sequence, dropped in a few short (~10 second) h.264 clips, moved the cache location somewhere else and saved the project.
After closing it and trying to open it again, it always crashes with a Segmentation Fault.

**Comment by satcom886** [comment] 2021-01-19 00:16
I just tried `LANG=C olive-editor`, but the result stays the same.

**Comment by Corvus69** [comment] 2021-01-19 00:23
> This also happens to me. `Olive 0.2.0-19eabf28`.
> I created a sequence, dropped in a few short (~10 second) h.264 clips, moved the cache location somewhere else and saved the project.
> After closing it and trying to open it again, it always crashes with a Segmentation Fault.

I don't even move the cache - it just CTDs if I try to load a previous save file. See this report:
https://github.com/olive-editor/olive/issues/1456

**Comment by satcom886** [comment] 2021-01-19 10:27
> > This also happens to me. `Olive 0.2.0-19eabf28`.
> > I created a sequence, dropped in a few short (~10 second) h.264 clips, moved the cache location somewhere else and saved the project.
> > After closing it and trying to open it again, it always crashes with a Segmentation Fault.
> 
> I don't even move the cache - it just CTDs if I try to load a previous save file. See this report:
> #1456

Yup. No need to move the cache. Crashes even without doing that.

**Comment by martinprikryl** [comment] 2021-02-07 17:20
I'm having the same problem with `Olive-19eabf28-Windows-x86_64.zip` and `Olive-374fa3f7-Windows-x86_64.zip`.

`Olive-1cd07bc1-Windows-x86_64.zip` works.

**Comment by wernight** [comment] 2021-02-17 20:18
I have the same issue for a while including in latest release, when running on Crostini (Ubuntu on Chromebook).

Version: 19eabf28
MD5: 806251aef0b14616850585de973d91f8
SHA1: 79e3f66631a4edd64b3f3732f2540e982ec4f94b

```
[2991:2991:20210217,211656.423911:ERROR elf_image_reader.cc:116] no preferred header address
[2991:2991:20210217,211656.423921:ERROR process_reader_linux.cc:520] no module mappings 0x7cb1f4067000
[2991:2991:20210217,211656.424503:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[2991:2991:20210217,211656.424539:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Segmentation fault (core dumped)
```

Note that it's irrelevant of what is in the project as far as I can tell. Also the project was create with that same version.

**Comment by callegar** [comment] 2021-02-27 20:47
Same issue here.  Made a new project, put a video in it, cut away a few bits of it, saved, cannot open it anymore because olive crashes. Seeing this on Ubuntu 20.04 with the appimage.

**Comment by callegar** [comment] 2021-02-27 21:00
I confirm that this is a regression. Version from Dec 13th works for me too. So the issue is there both in windows and in linux for the two versions post Dec 13.

**Comment by callegar** [comment] 2021-02-27 21:07
There appear to be many many duplicates of this, carrying no information about moving two versions back as a workaround.

Bug #1495 is probably a duplicate
Bug #1491 is probably a duplicate
Bug #1488 is probably a duplicate
Bug #1471 may be a duplicate too
Bug #1469 is probably a duplicate
Bug #1456 is probably a duplicate

There may be more

**Comment by itsmattkc** [comment] 2021-03-21 12:30
Can you test this with a new project file on the latest commit?

**Comment by Corvus69** [comment] 2021-03-21 13:03
Well, I've tried it with the latest nightly build (5b04d84) and OVE project files seems to work fine. (Though older projects are somewhat incompatible as expected). When saved as a .OTIO the project fails to load (although when trying to save it, Olive crashes to desktop so it may not be saving it properly anyway.)

 I see you also fixed the CTD bug if you grab the sequence viewer window when something was on the timeline - awesome! Many thanks for all your hard work! Dave.

**Comment by itsmattkc** [comment] 2021-03-21 13:14
Yeah if OTIO is saving on crash, that's probably a bug in and of itself. Feel free to make an issue for that too

**Comment by itsmattkc** [comment] 2021-03-22 12:57
Merging into #1456 since I believe it was the same bug.

**Closed by itsmattkc** 2021-03-22 12:57 UTC
Labels: Crash, Triage
