### ISSUE TITLE
Playhead sped up audio bug

### ISSUE THREAD

**Issue by Masken8** [olive-editor/olive#837] opened 2019-04-18 21:04 UTC
[If you are reporting a bug, please try to fill out all the information below. If you are requesting a feature, you can clear this template.]

### System Information

**Olive version:** 35e0cb4f
**Source:** Website
**Operating system:** Windows 10 Home 64bit
**CPU:** AMD A8-7410
**RAM:** 8GB DDR3 L
**GPU:** AMD Radeon(TM) R5 M335 2GB VRAM

### Detailed Description

When I render my video the first audio(mp3 from Balabolka) is sped up but it sounds normal in Olive. But if I put the playhead a couple of seconds after the absolute last media in the timeline and export the first audio sounds normal

### Steps to reproduce

Export mp3 from Balabolka import it to Olive and put it in the timeline render it with the playhead at the the start of the video and export this should reproduce it

### Output Log

?

**Comment by itsmattkc** [comment] 2019-04-19 00:17
Does 3251a420c066c093a54673304be89397287744e8 fix this?

**Comment by Masken8** [comment] 2019-04-19 04:50
Will test when in on my computer i just woke up

**Comment by Masken8** [comment] 2019-04-19 07:58
Possible duplicate of #753

**Comment by Masken8** [comment] 2019-04-19 08:37
@itsmattkc Still sped up

**Comment by benrob0329** [comment] 2019-04-19 13:42
I'd say probable duplicate, as I have also experienced this issue and changing the exported sample rate fixes it.

**Comment by itsmattkc** [comment] 2019-05-02 03:22
I believe this is a duplicate of #735.

**Closed by itsmattkc** 2019-05-02 03:22 UTC
