### ISSUE TITLE
[UI] Suspicious, nonexistant startup file constantly loading.

### ISSUE THREAD

**Issue by reiyua** [olive-editor/olive#2337] opened 2024-06-25 06:59 UTC
**Commit Hash** 
0.2.0-f7e1bff0

**Platform** 
Windows 11 Pro 23H2

**Summary**
A very suspicious, non existent "startup" file constantly attempts to open up, and has appeared since I FIRST installed the software yesterday.  I initally thought this was some virus that was installed but have tried on TWO other Windows 11 laptops and have achieved the same result. I am easily able to just press "OK" but this will appear on every launch.

**Additional Information / Output**

![image](https://github.com/olive-editor/olive/assets/11124303/1241bddd-0094-42c9-a3f5-bfd56d19ce8c)

**Comment by itsmattkc** [comment] 2024-07-16 17:34
Duplicate of #2075

**Closed by itsmattkc** 2024-07-16 17:34 UTC
Labels: User Interface, Triage
