### ISSUE TITLE
[TIMELINE] It seems that when changing speed on video clip above or below 100%, the video is not stretched in the timeline

### ISSUE THREAD

**Issue by rpatros1979** [olive-editor/olive#1698] opened 2021-07-31 05:36 UTC
**Commit Hash** 
5254be3f

**Platform** 
Arch Linux

**Summary**

https://user-images.githubusercontent.com/53153746/127729945-761f1871-eeb3-42ea-a809-bea272e99966.mp4

1. Create a sequence and add a video clip to the video1
2. Create the following nodes attached in this sequence:

Text-->Stroke-->Transform-->Crop-->Blur-->\
                                           \___Merge
                                           /
                 Media file-->Transform-->/

3. Test 1, change the video clip speed to 50 from 100
4. The video does not seem to be stretched in the timeline to accomodate the length of the defined speed of the clip. The clip does seem to play at half speed but it seems that it since the video is not stretched it is stops at the end frame.
4. Test 2, change the video clip speed to 200 from 100.
5. The video does not seem to be stretched in the timeline to accomodate the length of the defined speed of the clip. The clip does seem to play 2 times faster but it seems that it since the video clip length is not shortened, the rest of the video is black.

**Additional Information / Output**

**Comment by Simran-B** [comment] 2021-07-31 07:01
> The video does not seem to be stretched in the timeline to accommodate the length of the defined speed of the clip.

This is by design. Duplicate of #1389

**Closed by Simran-B** 2021-07-31 07:01 UTC
Labels: Playback, Triage

**Comment by rpatros1979** [comment] 2021-07-31 17:48
Thank you for the reply @Simran-B, but I still think it a is a bug because the container constraints when slowing the video by 50%, half of the video will be missing.

Do you have to stretch the video clip in the timeline to accommodate the length of the video when it is slowed down? I read bug 1389 when there are plans to keyfram the speed but again it would mean the same because the clip container limits stretching the video to fill the rest of the frames needed..

That is just my take on it.

**Comment by Simran-B** [comment] 2021-08-01 20:32
> Do you have to stretch the video clip in the timeline to accommodate the length of the video

Exactly. A clip is a container and independent of the medium.

Time effects include 0 (freeze frame) and negative values for speed. Automatically adjusting the clip length in the former case would logically be to make the clip length infinite, and in the latter case I'm not sure what would be expected. When animating the speed, especially crossing 0, it does not make any sense to adjust the clip length anymore and would be more annoying than helpful. It's also a valid workflow to allot a fixed amount of time for footage and to tweak the speed without affecting the clip boundaries so that the duration remains the same.

An idea that was discussed was to make it easy to set the clip boundaries to the medium start and end points, e.g. via snapping and visually indicating where the medium begins and ends. There are some other possibilities, but it's too early to get into details.
