### ISSUE TITLE
[UI] Duplicate project right click menu item in project browser

### ISSUE THREAD

**Issue by alcomposer** [olive-editor/olive#2039] opened 2022-09-25 06:02 UTC
**Commit Hash** 
658fe9da

**Platform**
Linux

**Summary**
When working with sequences, we will want to be able to duplicate them, so as to keep an earlier version, or to build different versions of the sequence for different uses.

It would be important to have two versions of duplicate: 

* Duplicate (Linked)
* Duplicate (Unlinked)

The idea would be that **Linked** duplicates the project, and all nested sequences remain linked, so as when changes are made to the nested sequences, the changes still propagate to the new duplicated sequence.

**Unlinked** would break that link, and duplicate the project and all of it's nested sequences as a new sequence. So that we can make changes to the new duplicate sequence without disrupting the original sequence.

FCPX has this exact functionality, called "Reference New Parent". That sounds kinda cryptic, but the idea is very simple, and 100% necessary for project management, and useful use of nested sequences.

For example, if I were working on a series I may want the same intro sequence to be referenced for each episode. But I may want to change the text sequence in each different intro segment. For this example I would have a nested sequence in the intro sequence, then reference the same intro sequence for each different episode intro.

For project archiving, it's also very useful to duplicate a main sequence unlinked, so that no changes you make in the future to anything inside are updated. For example, if I were sending an edit to a client, I would create a duplicate unlinked version of the sequence, so that I can always go back and see what I sent to the client. 

While it is possible to "Save As" the whole project, keeping the archived sequence in the main project browser is important if an editor needs to go back and revert a change made.

![olive_sequence_right_click_menu](https://user-images.githubusercontent.com/12004932/192130569-17f235f4-7631-4122-b655-220e1b99cfcb.jpg)

**Comment by itsmattkc** [comment] 2022-09-25 14:59
Duplicate of #1346

**Closed by itsmattkc** 2022-09-25 14:59 UTC
Labels: User Interface, Triage
