### ISSUE TITLE
[CRASH] AppImage fd143f1d hangs

### ISSUE THREAD

**Issue by JoaquimCarneiro** [olive-editor/olive#1238] opened 2020-09-26 12:13 UTC
**Commit Hash**
fd143f1d

**Platform**
Arch Linux

**Summary**
Double click on the appimage doesn't open the application
Running the appimage from terminal result in a hang with an error about double_fork_and_exec, the application throws and error but doesn't  exit 
(the applications has execution permissions)
Ended compiling from source and, in this case, everything is working fine (for now 8p).

**Steps to Reproduce**
1. double click appimage binary
2. nothing happens 
or 
1. run from terminal 
2. application throws error and hangs

**Error in Terminal**
<details><summary><strong>Backtrace</strong></summary><pre><code>

[18849:18849:20200926,125919.537620:FATAL double_fork_and_exec.cc:131] execv crashpad_handler: Ficheiro ou pasta inexistente (2)

</code></pre></details>

**Comment by AGI-THB** [comment] 2020-09-26 12:22
#1230

**Comment by itsmattkc** [comment] 2020-09-26 14:45
Duplicate of #1230, now fixed in 79d8b95f4ef46200a8eb14ed1b470d017786df7b

**Closed by itsmattkc** 2020-09-26 14:45 UTC
Labels: Crash, Triage
