### ISSUE TITLE
[CRASH] Attempting to put things on non-existent timeline after creating new project with allready opened project

### ISSUE THREAD

**Issue by mcDandy** [olive-editor/olive#1647] opened 2021-05-27 18:21 UTC
**Commit Hash** 
ab31df36

**Platform** 
Windows 10

**Summary**
I created new project. Project previously opened had seqence with size of 256x256 and framerate of 29 fps. It was still there along with file on timeline. I imported 1920x1080 file with the about same framerate. I dropped it on timeline  which should not be there and olive crashed.

**Steps to Reproduce**

1. Have project with something on timeline
2. Create new project
3. Add file to new project
4. put it to timeline
5. crash

<details><summary><strong>Crash Report</strong></summary><pre><code>

Crash report is empty. Attaching stack trace.
Out of bounds read at ? - output._node = nullptr
<pre><code>
>	olive-editor.exe!olive::Node::ConnectEdge(const olive::NodeOutput & output, const olive::NodeInput & input) Řádek 283	C++
 	olive-editor.exe!olive::PreviewAutoCacher::AddEdge(const olive::NodeOutput & output, const olive::NodeInput & input) Řádek 368	C++
 	olive-editor.exe!olive::PreviewAutoCacher::ProcessUpdateQueue() Řádek 315	C++
 	olive-editor.exe!olive::PreviewAutoCacher::TryRender() Řádek 492	C++
 	olive-editor.exe!olive::PreviewAutoCacher::VideoInvalidated(const olive::TimeRange & range) Řádek 134	C++
 	Qt5Core.dll!00007ff848765259()	Neznámý
 	olive-editor.exe!olive::PlaybackCache::Invalidated(const olive::TimeRange & _t1) Řádek 230	C++
 	olive-editor.exe!olive::PlaybackCache::SetLength(const olive::rational & r) Řádek 85	C++
 	olive-editor.exe!olive::ViewerOutput::VerifyLength() Řádek 307	C++
 	Qt5Core.dll!00007ff848765259()	Neznámý
 	olive-editor.exe!olive::TrackList::LengthChanged(const olive::rational & _t1) Řádek 230	C++
 	Qt5Core.dll!00007ff848765259()	Neznámý
 	olive-editor.exe!olive::Track::SetLengthInternal(const olive::rational & r, bool invalidate) Řádek 672	C++
 	olive-editor.exe!olive::Track::EndOperation() Řádek 610	C++
 	olive-editor.exe!olive::Track::AppendBlock(olive::Block * block) Řádek 523	C++
 	olive-editor.exe!olive::TrackPlaceBlockCommand::redo() Řádek 1388	C++
 	olive-editor.exe!olive::UndoCommand::redo_and_set_modified() Řádek 45	C++
 	olive-editor.exe!olive::MultiUndoCommand::redo() Řádek 29	C++
 	olive-editor.exe!olive::UndoCommand::redo_and_set_modified() Řádek 45	C++
 	olive-editor.exe!olive::UndoStack::push(olive::UndoCommand * command) Řádek 60	C++
 	olive-editor.exe!olive::ImportTool::DropGhosts(bool insert) Řádek 441	C++
 	olive-editor.exe!olive::ImportTool::DragDrop(olive::TimelineViewMouseEvent * event) Řádek 165	C++
 	olive-editor.exe!olive::TimelineWidget::ViewDragDropped(olive::TimelineViewMouseEvent * event) Řádek 865	C++
 	Qt5Core.dll!00007ff848765259()	Neznámý
 	olive-editor.exe!olive::TimelineView::DragDropped(olive::TimelineViewMouseEvent * _t1) Řádek 274	C++
 	olive-editor.exe!olive::TimelineView::dropEvent(QDropEvent * event) Řádek 206	C++
 	Qt5Widgets.dll!00007ff84b267cfc()	Neznámý
 	Qt5Widgets.dll!00007ff84b308530()	Neznámý
 	Qt5Widgets.dll!00007ff84b52a122()	Neznámý
 	Qt5Core.dll!00007ff84874812a()	Neznámý
 	Qt5Widgets.dll!00007ff84b24496c()	Neznámý
 	Qt5Widgets.dll!00007ff84b2435b1()	Neznámý
 	Qt5Core.dll!00007ff84874607a()	Neznámý
 	Qt5Widgets.dll!00007ff84b28ef21()	Neznámý
 	Qt5Widgets.dll!00007ff84b28e2d8()	Neznámý
 	Qt5Widgets.dll!00007ff84b244980()	Neznámý
 	Qt5Widgets.dll!00007ff84b243a03()	Neznámý
 	Qt5Core.dll!00007ff84874607a()	Neznámý
 	Qt5Gui.dll!00007ff848b83610()	Neznámý
 	Qt5Gui.dll!00007ff848b6c5d0()	Neznámý
 	qwindows.dll!00007ff89b1ebcd6()	Neznámý
 	ole32.dll!CPrivDragDrop::PrivDragDrop(CallerLocalityIndicator locality, HWND__ * hwnd, tagInterfaceData * pIFDataObject, unsigned long dop, unsigned long grfKeyState, _POINTL ptl, unsigned long * pdwEffects, unsigned long dwSmId, IDataObject * pRealDataObject, HWND__ * hwndSource) Řádek 740	C++
 	ole32.dll!PrivDragDrop(HWND__ * hwnd, IDropTarget * pWinRtTarget, tagDRAGOP dop, tagInterfaceData * pIFDDataObject, IDataObject * pIDataObject, unsigned long grfKeyState, _POINTL ptl, unsigned long * pdwEffect, HWND__ * hwndSource, void * * phDDInfo) Řádek 920	C++
 	ole32.dll!CDropTargetAdapter::Drop(IDataObject * pDataObject, unsigned long grfKeyState, _POINTL ptl, unsigned long * pdwEffect) Řádek 3449	C++
 	ole32.dll!CDragOperation::CompleteDrop() Řádek 2621	C++
 	ole32.dll!DoDragDrop(IDataObject * pDataObject, IDropSource * pDropSource, unsigned long dwOKEffects, unsigned long * pdwEffect) Řádek 3115	C++
 	qwindows.dll!00007ff89b1ed490()	Neznámý
 	Qt5Gui.dll!00007ff848bb5f6d()	Neznámý
 	Qt5Gui.dll!00007ff848bb676f()	Neznámý
 	Qt5Widgets.dll!00007ff84b466d38()	Neznámý
 	Qt5Widgets.dll!00007ff84b46152e()	Neznámý
 	Qt5Widgets.dll!00007ff84b4c2612()	Neznámý
 	Qt5Widgets.dll!00007ff84b267786()	Neznámý
 	Qt5Widgets.dll!00007ff84b308530()	Neznámý
 	Qt5Widgets.dll!00007ff84b4680c8()	Neznámý
 	Qt5Core.dll!00007ff84874812a()	Neznámý
 	Qt5Widgets.dll!00007ff84b24496c()	Neznámý
 	Qt5Widgets.dll!00007ff84b2428a0()	Neznámý
 	Qt5Core.dll!00007ff84874607a()	Neznámý
 	Qt5Widgets.dll!00007ff84b245b85()	Neznámý
 	Qt5Widgets.dll!00007ff84b2901d2()	Neznámý
 	Qt5Widgets.dll!00007ff84b28e16e()	Neznámý
 	Qt5Widgets.dll!00007ff84b244980()	Neznámý
 	Qt5Widgets.dll!00007ff84b243a03()	Neznámý
 	Qt5Core.dll!00007ff84874607a()	Neznámý
 	Qt5Gui.dll!00007ff848b846c3()	Neznámý
 	Qt5Gui.dll!00007ff848b6ecb0()	Neznámý
 	Qt5Core.dll!00007ff84878f0ca()	Neznámý
 	qwindows.dll!00007ff89b1fd9e9()	Neznámý
 	Qt5Core.dll!00007ff84874252c()	Neznámý
 	Qt5Core.dll!00007ff848745044()	Neznámý
 	olive-editor.exe!main(int argc, char * * argv) Řádek 204	C++
 	[Vložený rámec] olive-editor.exe!invoke_main() Řádek 78	C++
 	olive-editor.exe!__scrt_common_main_seh() Řádek 288	C++
 	kernel32.dll!BaseThreadInitThunk()	Neznámý
 	ntdll.dll!RtlUserThreadStart()	Neznámý

</code></pre></details>

**Additional Information**
I cat out parts where I failed at moving file to olive or grabbing file. Nodes were not recorded properly and there are more of them.
 https://user-images.githubusercontent.com/18588943/119876284-047f9800-bf28-11eb-81fc-725fc3ad54d2.mp4

**Comment by itsmattkc** [comment] 2021-05-27 23:34
Duplicate of #1351

**Closed by itsmattkc** 2021-05-27 23:34 UTC
Labels: Crash, Triage
