### ISSUE TITLE
[CRASH] Olive 0.2 Crashed when dropping footage onto timeline

### ISSUE THREAD

**Issue by DaniSeeh** [olive-editor/olive#1212] opened 2020-09-21 22:44 UTC
**Commit Hash (8 character string of letters/numbers in title bar)**
871bc08c

**Platform**
Manjaro

**Summary**
Upon dragging an h.264 mp4 video file onto timeline, Olive 0.2 consistently crashed

**Steps to Reproduce**
1. Import mp4
2. Drag onto timeline
3. Allow automatic detection
4. Segfault

**Backtrace**
```
[daniel@daniel-pc app]$ ./olive-editor
[DEBUG] Extracting default OCIO config to "/tmp/olivevideoeditor.org/Olive/ocioconf" ((null):0)
[INFO] Using Qt version: 5.15.0 ((null):0)
[DEBUG] Using graphics driver: NVIDIA Corporation ((null):0)
[INFO] Setting output audio device to "alsa_output.pci-0000_0c_00.3.analog-stereo" ((null):0)
[DEBUG] No arenas, creating new... ((null):0)
Segmentation fault (core dumped)
[daniel@daniel-pc app]$ gdb ./olive-editor
GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./olive-editor...
(No debugging symbols found in ./olive-editor)
(gdb) run
Starting program: /home/daniel/Downloads/olive-master/app/olive-editor 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffec52e700 (LWP 96651)]
[Detaching after vfork from child process 96652]
[Detaching after vfork from child process 96653]
[DEBUG] Extracting default OCIO config to "/tmp/olivevideoeditor.org/Olive/ocioconf" ((null):0)
[New Thread 0x7fffe92ac700 (LWP 96656)]
[INFO] Using Qt version: 5.15.0 ((null):0)
[New Thread 0x7fffe3fff700 (LWP 96657)]
[New Thread 0x7fffe37fe700 (LWP 96658)]
[New Thread 0x7fffe2ffd700 (LWP 96659)]
[New Thread 0x7fffe27fc700 (LWP 96660)]
[DEBUG] Using graphics driver: NVIDIA Corporation ((null):0)
[New Thread 0x7fffcebff700 (LWP 96661)]
[INFO] Setting output audio device to "alsa_output.pci-0000_0c_00.3.analog-stereo" ((null):0)
[New Thread 0x7fffcdffe700 (LWP 96662)]
[New Thread 0x7fffcd7fd700 (LWP 96663)]
[New Thread 0x7fffccffc700 (LWP 96664)]
[New Thread 0x7fffb3fff700 (LWP 96665)]
[New Thread 0x7fffb37fe700 (LWP 96666)]
[New Thread 0x7fffb2ffd700 (LWP 96667)]
[New Thread 0x7fffb27fc700 (LWP 96668)]
[New Thread 0x7fffb1ffb700 (LWP 96669)]
[New Thread 0x7fffb17fa700 (LWP 96670)]
[New Thread 0x7fffb0ff9700 (LWP 96671)]
[New Thread 0x7fffb07f8700 (LWP 96672)]
[New Thread 0x7fffafff7700 (LWP 96673)]
[New Thread 0x7fffaf7f6700 (LWP 96674)]
[New Thread 0x7fffaeff5700 (LWP 96675)]
[New Thread 0x7fffae7f4700 (LWP 96676)]
[New Thread 0x7fffadff3700 (LWP 96677)]
[Thread 0x7fffcdffe700 (LWP 96662) exited]
[Thread 0x7fffcd7fd700 (LWP 96663) exited]
[Thread 0x7fffccffc700 (LWP 96664) exited]
[Thread 0x7fffb3fff700 (LWP 96665) exited]
[Thread 0x7fffb37fe700 (LWP 96666) exited]
[Thread 0x7fffb2ffd700 (LWP 96667) exited]
[Thread 0x7fffb27fc700 (LWP 96668) exited]
[Thread 0x7fffb1ffb700 (LWP 96669) exited]
[Thread 0x7fffb17fa700 (LWP 96670) exited]
[Thread 0x7fffb0ff9700 (LWP 96671) exited]
[Thread 0x7fffb07f8700 (LWP 96672) exited]
[Thread 0x7fffafff7700 (LWP 96673) exited]
[Thread 0x7fffaf7f6700 (LWP 96674) exited]
[Thread 0x7fffaeff5700 (LWP 96675) exited]
[Thread 0x7fffae7f4700 (LWP 96676) exited]
[Thread 0x7fffadff3700 (LWP 96677) exited]
[New Thread 0x7fffadff3700 (LWP 96678)]
[New Thread 0x7fffae7f4700 (LWP 96679)]
[New Thread 0x7fffaeff5700 (LWP 96680)]
[New Thread 0x7fffaf7f6700 (LWP 96681)]
[New Thread 0x7fffcdffe700 (LWP 96682)]
[New Thread 0x7fffcd7fd700 (LWP 96683)]
[New Thread 0x7fffccffc700 (LWP 96684)]
[New Thread 0x7fffb0496700 (LWP 96685)]
[New Thread 0x7fffad7f2700 (LWP 96686)]
[New Thread 0x7fffacff1700 (LWP 96687)]
[New Thread 0x7fff67fff700 (LWP 96688)]
[New Thread 0x7fff677fe700 (LWP 96689)]
[New Thread 0x7fff66ffd700 (LWP 96690)]
[New Thread 0x7fff667fc700 (LWP 96691)]
[New Thread 0x7fff65ffb700 (LWP 96692)]
[New Thread 0x7fff657fa700 (LWP 96693)]
[New Thread 0x7fff64ff9700 (LWP 96694)]
[New Thread 0x7fff647f8700 (LWP 96695)]
[New Thread 0x7fff63ff7700 (LWP 96696)]
[New Thread 0x7fff637f6700 (LWP 96697)]
[New Thread 0x7fff62ff5700 (LWP 96698)]
[New Thread 0x7fff627f4700 (LWP 96699)]
[New Thread 0x7fff61ff3700 (LWP 96700)]
[New Thread 0x7fff617f2700 (LWP 96701)]
[New Thread 0x7fff60ff1700 (LWP 96702)]
[New Thread 0x7fff607f0700 (LWP 96703)]
[New Thread 0x7fff5ffef700 (LWP 96704)]
[New Thread 0x7fff5f7ee700 (LWP 96705)]
[New Thread 0x7fff5efed700 (LWP 96706)]
[New Thread 0x7fff5e7ec700 (LWP 96707)]
[New Thread 0x7fff5dfeb700 (LWP 96708)]
[New Thread 0x7fff5d7ea700 (LWP 96709)]
[New Thread 0x7fff5cfe9700 (LWP 96710)]
[New Thread 0x7fff5c7e8700 (LWP 96711)]
[New Thread 0x7fff5bfe7700 (LWP 96712)]
[New Thread 0x7fff5b7e6700 (LWP 96713)]
[DEBUG] No arenas, creating new... ((null):0)
--Type <RET> for more, q to quit, c to continue without paging--<ret>

Thread 25 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffadff3700 (LWP 96678)]
0x00007ffff5ec7852 in ?? () from /usr/lib/libswscale.so.5
(gdb) bt
#0  0x00007ffff5ec7852 in ?? () from /usr/lib/libswscale.so.5
#1  0x00007ffff5ec672c in ?? () from /usr/lib/libswscale.so.5
#2  0x00007ffff5e9cfa9 in sws_scale () from /usr/lib/libswscale.so.5
#3  0x00005555558675f2 in olive::FFmpegDecoder::BuffersToNativeFrame(int, int, int, olive::rational const&, unsigned char**, int*) ()
#4  0x0000555555864d12 in olive::FFmpegDecoder::RetrieveVideo(olive::rational const&, int const&) ()
#5  0x00005555559677fa in olive::RenderWorker::ProcessVideoFootage(std::shared_ptr<olive::Stream>, olive::rational const&) ()
#6  0x000055555591a966 in olive::NodeTraverser::PostProcessTable(olive::Node const*, olive::TimeRange const&, olive::NodeValueTable&) ()
#7  0x0000555555919f7f in olive::NodeTraverser::GenerateTable(olive::Node const*, olive::TimeRange const&) ()
#8  0x0000555555919d85 in olive::NodeTraverser::ProcessInput(olive::NodeInput*, olive::TimeRange const&) ()
#9  0x0000555555919bf8 in olive::NodeTraverser::GenerateDatabase(olive::Node const*, olive::TimeRange const&) ()
#10 0x0000555555919f42 in olive::NodeTraverser::GenerateTable(olive::Node const*, olive::TimeRange const&) ()
#11 0x000055555591a0df in olive::NodeTraverser::GenerateBlockTable(olive::TrackOutput const*, olive::TimeRange const&) ()
#12 0x0000555555966338 in olive::RenderWorker::GenerateBlockTable(olive::TrackOutput const*, olive::TimeRange const&) ()
--Type <RET> for more, q to quit, c to continue without paging--<ret>
#13 0x0000555555919f25 in olive::NodeTraverser::GenerateTable(olive::Node const*, olive::TimeRange const&) ()
#14 0x0000555555919d85 in olive::NodeTraverser::ProcessInput(olive::NodeInput*, olive::TimeRange const&) ()
#15 0x00005555559654d0 in olive::RenderWorker::RenderFrame(std::shared_ptr<olive::RenderTicket>, olive::ViewerOutput*, olive::rational const&) ()
#16 0x0000555555963961 in QtConcurrent::VoidStoredMemberFunctionPointerCall3<void, olive::RenderWorker, std::shared_ptr<olive::RenderTicket>, std::shared_ptr<olive::RenderTicket>, olive::ViewerOutput*, olive::ViewerOutput*, olive::rational const&, olive::rational>::runFunctor() ()
#17 0x0000555555954817 in QtConcurrent::RunFunctionTask<void>::run() ()
#18 0x00007ffff3a37e92 in ?? () from /usr/lib/libQt5Core.so.5
#19 0x00007ffff3a33e0f in ?? () from /usr/lib/libQt5Core.so.5
#20 0x00007ffff4dc6422 in start_thread () from /usr/lib/libpthread.so.0
#21 0x00007ffff3561bf3 in clone () from /usr/lib/libc.so.6
(gdb) 
```
**Additional Information**

**Comment by itsmattkc** [comment] 2020-09-22 01:43
Duplicate of #1176, I recommend either downgrading to FFmpeg 4.2 if you can, or switching to FFmpeg's git master (since you're on Manjaro you should be able to use [this AUR](https://aur.archlinux.org/packages/ffmpeg-git/)) which has fixed this issue. We should also have an AppImage up and running soon with specific dependency versions that gets around this issue.

**Closed by itsmattkc** 2020-09-22 01:43 UTC
Labels: Crash, Triage

**Comment by DaniSeeh** [comment] 2020-09-22 01:45
Thanks! Sorry for double reporting
