### ISSUE TITLE
[CRASH] Olive crashes when reattaching node

### ISSUE THREAD

**Issue by nesper8** [olive-editor/olive#1732] opened 2021-08-25 06:58 UTC
**Commit Hash** 
dc66c303

**Platform** 
Arch Linux

**Summary**
Olive crashes when reattaching sequence node to Root (Children) node

**Steps to Reproduce**

1. Create new sequence a project which creates Sequence 1 in Node Editor
2. Expand Root Node in Node Editor in Node editor
3. Remove the already connected node which connects Sequence 1 to Children in Root Node
4. Re-attach the node from Sequence 1 to Children
5. Olive Crashes

GDB Log
```
(gdb) exec-file olive-editor
(gdb) run
Starting program: /usr/bin/olive-editor 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe1d4a640 (LWP 16986)]
[New Thread 0x7fffdbfff640 (LWP 16987)]
[New Thread 0x7fffdb7fe640 (LWP 16988)]
[New Thread 0x7fffdaffd640 (LWP 16989)]
[New Thread 0x7fffda7fc640 (LWP 16990)]
[New Thread 0x7fffcbfff640 (LWP 16991)]
[New Thread 0x7fffcb7fe640 (LWP 16992)]
[New Thread 0x7fffcaffd640 (LWP 16993)]
[DEBUG] Extracting default OCIO config to "/home/nesper8/.cache/olivevideoeditor.org/Olive/ocioconf" ((null):0)
[New Thread 0x7fffca7fc640 (LWP 16994)]
[New Thread 0x7fffc9ffb640 (LWP 16995)]
[New Thread 0x7fffc97fa640 (LWP 16996)]
[New Thread 0x7fffc8ff9640 (LWP 16997)]
[New Thread 0x7fffbdd54640 (LWP 16998)]
[New Thread 0x7fffbd553640 (LWP 16999)]
[INFO] Using Qt version: 5.15.2 ((null):0)
[New Thread 0x7fffbcd52640 (LWP 17000)]
[New Thread 0x7fff97fff640 (LWP 17001)]
[New Thread 0x7fff977fe640 (LWP 17002)]
[New Thread 0x7fff96ffd640 (LWP 17003)]
[New Thread 0x7fff967fc640 (LWP 17004)]
[New Thread 0x7fff95ffb640 (LWP 17005)]
[New Thread 0x7fff957fa640 (LWP 17006)]
[New Thread 0x7fff94ff9640 (LWP 17007)]
[New Thread 0x7fff6ffff640 (LWP 17008)]
[DEBUG] Using graphics driver: Intel ((null):0)
[Thread 0x7fff6ffff640 (LWP 17008) exited]
[New Thread 0x7fff6ffff640 (LWP 17009)]
[INFO] Setting output audio device to "alsa_output.pci-0000_00_1f.3.analog-stereo" ((null):0)
[WARNING] Tried to allocate sample buffer with zero sample count ((null):0)
[WARNING] Tried to fill an unallocated sample buffer ((null):0)
[Thread 0x7fffda7fc640 (LWP 16990) exited]

Thread 1 "olive-editor" received signal SIGSEGV, Segmentation fault.
0x00005555557e4735 in ?? ()
```

GDB Backtrace
```
(gdb) bt
#0  0x00005555557e4735 in  ()
#1  0x000055555b26e310 in  ()
#2  0x00005555557d7de1 in  ()
#3  0x0000000000000000 in  ()
```

**Comment by itsmattkc** [comment] 2021-08-25 16:14
Your build contains no symbols which makes your GDB backtrace effectively useless. Anyways I believe this is a duplicate of #1650 (allowing access to array elements).

**Closed by itsmattkc** 2021-08-25 16:14 UTC
Labels: Crash, Triage
