### ISSUE TITLE
export projects in the formats AAF, EDL, XML.

### ISSUE THREAD

**Issue by ongovorit** [olive-editor/olive#444] opened 2019-02-06 11:47 UTC
I propose to add the ability to export projects in the formats AAF, EDL, XML. Conveniently, for the exchange of finished projects with people who have installed other programs for video processing.

**Comment by sobotka** [comment] 2019-02-22 03:01
This is a duplicate of #310.

**Comment by ongovorit** [comment] 2019-02-22 10:35
What does duplicate mean? You want to say that I am duplicating topics?

> This is a duplicate of #310.

**Comment by ongovorit** [comment] 2019-02-22 10:36
**[ongovorit](/ongovorit) ** commented [16 days ago](#issue-407197946)
[sobotka](/sobotka) referenced this issue [ 8 hours ago](#ref-issue-407197946)

**Comment by ongovorit** [comment] 2019-02-22 10:37
My post is 16 days. Your 8 hours.

**Comment by naj59** [comment] 2019-02-22 11:50
The issue #310 is the same and over a month ago.

**Comment by ongovorit** [comment] 2019-02-22 12:09
Do you explain your messages? What for? I added a request to add parameters to the olive-editor program. Since at that time no such proposals were published for this program.
You write to me for what purpose?

You have completely different programs mentioned and there is no mention of export in olive-editor.

[Someone made a plugin for Premiere Pro.](https://github.com/boredstiff/protio) and [Blender might implement it](https://developer.blender.org/T59540).

Then they made a link to my post and write to me.

### [sobotka](/sobotka) referenced this issue [ 9 hours ago ](#ref-issue-407197946)
 Open
#### [ export projects in the formats AAF, EDL, XML. #444](/olive-editor/olive/issues/444)


I repeat the question? Why are you writing to me? You are a developer and want to clarify the details? Or answer my request?
If not. Go to the forest and bears tell about the duplication of information...

**Comment by ongovorit** [comment] 2019-02-22 12:18
If there is no information on my question: export projects in the formats AAF, EDL, XML.
Go about your business. And do not flood in other people's posts.

**Comment by naj59** [comment] 2019-02-22 12:22
Please go inform yourself about OpenTimelineIO. What you are currently doing here is a joke. 

> OpenTimelineIO supports, or plans to support, conversion adapters for many existing file formats, such as Final Cut Pro XML, AAF, CMX 3600 EDL, etc.

Marking it as duplicate would help to implement a feature faster because a wider userbase wants to have the same feature.

**Comment by ongovorit** [comment] 2019-02-22 12:29
Because a lot of jokers. Immediately difficult to understand. Or you are bored. Or you are also interested in this feature.

> Please go inform yourself about OpenTimelineIO. What you are currently doing here is a joke (why so much aggression about somebody who just says its a duplicate, tf?)
> 
> > OpenTimelineIO supports, or plans to support, conversion adapters for many existing file formats, such as Final Cut Pro XML, AAF, CMX 3600 EDL, etc.
> 
> Marking it as duplicate would help to implement a feature faster because a wider userbase wants to have the same feature.

**Comment by naj59** [comment] 2019-02-22 12:34
> **export projects in the formats AAF, EDL, XML**

> Support for OpenTimelineIO
> OpenTimelineIO supports, or plans to support, **conversion adapters for many existing file formats, such as Final Cut Pro XML, AAF, CMX 3600 EDL, etc.**

**Comment by ongovorit** [comment] 2019-02-22 12:39
Great information. Thank. I understand that export is possible in the future. Very happy.

**Comment by BrimsonBhin** [comment] 2019-05-02 18:21
Closing because OpenTimelineIO is being considered already

**Closed by BrimsonBhin** 2019-05-02 18:21 UTC
Labels: feature request
