### ISSUE TITLE
Effect settings are not getting copied

### ISSUE THREAD

**Issue by Cambloid** [olive-editor/olive#323] opened 2019-01-17 11:06 UTC
Version: Olive January 2019

When copying a clip with settings like scale or position. Those settings are not copied to the new clip.

**Comment by itsmattkc** [comment] 2019-01-17 12:06
Likely a duplicate of #272, is this the latest Windows binary from the website?

**Comment by Cambloid** [comment] 2019-01-17 12:23
Yes

**Comment by Symbian9** [comment] 2019-01-17 13:03
FTR, it's possible setup Travis CI for build nightly for Windows (as already it used for Linux).

- https://blog.travis-ci.com/2018-10-11-windows-early-release
- https://docs.travis-ci.com/user/reference/windows/
- https://docs.travis-ci.com/user/multi-os
- https://hub.packtpub.com/announcing-the-early-release-of-travis-ci-on-windows/

And here is example of `.travis.yml` for *macOS*

- https://github.com/leozide/leocad/blob/master/.travis.yml

So, nightly builds could be built using Travis CI for all supported platforms macOS, Linux, Windows

**Comment by itsmattkc** [comment] 2019-01-17 13:36
@Symbian9 Yeah setting up something like that would probably be a good idea

**Comment by itsmattkc** [comment] 2019-01-18 01:22
@Cambloid Please try the latest website builds and see if the issue is fixed

**Comment by itsmattkc** [comment] 2019-01-19 10:37
I will assume this issue is solved, feel free to let me know if not.

**Closed by itsmattkc** 2019-01-19 10:37 UTC
