### ISSUE TITLE
[PLAYBACK] MP3 audio file not playing

### ISSUE THREAD

**Issue by axiomgraph** [olive-editor/olive#1568] opened 2021-04-14 02:23 UTC
**Commit Hash** 
Olive 429442c0

**Platform** 
linux 
**Summary**
in time line mp3 audio file not playing. play button does works but time line stuck.

**Additional Information / Output**

**Comment by itsmattkc** [comment] 2021-04-14 03:50
We had some audio issues a few commits ago but just fixed them, can you confirm if this is fixed on your end?

**Comment by axiomgraph** [comment] 2021-04-15 03:56
problem still exists Olive-0d315d66
https://imgur.com/a/t25wji0

**Comment by itsmattkc** [comment] 2021-04-15 23:56
Can you send that file? MP3s on my end don't cause issues.

**Comment by itsmattkc** [comment] 2021-04-16 01:30
Can you delete the following folder and try again: `~/.local/share/olivevideoeditor.org/Olive/mediacache`

**Comment by axiomgraph** [comment] 2021-04-17 14:48
thanks after deleting mediacache audio started playing.

**Comment by Simran-B** [comment] 2021-04-17 21:26
Closing, as it was apparently caused by a bad disk cache.

**Closed by Simran-B** 2021-04-17 21:26 UTC
Labels: Playback, Triage
