### ISSUE TITLE
[PROJECT] Duplicate sequence

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1727] opened 2021-08-17 16:36 UTC
**Commit Hash** 
2794730a

**Platform** 
macOS 10.14.6 (but any)

**Summary**
It would be nice to have a way to duplicate a sequence in the Project view.
Something like selecting the sequence, pressing secondary mouse button and having that option.

**Additional Information / Output**
It could also be useful to duplicate any other element, such as folders...

Other option would be to have Copy and Paste entries but I think it would end up "duplicating" the sequence.

**Comment by itsmattkc** [comment] 2021-08-17 18:03
Duplicate of #1346

**Closed by itsmattkc** 2021-08-17 18:03 UTC
Labels: Triage
