### ISSUE TITLE
[Feature Request] Set timecode of clip from metadata only

### ISSUE THREAD

**Issue by alcomposer** [olive-editor/olive#629] opened 2019-03-13 16:24 UTC
When using cameras that record timecode start (in metadata), eg: Panasonic GH5 I am able to see this output in the terminal:

```
  Duration: 00:01:11.04, start: 0.000000, bitrate: 102834 kb/s
    Stream #0:0(und): Video: h264 (High 4:2:2) (avc1 / 0x31637661), yuv422p10le(pc, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 100087 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2019-02-23T14:50:02.000000Z
      timecode        : 02:26:00:00
```

However the clip in Olive shows start time of 00:00:00:00

It would be good to allow Olive to use this information.

Possibly:

**Sequence**  timecode of project sequence (starting at 0)
**Media**  timecode of container holding clip (starting at 0)
**Source Timecode**  timecode of clip itself (starting at creation time: metadata timecode)

**Comment by sobotka** [comment] 2019-03-15 03:57
Uh... duplicate of #628? LOL.

**Comment by alcomposer** [comment] 2019-03-15 04:32
Sorry Troy. I read your #628 request as LTC = https://en.wikipedia.org/wiki/Linear_timecode

This request is only for the reading of Metadata from the media, which may actually be different from a LTC encoded audio stream / burst.

If you were indeed thinking of Metadata then yes this is a duplicate.

I'm working on the metadata reading and display here: https://github.com/alcomposer/olive/tree/media_timecode_read_2

**Closed** 2019-03-15 05:05 UTC
