### ISSUE TITLE
[CRASH] attaching node and problems setting cross dissolve transition

### ISSUE THREAD

**Issue by MickBuntu** [olive-editor/olive#1537] opened 2021-03-25 10:53 UTC
**Commit hash**
2d420dec

**Platform**
Ubuntu 20.04.1

**Summary**
Open Olive, import small video, save project. Close Olive. Open Olive use recent is successful. Great. Try to set a Transition/Cross Dissolve, select start with cross, drag over video clip, it changes color then cuts instead of setting a dissolve. Tried several times, reproducible.  Added a node. Tried to change it but couldn't access its menu then tried to attach to clip and Olive closed without warning. I tried this several times with no success. At least I can save and reopen now. Nodes are very hard to get my head around. They may be technically the best way to go but they are not intuitive.

**Steps to reproduce**

1. Import video clip
2. Click toolbar Transition/Cross Dissolve
3. Drag cross hair from start of clip a few frames in
4. Release and expect a transition.
5. It cuts that amount from clip.
6. Attempt to create a node to do same thing
7. Try to attach node to clip
8. Olive immediately disappears without warning. Closes.

**Backtrace**
Sorry no backtrace.

**Additional information**
At least Olive will now allow a clip to be imported, saved and opened via Recent.

**Comment by itsmattkc** [comment] 2021-03-25 11:05
The first issue is a duplicate of #1522.

As for nodes, we intend to make some tutorials and documentation once Olive reaches a more stable state. Nodes may not be a familiar way of working to the average person, but they're actually very logical once you know what they're doing.

As for the crash, you'll have to be a little more specific. What node are you creating? What are you connecting it to?

**Comment by MickBuntu** [comment] 2021-03-25 20:22
I was attempting to attach the cross dissolve node to the video clip node. 
I may have inadvertantly touched another node as I tried to move the node 
group but found the mouse wasn't playing ball, as I'd previously been able 
to change the size/position of all node group by mouse wheel but this 
seemed to stop working so nodes were hard to hard to access being partly 
out of the node window. I'll try the test again and see if I can get my 
head around nodes, I'm a slow learner. Thank you for all your amazing work, 
I'll try to be more exacting in my comments.

From Birchley Manor via Samsung S2 tablet

**Comment by itsmattkc** [comment] 2021-04-08 11:48
The latest AppImage should provide a crash report on its own without the use of any debugger, can you recreate this in that and provide the report?

**Comment by itsmattkc** [comment] 2021-04-22 12:13
Closing for inactivity. I can't recreate the crash (it's possible it's been fixed inadvertently by now?) and without a report there's not much else I can do. Feel free to reply back with a crash report if you can recreate it in the latest commit.

**Closed by itsmattkc** 2021-04-22 12:13 UTC
Labels: Crash
