### ISSUE TITLE
[CRASH] closed when trying to turn a tab into a window

### ISSUE THREAD

**Issue by Kau-Aug** [olive-editor/olive#1512] opened 2021-03-14 18:12 UTC
the program closes when trying to transform the tab and a separate window

**Comment by AGI-THB** [comment] 2021-03-14 18:49
Fill out the Issue Template

**Comment by itsmattkc** [comment] 2021-03-20 12:16
It sounds like you're experiencing a crash when you try to undock a panel. Please provide specific steps to recreate this.

**Comment by Simran-B** [comment] 2021-03-20 12:23
Potentially a duplicate of #1486 which I was able to reproduce.

**Comment by itsmattkc** [comment] 2021-03-21 12:01
If it's a duplicate of #1486, it should be fixed in 5b04d84bfb9be16cd09083cf1eb73030218cddd7

**Comment by Simran-B** [comment] 2021-03-23 10:38
I'm pretty sure that this is a duplicate. Dragging a panel as well as clicking the small button to make a panel a separate window do no longer crash Olive for me.

![image](https://user-images.githubusercontent.com/7819991/112133763-4f013300-8bcc-11eb-9f07-1d392670ca8c.png)

**Closed by Simran-B** 2021-03-23 10:38 UTC
Labels: Crash, Inadequate Information, User Interface
