### ISSUE TITLE
[Feature Request] Re-enable nightly builds

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#1068] opened 2019-08-22 05:38 UTC
**Additional context**

Please, re-enable `continuous` builds.

- https://github.com/olive-editor/olive/releases/tag/continuous

**Comment by Simran-B** [comment] 2019-08-22 08:55
No point in doing that with Olive being in a non-functional state.

**Comment by Symbian9** [comment] 2019-08-22 09:38
> No point in doing that with Olive being in a non-functional state.

Well, think, you mean `master` branch.

But what about enabling nightly builds for `0.1.x`, as there are many changes since `v0.1.0` release:

- https://github.com/olive-editor/olive/tree/0.1.x

**Comment by AGI-THB** [comment] 2019-08-22 09:59
I would rather say: Disable all nightly builds.

The Problem is that in the last 6 months, most of the people using these builds had absolutely no clue about what an alpha software is or how software development works.
They don't look at the README or Roadmap and just complain that there are bugs ( which is normal in alpha stage) or that there is no masking / tracking.

Discord is full of these people. 

Just my opinion.

**Comment by Simran-B** [comment] 2019-08-22 10:16
> But what about enabling nightly builds for `0.1.x`, as there are many changes since `v0.1.0` release

All commits in the 0.1.x branch since the May release (1e3cf53) are updates to translations, nothing else.

**Comment by AGI-THB** [comment] 2019-08-23 08:39
@sobotka Can you close this ticket?

It's a repost anyway.

#923

**Comment by sobotka** [comment] 2019-08-23 08:46
Thanks @AGI-THB. Closing.

**Closed by sobotka** 2019-08-23 08:46 UTC
