### ISSUE TITLE
Sign Nightly Builds

### ISSUE THREAD

**Issue by Stoffe** [olive-editor/olive#1726] opened 2021-08-17 15:23 UTC
**Commit Hash** 
2794730a

**Platform** 
Windows

**Summary**
You are not signing any of the executables, which leads to Windows SmartScreen to block your files from beeing downloaded and executed unless you are bypassing it.
You should make part of your CI/CD pipeline sign the executable so its signed by you and can be identified as a legitimate .exe file.
This is a do once and then done job for a while so should be rather simple to achieve.
Also, make sure your exe file is populated with information about who you are and where this is from, so its possible to identify the exe file from you.

**Additional Information / Output**

**Comment by Stoffe** [comment] 2021-08-17 15:24
Note that Im talking about the installer executables currently.

**Comment by itsmattkc** [comment] 2021-08-17 17:57
Duplicate of #1288. We are well aware, but you're neglecting to mention that getting an EV certificate to sign with costs a fairly substantial amount of money annually. If you mean a "standard" code signing certificate, those are reportedly not enough to pass SmartScreen without "building up reputation", which generally won't happen because our nightly builds change so frequently.

We will certainly do it at some point, but while we're still in pre-alpha and still have extremely limited funds and resources, you'll just have to put up with clicking "Run Anyway".

**Closed by itsmattkc** 2021-08-17 17:57 UTC
