### ISSUE TITLE
Viewer not zooming correctly on macOS

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#187] opened 2018-12-22 22:49 UTC
Hi,

First of all, congratulations for this awesome project, you are almost done with all the basic features for professional editing.
I have tried both "november 2018" and alpha branch (compiling it) and they have the same Viewer bug: when having any kind of clip (video, title, solid color, etc...) the Viewer preview video gets underscalled and makes it difficult to edit... Everything else seems to work fine, just this weird bug.
<img width="1792" alt="1" src="https://user-images.githubusercontent.com/5942369/50379222-1e746c80-0644-11e9-87bf-7698af688614.png">
<img width="1792" alt="2" src="https://user-images.githubusercontent.com/5942369/50379223-23392080-0644-11e9-8be0-1f9f64c9edc3.png">

Keep on the good work
Thanks

PS- I'm running macOS 10.14 (Mojave)

**Comment by itsmattkc** [comment] 2018-12-23 00:15
Hi, thanks for checking out Olive and the kind words.

First of all, I assume you're on a Mac with a retina display? We had a similar bug on Linux (#167) that was also caused by HiDPI and got fixed, but I'm guessing that fix didn't permeate to Macs.

**Comment by pgilfernandez** [comment] 2018-12-23 08:48
Yes, you are right. I have checked the Linux issue and it’s similar... so in Mac it seems not to work.
I can only help testing it as I’m not a programmer but count on me for that or anything you think could be helpful.

Cheers

**Comment by itsmattkc** [comment] 2018-12-23 11:11
I've added some code to a new branch `retinafix`, let me know if this addresses the issue!

**Comment by pgilfernandez** [comment] 2018-12-23 15:34
It works like a charm!
=)
<img width="1792" alt="3" src="https://user-images.githubusercontent.com/5942369/50385031-0e08d400-06ce-11e9-9b4a-841c1799862d.png">

BTW my build doesn't export the video and it crashes when expanding a crossfade but I guess it's not related with this fix but just something with my non packaged build

**Comment by itsmattkc** [comment] 2018-12-23 15:42
Huh... it might be, but feel free to file another issue if those problems persist.

For now, I'll close this one - glad the problem's solved!

**Closed by itsmattkc** 2018-12-23 15:42 UTC
Labels: bug

**Comment by pgilfernandez** [comment] 2018-12-23 16:59
Hi,

Just one question: you haven't merged this fix into the December 2018 macOS release, doesn't it?
This build still has the bug...

**Comment by itsmattkc** [comment] 2018-12-24 10:16
No I'm afraid this fix wasn't merged into the master by the time I made the release, but it'll make the next one for sure (I might even update the build specifically for it since retina displays are so prevalent now).

**Comment by pgilfernandez** [comment] 2018-12-24 11:08
Don’t worry, I just wanted to know if it was a new bug or it just wasn’t merged
