### ISSUE TITLE
Opening saved project removes all position keyframes

### ISSUE THREAD

**Issue by Awesomeplayer98** [olive-editor/olive#2218] opened 2023-04-29 02:15 UTC
**245a4f6d** 

**Windows 10**

**When reopening a saved Olive project all positional keyframe data for images or videos (not text or shapes) is deleted, which is really frustrating and has shown up in several of my YouTube videos, which is super embarrassing. I have no idea how nobody else has reported this, but here's a screenshot: 
![image](https://user-images.githubusercontent.com/59984464/235278971-41c8e992-908a-4139-b030-5bdb61f34559.png)

https://user-images.githubusercontent.com/59984464/235374679-38b42b6a-1e3b-4cf8-9782-366a9534da70.mp4
**

**This happens every time I open the project when keyframes start and end on the same position, not when they end at different spots, but exporting works fine as long as I have fixed it in the same sitting. Please help! Thank you!**

**Comment by itsmattkc** [comment] 2023-04-30 13:46
I can't reproduce this. The keyframes restore fine for me.

You skipped entering the commit hash. Please enter it.

**Comment by Awesomeplayer98** [comment] 2023-04-30 20:25
Thank you so much, I just figured out what a commit hash is.
Also, I edited the post to include a video clip where I reproduce it. Thank you!

**Comment by itsmattkc** [comment] 2023-05-02 09:47
I too am surprised no one reported this until now.

Fixed in d75aef40a8aa24e51128a5e0ff8a305e1593dc28

**Closed by itsmattkc** 2023-05-02 09:47 UTC
Labels: Inadequate Information, Nodes/Compositing

**Comment by Awesomeplayer98** [comment] 2023-05-02 13:04
Me too! This has been pretty much my only complaint with Olive, and am glad to see it fixed! Thank you!
