### ISSUE TITLE
[Feature Request] Adding wipes to video transitions

### ISSUE THREAD

**Issue by malnaanah** [olive-editor/olive#499] opened 2019-02-13 17:41 UTC
I hope you can add wipes to video transitions as in Kdenlive, also it is good  to be able to add custom wipe images.

**Comment by itsmattkc** [comment] 2019-02-15 13:42
Kind of a duplicate of #452, I think I'll probably roll this issue into that one.

**Closed by itsmattkc** 2019-02-15 13:42 UTC
