### ISSUE TITLE
Allow editing multiple selected clips

### ISSUE THREAD

**Issue by main-gi** [olive-editor/olive#320] opened 2019-01-17 00:33 UTC
Not sure what all the ramifications would be if you allowed full control over _all_ differing elements (example: selecting two clips with different scales and being able to multiply/add some number to all of them), but at least you should be able to mass change the properties of _equal_ valued elements (clips of the same scale, position, opacity, etc.)

**Comment by itsmattkc** [comment] 2019-01-17 01:30
Duplicate of #92, but yes this is planned

**Closed by itsmattkc** 2019-01-17 01:30 UTC
