### ISSUE TITLE
[EXPORT] Renders a black video (only a few kb in size) on Linux

### ISSUE THREAD

**Issue by LavenderSolus** [olive-editor/olive#1663] opened 2021-07-04 04:08 UTC
**Commit Hash**  08e2fa4d

**Platform** 
elementary OS 5.1.7 Hera

**Summary**
I imported a 14 sec HD video about 19MB in size. When I export, it generates a sequence that is black and around 33 kb only (8 secs long in vlc).

**Additional Information / Output**
Did several tests, same result.
Used the default export settings.
AppImage 64-bit

**Comment by itsmattkc** [comment] 2021-07-04 16:50
Sounds like a duplicate of #1637 or #1297, which may even be duplicates of each other.

Does exporting with quality set to "half float" work?

**Comment by LavenderSolus** [comment] 2021-07-09 01:21
> Sounds like a duplicate of #1637 or #1297, which may even be duplicates of each other.
> 
> Does exporting with quality set to "half float" work?

**Comment by LavenderSolus** [comment] 2021-07-09 01:22
> Sounds like a duplicate of #1637 or #1297, which may even be duplicates of each other.
> 
> Does exporting with quality set to "half float" work?

Thanks a lot, mate. This worked! But I wanna know is "half-float" any lesser quality than "full-float"?

**Comment by itsmattkc** [comment] 2021-07-09 01:25
Theoretically yes, half-float is less precise and may lead to more color banding than full-float (half-float is good as a draft quality export), which is why full-float is the default.

Can you tell me what graphics card you have?

**Comment by LavenderSolus** [comment] 2021-07-09 04:57
No GPU actually. It's:
Intel i5 3330
Intel mobo (don't remember exact model, but its average)
RAM: 6GB (4+2)

**Comment by Simran-B** [comment] 2021-07-09 07:33
That would be an Intel HD Graphics 2500

https://ark.intel.com/content/www/us/en/ark/products/65509/intel-core-i5-3330-processor-6m-cache-up-to-3-20-ghz.html

Should support OpenGL 4.2 on Linux and 4.0 on Windows

https://en.m.wikipedia.org/wiki/Intel_Graphics_Technology#Capabilities_(GPU_hardware)

**Comment by itsmattkc** [comment] 2021-07-09 07:37
The person in #1297 had a Intel HD 5000, seems there might be something with Intel GPUs of a certain era (this issue appears to be a duplicate of that one).

**Comment by LavenderSolus** [comment] 2021-07-14 14:29
> The person in #1297 had a Intel HD 5000, seems there might be something with Intel GPUs of a certain era (this issue appears to be a duplicate of that one).

The new 539b0582 also have the same problem but partial: the logo that runs the full length of the video is fine from the very first second but the rest behind the logo is just black with partial scenes rendered okay if I skip forward.

**Comment by itsmattkc** [comment] 2021-07-15 20:31
I'm fairly certain this is a duplicate of #1297, some issue with float buffers on Intel GPUs before a certain generation. Closing to merge into that issue.

**Closed by itsmattkc** 2021-07-15 20:31 UTC
Labels: Export, Triage

**Comment by sobotka** [comment] 2021-12-11 18:43
> Thanks a lot, mate. This worked! But I wanna know is "half-float" any lesser quality than "full-float"?

The ultimate answer is going to be "it depends".

Full float will encode a wider range of stimulus values, as well as provide more values of precision for the decimal representation, which is surprisingly important even with float data [due to the underlying innate method of storage on a computer](https://fabiensanglard.net/floating_point_visually_explained/). There is another article [that is a solid read on the subject as well](https://bartwronski.com/2017/04/02/small-float-formats-r11g11b10f-precision/).

The "it depends" will end up being on the sources. If it is a high quality CGI render? Likely gains to be had. If footage from a camera? Probably not much for gains.
