### ISSUE TITLE
{Feature Request] Drop shadow on clip

### ISSUE THREAD

**Issue by brethnew** [olive-editor/olive#847] opened 2019-04-19 07:51 UTC
Okay so this is a very specific feature that I doubt many people would use very often.
I'd like the ability to assign a drop shadow "behind" a clip, let's say if you're using a webcam and overlaying your webcam clip on top of your game clip or something. I'm sure I can use a png to achieve the same effect if it never get's added.

Know what I mean?
![See Image](https://user-images.githubusercontent.com/40444084/56413697-4ff9ef00-6256-11e9-9535-cc90b887c452.jpg)

**Comment by itsmattkc** [comment] 2019-04-19 09:17
Duplicate of #595, it's coming.

**Closed by itsmattkc** 2019-04-19 09:17 UTC

**Comment by brethnew** [comment] 2019-04-19 12:08
Sick
