### ISSUE TITLE
Open file from app association

### ISSUE THREAD

**Issue by gnolooo** [olive-editor/olive#1834] opened 2022-01-17 18:27 UTC
**Commit Hash** 

**Platform** 
Arch Linux

**Summary**
This is more of an information / feature request than an issue.
Does Olive AppImage for Linux support opening files?
I just had to manually configure mime types and combine it with .ove extension (not a problem at all) but when I try to open a file, Olive just launches a new session instead of opening that file (this happens even including %F placeholder in the custom .desktop file I created).
Also, I tried to open a file from terminal (`$ /my-path/olive.appimage my-file`) but this doesn't work either.
I'm inclined to think this is just a lacking feature, am I right? Would it be possible to add it?
Thanks anyway, keep it up with this awesome app!

**Additional Information / Output**

**Comment by itsmattkc** [comment] 2022-01-18 21:18
Ironically, while we only officially provide AppImages for simplicity of deployment, both issues you mention (having to manually configure associations and the file argument not working) are both AppImage-exclusive. If you compiled manually (and ran `make install`) or installed through a package manager (AUR, since you mentioned you're on Arch), both of these would have worked out of the box.

Apparently there are ways to set up associations with AppImages, but I'm not entirely sure how currently (maybe by adding to the start of the `AppRun` and ensuring they're configured every load?) It could be seen as a limitation of AppImages that they're portable by design, and aren't really "installed", so there's no obvious step where setting up associations would be appropriate. But apparently some other AppImages are capable of doing so.

The second issue is simply a bug, while Olive the program supports a filename/project as an argument, our AppRun implementation wasn't passing the arguments through. That's been fixed in a55e142ed0fad94d152e3a5795ae34b5361d7485 and since that's the main issue here, I'll close this now

**Closed by itsmattkc** 2022-01-18 21:18 UTC
Labels: Triage

**Comment by gnolooo** [comment] 2022-01-19 10:03
I use AppImage because, even if I'm on Arch and I have AUR, it's not updated (currently, there are two Olive packages on AUR, `olive` - which is 0.1 version - and `olive-git` - last updated in december), and also building from source, which is my only other alternative, is quite annoying in a unstable-nightly-builds phase. But I totally understand the fact that my issue is AppImage-related and not Olive-related, so thank you for your explanation. Also, I can confirm you that latest version is working, so I'll stick to AppImage (imho, having to do a little bit of tweaking and manual configuration one time is better than building from source every day). Thank you guys for your work!
