### ISSUE TITLE
[EXPORT] Exporting video ends up consuming all machine memory and process being killed by OOM Killer

### ISSUE THREAD

**Issue by callegar** [olive-editor/olive#1501] opened 2021-02-27 21:22 UTC
**Commit Hash** 
1cd07bc1 (later versions are untestable as they crash opening project files)

**Platform** 
Ubuntu 20.04

**Summary**
Trying to export a video seems to work. However, there must be some significant memory management issue as the memory consumption goes higher and higher as the exporting progresses until all the memory is exhausted (I have 16GB of RAM and 20 of swap and all gets used) and the process gets killed by the out of memory killer.

**Additional Information / Output**

**Comment by a-teammate** [comment] 2021-02-28 22:32
Offtopic comment:
Thank you for saving my day!
I was looking forever for a version of olive for ubuntu 20.04, which let me open my files!

**Comment by Mennaruuk** [comment] 2021-03-05 18:45
tbh I'm still having trouble opening files with `1cd07bc1`.

**Comment by itsmattkc** [comment] 2021-03-20 12:24
Might be a duplicate of #1418?

**Comment by itsmattkc** [comment] 2021-03-22 12:50
With further investigation, I believe this is indeed a duplicate of #1418.

**Closed by itsmattkc** 2021-03-22 12:50 UTC
Labels: Export, Triage
