### ISSUE TITLE
[Feature Request] Import .xcf Files as Nested Sequence

### ISSUE THREAD

**Issue by Nordy13** [olive-editor/olive#988] opened 2019-06-02 01:20 UTC
A feature that would be useful for GIMP users. Every layer will be an image.

**Comment by libreartist** [comment] 2019-06-02 02:13
What if there are users of other graphic applications around? Doesn't it root for a common layered format supported by all such photo editing tools?

**Comment by sobotka** [comment] 2019-06-02 04:58
XCF is a steaming pile of garbage.

Olive is intended to treat still image files as first class citizens. As such, proper file formats such as EXR are preferred over pure junk.

**Comment by libreartist** [comment] 2019-06-02 18:06
Wow! If it could be done as something like "import as layers" option for EXR files, it could be the most colour accurate workflow to preserve layers. And imagine that, as Gimp is soon to have complete ACES setup, and we already have that one in Krita, Blender, RawTherapee and darktable, we can preserve colour accuracy, as well as the layers in any (open source) vfx workflows!

**Comment by libreartist** [comment] 2019-06-07 13:02
Hi,
Will the following link be useful?
https://natron.readthedocs.io/en/master/plugins/fr.inria.openfx.OpenRaster.html

It states of OpenRaster file (stack of PNGs, and svg layers) with readability via a openfx plugin, supported with opencolorio configuration. Also, as PNG can hold custom icc profiles (it means linear gamma, with the use of rec2020 and Aces profiles), can we somehow make use of it (especially considering ocio)? ... since Olive is underway with ocio support and is about to support openfx in near future?

**Comment by sobotka** [comment] 2019-06-07 13:18
PNG is absolute garbage. The fact that everyone in open source latched onto it tells you that very few people suggesting it have pushed pixels.

**Comment by libreartist** [comment] 2019-06-07 14:00
Then, can the same layer stack import be achieved with OpenEXR? (for raster images)

**Comment by libreartist** [comment] 2019-06-07 14:10
Afaik, sorry, Gimp is unable to identify the layers of an EXR image that I have used, but Krita does perfect.

**Comment by sobotka** [comment] 2019-06-07 14:11
Seems like GIMP has some problems, then.

**Comment by libreartist** [comment] 2019-06-07 14:21
And, digging into Krita's rep, I found: https://github.com/KDE/krita/tree/master/plugins/impex/exr

Hope, this could be useful.
And, sorry, my conversation may seem monotonous.

**Comment by itsmattkc** [comment] 2019-07-10 03:01
Duplicate of #982

**Closed by itsmattkc** 2019-07-10 03:01 UTC
