### ISSUE TITLE
[CRASH] Olive crashes when dropping an MP4 Video to Timeline

### ISSUE THREAD

**Issue by NimrodHU** [olive-editor/olive#1187] opened 2020-09-16 19:40 UTC
**Commit Hash**
007b9f28-x86_64.AppImage (plus an older build: 9ddcd2a2-x86_64.AppImage)

**Platform**
Kubuntu 20.04 LTS 64-bit

**Summary**
Olive chrashes, when dragging & dropping an imported *.mp4 file to the timeline.

**Steps to Reproduce**
1. Create sequence
2. Import --> *any .mp4 video file*
3. Drag-and-drop to timeline --> Olive crashes

**Backtrace**
This is what the terminal displayed, when the crash happened:
```
[DEBUG] Extracting default OCIO config to "/tmp/olivevideoeditor.org/Olive/ocioconf" ((null):0)
[INFO] Using Qt version: 5.11.0 ((null):0)
[DEBUG] Using graphics driver: X.Org ((null):0)
[INFO] Setting output audio device to "alsa_output.pci-0000_00_01.1.hdmi-stereo" ((null):0)
[DEBUG] No arenas, creating new... ((null):0)
Segmentation fault (core dumped)
```

**Additional Information**
When the crash happens, it generates about 98 empty folders (with names such as 00, 0e, 2b, 5d, 24, 9f, 58, ab, ff) and (depending on how many times the crash had been attempted) a .pcm file (seems to empty, I checked them in nano and cat).
I tried to run it as sudo, with no success; the crash was triggered.

**Comment by ThomasWilshaw** [comment] 2020-09-16 19:46
Are you able to generate a gdb back trace? https://github.com/olive-editor/olive/wiki/Debug-Logs-on-crash

**Comment by NimrodHU** [comment] 2020-09-16 20:03
> Are you able to generate a gdb back trace? https://github.com/olive-editor/olive/wiki/Debug-Logs-on-crash

The only difference when debugging the crash with GDB is that the program doesn't quit immediately, rather the graphical elements of the window freeze (buttons, menu bars, containers, no reaction to mouse clicks...).
```
Starting program: /media/nimrod/DATA/xd/Olive-007b9f28-x86_64.AppImage 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 11313]
process 11309 is executing new program: /tmp/.mount_Olive-u9xPal/local/bin/olive-editor
warning: Loadable section ".dynstr" outside of ELF segments
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffd34e9700 (LWP 11318)]
[New Thread 0x7fffcf9d9700 (LWP 11319)]
[DEBUG] Extracting default OCIO config to "/tmp/olivevideoeditor.org/Olive/ocioconf" ((null):0)
[New Thread 0x7fffcd465700 (LWP 11322)]
[New Thread 0x7fffccb0f700 (LWP 11323)]
[New Thread 0x7fffc396b700 (LWP 11324)]
[New Thread 0x7fffc316a700 (LWP 11325)]
[New Thread 0x7fffc2969700 (LWP 11326)]
[New Thread 0x7fffc2168700 (LWP 11327)]
[New Thread 0x7fffc1967700 (LWP 11328)]
[New Thread 0x7fffc1166700 (LWP 11329)]
[New Thread 0x7fffc0965700 (LWP 11330)]
[New Thread 0x7fff9bfff700 (LWP 11331)]
[New Thread 0x7fff9b7fe700 (LWP 11332)]
[New Thread 0x7fff9affd700 (LWP 11333)]
[INFO] Using Qt version: 5.11.0 ((null):0)
[New Thread 0x7fff9a7fc700 (LWP 11334)]
[New Thread 0x7fff99ffb700 (LWP 11335)]
[New Thread 0x7fff997fa700 (LWP 11336)]
[New Thread 0x7fff98ff9700 (LWP 11337)]
[New Thread 0x7fff7bfff700 (LWP 11338)]
[New Thread 0x7fff7b7fe700 (LWP 11339)]
[New Thread 0x7fff7affd700 (LWP 11340)]
[DEBUG] Using graphics driver: X.Org ((null):0)
[Thread 0x7fff7affd700 (LWP 11340) exited]
[New Thread 0x7fff7affd700 (LWP 11342)]
[New Thread 0x7fff7982a700 (LWP 11343)]
[INFO] Setting output audio device to "alsa_output.pci-0000_00_01.1.hdmi-stereo" ((null):0)
[New Thread 0x7fff79029700 (LWP 11349)]
[New Thread 0x7fff78828700 (LWP 11350)]
[Thread 0x7fff78828700 (LWP 11350) exited]
[New Thread 0x7fff78828700 (LWP 11353)]
[New Thread 0x7fff5bffd700 (LWP 11354)]
[New Thread 0x7fff5b7fc700 (LWP 11355)]
[New Thread 0x7fff5affb700 (LWP 11356)]
[New Thread 0x7fff5a7fa700 (LWP 11357)]
[Thread 0x7fff78828700 (LWP 11353) exited]
[Thread 0x7fff5bffd700 (LWP 11354) exited]
[Thread 0x7fff5b7fc700 (LWP 11355) exited]
[Thread 0x7fff5affb700 (LWP 11356) exited]
[Thread 0x7fff5a7fa700 (LWP 11357) exited]
[New Thread 0x7fff5a7fa700 (LWP 11358)]
[New Thread 0x7fff5affb700 (LWP 11359)]
[New Thread 0x7fff5b7fc700 (LWP 11360)]
[New Thread 0x7fff5bffd700 (LWP 11361)]
[WARNING] Tried to allocate sample buffer with zero sample count ((null):0)
[WARNING] Tried to allocate sample buffer with zero sample count ((null):0)
[New Thread 0x7fff78828700 (LWP 11362)]
[New Thread 0x7fff59ff9700 (LWP 11363)]
[New Thread 0x7fff597f8700 (LWP 11365)]
[New Thread 0x7fff58ff7700 (LWP 11364)]
[New Thread 0x7fff43fff700 (LWP 11366)]
[New Thread 0x7fff437fe700 (LWP 11367)]
[New Thread 0x7fff42ffd700 (LWP 11368)]
[New Thread 0x7fff427fc700 (LWP 11369)]
[New Thread 0x7fff41ffb700 (LWP 11370)]
[New Thread 0x7fff417fa700 (LWP 11371)]
[DEBUG] No arenas, creating new... ((null):0)
```

**Comment by ThomasWilshaw** [comment] 2020-09-16 20:08
When it freezes up, type `bt` into gdb to get the actual backtrace.

**Comment by NimrodHU** [comment] 2020-09-16 20:12
> When it freezes up, type `bt` into gdb to get the actual backtrace.

```
(gdb) run
Starting program: /media/nimrod/DATA/xd/Olive-007b9f28-x86_64.AppImage 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 11547]
process 11543 is executing new program: /tmp/.mount_Olive-ym2Eu3/local/bin/olive-editor
warning: Loadable section ".dynstr" outside of ELF segments
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffd34e9700 (LWP 11552)]
[New Thread 0x7fffcf9d9700 (LWP 11553)]
[DEBUG] Extracting default OCIO config to "/tmp/olivevideoeditor.org/Olive/ocioconf" ((null):0)
[New Thread 0x7fffcd465700 (LWP 11554)]
[New Thread 0x7fffccb0f700 (LWP 11555)]
[New Thread 0x7fffc396b700 (LWP 11556)]
[New Thread 0x7fffc316a700 (LWP 11557)]
[New Thread 0x7fffc2969700 (LWP 11558)]
[New Thread 0x7fffc2168700 (LWP 11559)]
[New Thread 0x7fffc1967700 (LWP 11560)]
[New Thread 0x7fffc1166700 (LWP 11561)]
[New Thread 0x7fffc0965700 (LWP 11562)]
[New Thread 0x7fff9bfff700 (LWP 11563)]
[New Thread 0x7fff9b7fe700 (LWP 11564)]
[New Thread 0x7fff9affd700 (LWP 11565)]
[INFO] Using Qt version: 5.11.0 ((null):0)
[New Thread 0x7fff9a7fc700 (LWP 11566)]
[New Thread 0x7fff99ffb700 (LWP 11567)]
[New Thread 0x7fff997fa700 (LWP 11568)]
[New Thread 0x7fff98ff9700 (LWP 11569)]
[New Thread 0x7fff7bfff700 (LWP 11572)]
[New Thread 0x7fff7b7fe700 (LWP 11573)]
[New Thread 0x7fff7affd700 (LWP 11574)]
[DEBUG] Using graphics driver: X.Org ((null):0)
[Thread 0x7fff7affd700 (LWP 11574) exited]
[New Thread 0x7fff7affd700 (LWP 11576)]
[New Thread 0x7fff7a05a700 (LWP 11577)]
[INFO] Setting output audio device to "alsa_output.pci-0000_00_01.1.hdmi-stereo" ((null):0)
[New Thread 0x7fff79859700 (LWP 11579)]
[New Thread 0x7fff5bffd700 (LWP 11580)]
[Thread 0x7fff5bffd700 (LWP 11580) exited]
[New Thread 0x7fff5bffd700 (LWP 11583)]
[New Thread 0x7fff5b7fc700 (LWP 11584)]
[New Thread 0x7fff5affb700 (LWP 11585)]
[New Thread 0x7fff5a7fa700 (LWP 11586)]
[New Thread 0x7fff59ff9700 (LWP 11587)]
[Thread 0x7fff5bffd700 (LWP 11583) exited]
[Thread 0x7fff5b7fc700 (LWP 11584) exited]
[Thread 0x7fff5affb700 (LWP 11585) exited]
[Thread 0x7fff5a7fa700 (LWP 11586) exited]
[Thread 0x7fff59ff9700 (LWP 11587) exited]
[New Thread 0x7fff59ff9700 (LWP 11588)]
[New Thread 0x7fff5a7fa700 (LWP 11589)]
[New Thread 0x7fff5affb700 (LWP 11590)]
[New Thread 0x7fff5b7fc700 (LWP 11591)]
[WARNING] Tried to allocate sample buffer with zero sample count ((null):0)
[WARNING] Tried to allocate sample buffer with zero sample count ((null):0)
[New Thread 0x7fff5bffd700 (LWP 11592)]
[New Thread 0x7fff597f8700 (LWP 11593)]
[New Thread 0x7fff58ff7700 (LWP 11594)]
[New Thread 0x7fff43fff700 (LWP 11595)]
[New Thread 0x7fff437fe700 (LWP 11596)]
[New Thread 0x7fff42ffd700 (LWP 11597)]
[New Thread 0x7fff427fc700 (LWP 11598)]
[New Thread 0x7fff417fa700 (LWP 11600)]
[New Thread 0x7fff41ffb700 (LWP 11599)]
[New Thread 0x7fff40ff9700 (LWP 11601)]
[DEBUG] No arenas, creating new... ((null):0)
--Type <RET> for more, q to quit, c to continue without paging--bt

Thread 35 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff5b7fc700 (LWP 11591)]
0x00007ffff5556ff2 in ?? () from /tmp/.mount_Olive-ym2Eu3/local/bin/../lib/libswscale.so.5
(gdb) 
```

**Comment by ThomasWilshaw** [comment] 2020-09-16 21:24
I suspect this is the same issue as #1176

**Comment by itsmattkc** [comment] 2020-09-17 02:24
Yeah I think it's a duplicate of #1176

**Closed by itsmattkc** 2020-09-17 02:24 UTC
Labels: Crash, Triage
