### ISSUE TITLE
[NODES] Disconnecting and connecting a Media node to Transform node breaks the video

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1697] opened 2021-07-30 11:08 UTC
**Commit Hash** 
3f785f30

**Platform** 
macOS 10.14.6

**Summary**
Disconnecting and connecting a Media node to Transform node breaks the video:

https://user-images.githubusercontent.com/5942369/127644306-5d05dd3e-45d8-4b87-974d-8ddccb2844e0.mov

**Additional Information / Output**
Doing a similar thing with the Transform node and the Clip node works fine, it's just the Media one with the Transform one

**Comment by itsmattkc** [comment] 2021-07-30 20:26
Duplicate of #1650 (specifically the ability to select outputs).

**Closed by itsmattkc** 2021-07-30 20:26 UTC
Labels: Nodes/Compositing, Triage
