### ISSUE TITLE
[Feature Request] Finding Missing Files

### ISSUE THREAD

**Issue by MisterTeeXD** [olive-editor/olive#680] opened 2019-03-23 14:37 UTC
In Kdenlive, there is a window that pops up that says there are files missing and a button that allows us to tell the editor where it is. it would be awesome if this was in Olive.

**Comment by itsmattkc** [comment] 2019-03-23 23:05
Duplicate of #610, but yes it is planned

**Closed by itsmattkc** 2019-03-23 23:05 UTC
